// GENERATED by re/g_api_exports.py -- do not edit by hand.
//
// The C ABI of the original module: one definition per export. A body either forwards to a recovered
// implementation (the forwarding map below) or reports the call and returns the documented neutral value.
// Signatures are INFERRED -- see re/exports_table.json and lcns/docs/MAPPING.md.

#include "lcns/api.hpp"
#include "lcns/exports.hpp"
#include "lcns/exports_impl.hpp"

#include <cstdint>
#include <limits>

namespace lcns {
namespace dll {
namespace exports {

// Which exports the project implements, from the hand-written file below. Every entry not listed there
// fails loudly instead of guessing, and its original bytes are embedded and verified.
extern const Forwarding kForwarding[];
extern const std::size_t kForwardingCount;
#include "lcns/detail/exports_forwarding.inc"

}  // namespace exports
}  // namespace dll
}  // namespace lcns

// ---------------------------------------------------------------- the 168 definitions

namespace lcns {
namespace dll {

// ordinal 1/2  rva 0x16420  490 bytes  // AddPolygonHoleToPart
// signature from the inferred typed table
extern "C" int AddPolygonHoleToPart(Part, int, const double*) {
    lcns::dll::exports::notReversed(0u);
    return 0;
}

// ordinal 3/4  rva 0x162B0  353 bytes  // AddPolygonPart
// signature from the inferred typed table
extern "C" Part AddPolygonPart(Order, int, int, const double*, int) {
    lcns::dll::exports::notReversed(1u);
    return nullptr;
}

// ordinal 5/6  rva 0x15BF0  1717 bytes
// signature from the inferred typed table
extern "C" Sheet AddSheet(Order, int, double, double, int) {
    lcns::dll::exports::notReversed(2u);
    return nullptr;
}

// ordinal 7/8  rva 0x118F0  3660 bytes  *** ERROR unterminated/cancelled computation ***
// signature from the inferred typed table
extern "C" int DeleteLaunchingOrder(Order) {
    lcns::dll::exports::notReversed(3u);
    return 0;
}

// ordinal 9/10  rva 0x0B1D0  370 bytes  <h1> Problem contains invalid parts. </h1>
// signature from the inferred typed table
extern "C" int GenerateHtmlLaunchingOrderReport(Order, const char*) {
    lcns::dll::exports::notReversed(4u);
    return 0;
}

// ordinal 11/12  rva 0x0B350  247 bytes
// signature from the inferred typed table
extern "C" int GenerateHtmlSolutionReport(Solution, const char*) {
    lcns::dll::exports::notReversed(5u);
    return 0;
}

// ordinal 13/14  rva 0x0B8D0  378 bytes  source_version
// signature from the inferred typed table
extern "C" int GenerateLaunchingOrderProblem(Order, const char*) {
    lcns::dll::exports::notReversed(6u);
    return 0;
}

// ordinal 15/16  rva 0x107E0  155 bytes  // GetComputationStatus
// signature from the inferred typed table
extern "C" int GetComputationStatus(void*) {
    lcns::dll::exports::notReversed(7u);
    return 0;
}

// ordinal 17/18  rva 0x0B100  34 bytes
// signature from the inferred typed table
extern "C" int GetMultiplicity(Part) {
    lcns::dll::exports::notReversed(8u);
    return 0;
}

// ordinal 19/20  rva 0x0D460  688 bytes  cns.cpp
// signature from the inferred typed table
extern "C" NestedPart GetNestedPart(Nesting, int) {
    lcns::dll::exports::notReversed(9u);
    return 0;
}

// ordinal 21/22  rva 0x10F30  490 bytes  cns.cpp
// signature from the inferred typed table
extern "C" Nesting GetNesting(Solution, int) {
    lcns::dll::exports::notReversed(10u);
    return 0;
}

// ordinal 23/24  rva 0x0B190  63 bytes
// signature from the inferred typed table
extern "C" int GetNumberOfNestedParts(Nesting) {
    lcns::dll::exports::notReversed(11u);
    return 0;
}

// ordinal 25/26  rva 0x0B0C0  52 bytes
// signature from the inferred typed table
extern "C" int GetNumberOfNestings(Solution) {
    lcns::dll::exports::notReversed(12u);
    return 0;
}

// ordinal 27/28  rva 0x0C5E0  36 bytes
// signature from the inferred typed table
extern "C" int GetPartUserString(Part, const char**) {
    lcns::dll::exports::notReversed(13u);
    return 0;
}

// ordinal 29/30  rva 0x0B510  43 bytes
// signature from the inferred typed table
extern "C" int GetPartWithBadGeometry(Order) {
    lcns::dll::exports::notReversed(14u);
    return 0;
}

// ordinal 31/32  rva 0x0B600  332 bytes  number <= order->sheets.size()
// signature from the inferred typed table
extern "C" Sheet GetSheet(Order, int) {
    lcns::dll::exports::notReversed(15u);
    return nullptr;
}

// ordinal 33/34  rva 0x0B0A0  29 bytes
// signature from the inferred typed table
extern "C" Solution GetSolution(Order) {
    lcns::dll::exports::notReversed(16u);
    return 0;
}

// ordinal 35/36  rva 0x06100  3894 bytes  c:/Temp/cns.pb.json
// signature from the inferred typed table
extern "C" void* LaunchComputation(Order, const char*, const char*, double) {
    lcns::dll::exports::notReversed(17u);
    return nullptr;
}

// ordinal 37/38  rva 0x14620  1081 bytes
// signature from the inferred typed table
extern "C" Order NewLaunchingOrder(int, double, double) {
    lcns::dll::exports::notReversed(18u);
    return nullptr;
}

// ordinal 39/40  rva 0x0CF20  303 bytes  cns.cpp
// signature from the inferred typed table
extern "C" void SetInterpartGap(Order, double) {
    lcns::dll::exports::notReversed(19u);
}

// ordinal 41/42  rva 0x0C1A0  241 bytes
// signature from the inferred typed table
extern "C" void SetPartAuthorizations(Order, int, int) {
    lcns::dll::exports::notReversed(20u);
}

// ordinal 43/44  rva 0x0C420  446 bytes
// signature from the inferred typed table
extern "C" void SetPartUserString(Order, int, const char*) {
    lcns::dll::exports::notReversed(21u);
}

// ordinal 45/46  rva 0x0CCB0  527 bytes
// signature from the inferred typed table
extern "C" void SetSheetGaps(Order, double, double, double, double) {
    lcns::dll::exports::notReversed(22u);
}

// ordinal 47/48  rva 0x104D0  370 bytes  // WaitComputationTermination
// signature from the inferred typed table
extern "C" int WaitComputationTermination(void*) {
    lcns::dll::exports::notReversed(23u);
    return 0;
}

// ordinal 49/50  rva 0x10650  386 bytes  c:/Temp/computation_solution.html
// signature from the inferred typed table
extern "C" int WaitNextSolution(void*, int*) {
    lcns::dll::exports::notReversed(24u);
    return 0;
}

// ordinal 51/52  rva 0x02AB0  2134 bytes  cns_force_cloud
// signature from the inferred typed table
extern "C" void* LaunchLocalComputation(Order, double) {
    lcns::dll::exports::notReversed(25u);
    return nullptr;
}

// ordinal 53/54  rva 0x10880  155 bytes  CancelComputation 
// signature from the inferred typed table
extern "C" int CancelComputation(void*) {
    lcns::dll::exports::notReversed(26u);
    return 0;
}

// ordinal 55/56  rva 0x0B020  52 bytes
// signature synthesized from the register analysis: 3 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t GetPartUserStringEx(std::intptr_t, std::intptr_t, std::intptr_t) {
    lcns::dll::exports::notReversed(27u);
    return 0;
}

// ordinal 57/58  rva 0x0C670  446 bytes
// signature from the inferred typed table
extern "C" void SetSheetUserString(Order, int, const char*) {
    lcns::dll::exports::notReversed(28u);
}

// ordinal 59/60  rva 0x0C830  353 bytes
// signature from the inferred typed table
extern "C" int GetSheetUserString(Sheet, const char**) {
    lcns::dll::exports::notReversed(29u);
    return 0;
}

// ordinal 61/62  rva 0x0B060  52 bytes
// signature synthesized from the register analysis: 3 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t GetSheetUserStringEx(std::intptr_t, std::intptr_t, std::intptr_t) {
    lcns::dll::exports::notReversed(30u);
    return 0;
}

// ordinal 65/66  rva 0x11120  868 bytes
// signature from the inferred typed table
extern "C" void SetExtraParameters(Order, const char*, double) {
    lcns::dll::exports::notReversed(31u);
}

// ordinal 67/68  rva 0x13C90  411 bytes
// signature from the inferred typed table
extern "C" void SetSheetPriority(Order, int) {
    lcns::dll::exports::notReversed(32u);
}

// ordinal 69/70  rva 0x16B20  353 bytes  // AddNonRectangularPolygonSheet
// signature from the inferred typed table
extern "C" Sheet AddNonRectangularPolygonSheet(Order, int, int, const double*, int) {
    lcns::dll::exports::notReversed(33u);
    return nullptr;
}

// ordinal 71/72  rva 0x16970  426 bytes  // AddPolygonDefectToSheet
// signature from the inferred typed table
extern "C" int AddPolygonDefectToSheet(Sheet, const double*) {
    lcns::dll::exports::notReversed(34u);
    return 0;
}

// ordinal 73/74  rva 0x0D370  61 bytes
// signature from the inferred typed table
extern "C" void SetLocalEngine(Order, int, int) {
    lcns::dll::exports::notReversed(35u);
}

// ordinal 76/77  rva 0x0D430  36 bytes
// signature from the inferred typed table
extern "C" int UnLockLaunchingOrder(Order, int) {
    lcns::dll::exports::notReversed(36u);
    return 0;
}

// ordinal 78/79  rva 0x0CEC0  45 bytes
// signature from the inferred typed table
extern "C" void SetObjective(Order, Objective) {
    lcns::dll::exports::notReversed(37u);
}

// ordinal 80/81  rva 0x109C0  388 bytes
// signature from the inferred typed table
extern "C" void SetDefectGap(Order, double) {
    lcns::dll::exports::notReversed(38u);
}

// ordinal 82/83  rva 0x0D3B0  68 bytes
// signature from the inferred typed table
extern "C" void SetLocalMaximumThreads(Order, int) {
    lcns::dll::exports::notReversed(39u);
}

// ordinal 84/85  rva 0x0D400  36 bytes
// signature from the inferred typed table
extern "C" void SetLocalMaximumIterations(Order, int) {
    lcns::dll::exports::notReversed(40u);
}

// ordinal 86/87  rva 0x0D050  334 bytes
// signature from the inferred typed table
extern "C" void SetOrigin(Order, NestingOrigin) {
    lcns::dll::exports::notReversed(41u);
}

// ordinal 88/89  rva 0x0B490  31 bytes
// signature from the inferred typed table
extern "C" const char* GetBuildVersion() {
    // RE 0xB490, implemented in exports_impl.cpp: a logger call, then the data pointer of the std::string held by the
    // global at 0xA07660. That string is empty in the image, so the value is not recoverable and the implementation says so.
    return lcns::dll::exports::impl::getBuildVersion();
}

// ordinal 90/91  rva 0x0B470  31 bytes
// signature from the inferred typed table
extern "C" const char* GetBuildDate() {
    // RE 0xB470: same shape; the global at 0xA07690 holds a std::string whose data, at 0xB1F410, is "Jun 28 2019".
    return lcns::dll::exports::impl::getBuildDate();
}

// ordinal 92/93  rva 0x0B450  31 bytes
// signature from the inferred typed table
extern "C" int GetMajorVersion() {
    // RE 0xB450: same shape; the global at 0xA07670 holds a std::string whose data, at 0xB1F430, is "5.0".
    return lcns::dll::exports::impl::getMajorVersion();
}

// ordinal 94/95  rva 0x10CE0  584 bytes
// signature from the inferred typed table
extern "C" void AddPartSpecificAuthorizations(Order, int, int) {
    lcns::dll::exports::notReversed(45u);
}

// ordinal 96/97  rva 0x0B130  36 bytes
// signature from the inferred typed table
extern "C" double GetLength(Part) {
    lcns::dll::exports::notReversed(46u);
    return std::numeric_limits<double>::quiet_NaN();
}

// ordinal 98/99  rva 0x0C9A0  372 bytes
// signature from the inferred typed table
extern "C" void SetSheetGrainDirection(Order, int) {
    lcns::dll::exports::notReversed(47u);
}

// ordinal 100/101  rva 0x0B160  36 bytes
// signature from the inferred typed table
extern "C" double GetHeight(Part) {
    lcns::dll::exports::notReversed(48u);
    return std::numeric_limits<double>::quiet_NaN();
}

// ordinal 102/103  rva 0x16610  419 bytes  // AddExternalPolygonBoundaryToSheet
// signature synthesized from the register analysis: 3 integer register(s), 2 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" double AddExternalPolygonBoundaryToSheet(std::intptr_t, std::intptr_t, std::intptr_t, double, double) {
    lcns::dll::exports::notReversed(49u);
    return std::numeric_limits<double>::quiet_NaN();
}

// ordinal 104/105  rva 0x167C0  426 bytes  // AddExternalPolygonBoundaryToPart
// signature from the inferred typed table
extern "C" int AddExternalPolygonBoundaryToPart(Part, const double*) {
    lcns::dll::exports::notReversed(50u);
    return 0;
}

// ordinal 110/111  rva 0x14D10  1891 bytes
// signature from the inferred typed table
extern "C" Part AddPart(Order, int, int, const double*, int) {
    lcns::dll::exports::notReversed(51u);
    return nullptr;
}

// ordinal 112/113  rva 0x132E0  176 bytes
// signature from the inferred typed table
extern "C" int AddHoleToPart(Part, int, int, const double*) {
    lcns::dll::exports::notReversed(52u);
    return 0;
}

// ordinal 114/115  rva 0x13390  124 bytes
// signature from the inferred typed table
extern "C" int AddExternalBoundaryToPart(Part, int, const double*) {
    lcns::dll::exports::notReversed(53u);
    return 0;
}

// ordinal 116/117  rva 0x157A0  1098 bytes
// signature from the inferred typed table
extern "C" Sheet AddNonRectangularSheet(Order, int, int, const double*, int) {
    lcns::dll::exports::notReversed(54u);
    return nullptr;
}

// ordinal 118/119  rva 0x14190  124 bytes
// signature from the inferred typed table
extern "C" int AddDefectToSheet(Sheet, int, const double*) {
    lcns::dll::exports::notReversed(55u);
    return 0;
}

// ordinal 120/121  rva 0x14210  117 bytes
// signature synthesized from the register analysis: 3 integer register(s), 2 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t AddExternalBoundaryToSheet(std::intptr_t, std::intptr_t, std::intptr_t, double, double) {
    lcns::dll::exports::notReversed(56u);
    return 0;
}

// ordinal 122/123  rva 0x10920  155 bytes  TerminateComputation 
// signature from the inferred typed table
extern "C" int TerminateComputation(void*) {
    lcns::dll::exports::notReversed(57u);
    return 0;
}

// ordinal 124/125  rva 0x14A60  678 bytes
// signature from the inferred typed table
extern "C" int AddOpenCuttingPathToPart(Part, int, const double*) {
    lcns::dll::exports::notReversed(58u);
    return 0;
}

// ordinal 126/127  rva 0x0C2A0  382 bytes
// signature from the inferred typed table
extern "C" void SetPartPriority(Order, int, int) {
    lcns::dll::exports::notReversed(59u);
}

// ordinal 128/129  rva 0x0D1A0  353 bytes
// signature synthesized from the register analysis: 2 integer register(s), 1 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" double CNS_SetMultiplicityPreference(std::intptr_t, std::intptr_t, double) {
    lcns::dll::exports::notReversed(60u);
    return std::numeric_limits<double>::quiet_NaN();
}

// ordinal 130/131  rva 0x15480  404 bytes  // AddCircularPart
// signature from the inferred typed table
extern "C" Part AddCircularPart(Order, int, double, double, double, int) {
    lcns::dll::exports::notReversed(61u);
    return nullptr;
}

// ordinal 132/133  rva 0x13800  581 bytes  // AddCircularHoleToPart
// signature from the inferred typed table
extern "C" int AddCircularHoleToPart(Part, double, double, double) {
    lcns::dll::exports::notReversed(62u);
    return 0;
}

// ordinal 134/135  rva 0x15620  374 bytes  // AddRectanglePart
// signature from the inferred typed table
extern "C" Part AddRectanglePart(Order, int, double, double, double, double, int) {
    lcns::dll::exports::notReversed(63u);
    return nullptr;
}

// ordinal 136/137  rva 0x13A50  569 bytes  // AddRectangularHoleToPart
// signature from the inferred typed table
extern "C" int AddRectangularHoleToPart(Part, double, double, double, double) {
    lcns::dll::exports::notReversed(64u);
    return 0;
}

// ordinal 138/139  rva 0x14290  440 bytes
// signature from the inferred typed table
extern "C" int AddOptionalQuantityToPart(Part, int) {
    lcns::dll::exports::notReversed(65u);
    return 0;
}

// ordinal 140/141  rva 0x0E010  353 bytes
// signature from the inferred typed table
extern "C" void SetAutomaticStop(Order, int) {
    lcns::dll::exports::notReversed(66u);
}

// ordinal 142/143  rva 0x0E2D0  399 bytes
// signature from the inferred typed table
extern "C" void SetOffcutEvaluation(Order, double, double, double) {
    lcns::dll::exports::notReversed(67u);
}

// ordinal 144/145  rva 0x0DD90  36 bytes
// signature from the inferred typed table
extern "C" void SetFillLastNestingStrategy(Order, int) {
    lcns::dll::exports::notReversed(68u);
}

// ordinal 146/147  rva 0x0DDC0  33 bytes
// signature from the inferred typed table
extern "C" void SetShearMode(Order, int) {
    lcns::dll::exports::notReversed(69u);
}

// ordinal 148/149  rva 0x0E460  404 bytes
// signature from the inferred typed table
extern "C" void SetCommonCutMode(Order, int, int) {
    lcns::dll::exports::notReversed(70u);
}

// ordinal 150/151  rva 0x0E940  354 bytes
// signature from the inferred typed table
extern "C" void SetCommonCutSafetyPreference(Order, int, int) {
    lcns::dll::exports::notReversed(71u);
}

// ordinal 152/153  rva 0x0EAB0  468 bytes
// signature from the inferred typed table
extern "C" void SetCommonCutAuthorizations(Order, int, int, int) {
    lcns::dll::exports::notReversed(72u);
}

// ordinal 154/155  rva 0x0EC90  340 bytes
// signature from the inferred typed table
extern "C" void SetCommonCutCuttingPreference(Order, int, int) {
    lcns::dll::exports::notReversed(73u);
}

// ordinal 156/157  rva 0x0EDF0  337 bytes
// signature from the inferred typed table
extern "C" void SetCommonCutObjective(Order, double, double) {
    lcns::dll::exports::notReversed(74u);
}

// ordinal 158/159  rva 0x0D710  346 bytes  cns.cpp
// signature from the inferred typed table
extern "C" int GetNumberOfCommonCuts(Order) {
    lcns::dll::exports::notReversed(75u);
    return 0;
}

// ordinal 160/161  rva 0x0BA50  825 bytes  cns.cpp
// signature from the inferred typed table
extern "C" int GetCommonCut(Order, int, void*) {
    lcns::dll::exports::notReversed(76u);
    return 0;
}

// ordinal 162/163  rva 0x0E180  111 bytes
// signature from the inferred typed table
extern "C" int UnLockLaunchingOrderSntl(Order, const char*, const char*) {
    lcns::dll::exports::notReversed(77u);
    return 0;
}

// ordinal 164/165  rva 0x03310  66 bytes
// signature from the inferred typed table
extern "C" void* LaunchLimitedLocalComputation(Order, double) {
    lcns::dll::exports::notReversed(78u);
    return nullptr;
}

// ordinal 166/167  rva 0x0DE50  36 bytes
// signature from the inferred typed table
extern "C" void SetPartCommonCutMode(Order, int, int) {
    lcns::dll::exports::notReversed(79u);
}

// ordinal 168/169  rva 0x0B4B0  34 bytes
// signature from the inferred typed table
extern "C" double GetFillRatio(Solution) {
    lcns::dll::exports::notReversed(80u);
    return std::numeric_limits<double>::quiet_NaN();
}

// ordinal 170/171  rva 0x0BD90  470 bytes  cns.cpp
// signature from the inferred typed table
extern "C" int GetNestingDimensions(Nesting, double*, double*) {
    lcns::dll::exports::notReversed(81u);
    return 0;
}

// ordinal 172/173  rva 0x0CB20  388 bytes
// signature from the inferred typed table
extern "C" void SetSheetPrice(Order, double) {
    lcns::dll::exports::notReversed(82u);
}

// ordinal 174/175  rva 0x0EF50  479 bytes
// signature from the inferred typed table
extern "C" void SetMultiTorchMode(Order, int, int, double, double, int) {
    lcns::dll::exports::notReversed(83u);
}

// ordinal 176/177  rva 0x0F130  388 bytes
// signature from the inferred typed table
extern "C" void SetMultiTorchCuttingPreference(Order, int, int) {
    lcns::dll::exports::notReversed(84u);
}

// ordinal 178/179  rva 0x0F2C0  633 bytes
// signature from the inferred typed table
extern "C" void SetMultiTorchObjective(Order, double, double, double, double) {
    lcns::dll::exports::notReversed(85u);
}

// ordinal 180/181  rva 0x14450  449 bytes
// signature from the inferred typed table
extern "C" void SetExtraGapOnPart(Order, int, double) {
    lcns::dll::exports::notReversed(86u);
}

// ordinal 182/183  rva 0x0DD30  36 bytes
// signature synthesized from the register analysis: 2 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t CNS_SetFloatingMode(std::intptr_t, std::intptr_t) {
    lcns::dll::exports::notReversed(87u);
    return 0;
}

// ordinal 184/185  rva 0x0D870  826 bytes  cns.cpp
// signature from the inferred typed table
extern "C" int GetPartTorchInfos(Order, int, void*) {
    lcns::dll::exports::notReversed(88u);
    return 0;
}

// ordinal 186/187  rva 0x0F540  629 bytes
// signature from the inferred typed table
extern "C" void SetDetailedMultiTorchObjective(Order, double, double, double, double) {
    lcns::dll::exports::notReversed(89u);
}

// ordinal 188/189  rva 0x0D310  33 bytes
// signature synthesized from the register analysis: 2 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t CNS_SetNoMixPreference(std::intptr_t, std::intptr_t) {
    lcns::dll::exports::notReversed(90u);
    return 0;
}

// ordinal 190/191  rva 0x0DBB0  382 bytes
// signature synthesized from the register analysis: 2 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t CNS_SetNoOrientationMixOnPart(std::intptr_t, std::intptr_t) {
    lcns::dll::exports::notReversed(91u);
    return 0;
}

// ordinal 192/193  rva 0x0B4E0  38 bytes
// signature from the inferred typed table
extern "C" double GetNestingFillRatio(Nesting) {
    lcns::dll::exports::notReversed(92u);
    return std::numeric_limits<double>::quiet_NaN();
}

// ordinal 194/195  rva 0x18100  1955 bytes
// signature synthesized from the register analysis: 3 integer register(s), 3 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t AddPartVariantToPart(std::intptr_t, std::intptr_t, std::intptr_t, double, double, double) {
    lcns::dll::exports::notReversed(93u);
    return 0;
}

// ordinal 196/197  rva 0x16D00  49 bytes  // AddHoleToPartVariant
// signature synthesized from the register analysis: 3 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t AddHoleToPartVariant(std::intptr_t a, std::intptr_t b, std::intptr_t c) {
    // RE 0x16D00, ordinal 196/197: eleven instructions that keep the three arguments, log the export's own name and tail
    // call 0x132E0. The logger call is not reproduced; the rest is forwarded unchanged.
    lcns::dll::exports::impl::addHoleToPartVariant(reinterpret_cast<void*>(a), static_cast<int>(b),
                                                  reinterpret_cast<void*>(c));
    return 0;
}

// ordinal 198/199  rva 0x16D40  49 bytes  // CNS_AddExternalBoundaryToPartVariant
// signature synthesized from the register analysis: 3 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t CNS_AddExternalBoundaryToPartVariant(std::intptr_t a, std::intptr_t b, std::intptr_t c) {
    // RE 0x16D40, ordinal 198/199: the SAME eleven instructions and the same tail target, so this delegates rather than
    // repeating its twin. Kept as its own entry point because the module has two and the ordinals record the distinction.
    lcns::dll::exports::impl::addExternalBoundaryToPartVariant(reinterpret_cast<void*>(a), static_cast<int>(b),
                                                               reinterpret_cast<void*>(c));
    return 0;
}

// ordinal 200/201  rva 0x16D80  96 bytes  // CNS_AddOpenCuttingPathToPartVariant
// signature synthesized from the register analysis: 4 integer register(s), 1 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" double CNS_AddOpenCuttingPathToPartVariant(std::intptr_t a, std::intptr_t b, std::intptr_t c, std::intptr_t d, double e) {
    lcns::dll::exports::impl::addOpenCuttingPathToPartVariant(reinterpret_cast<void*>(a), reinterpret_cast<const void*>(b), static_cast<int>(c),
                                                          reinterpret_cast<void*>(d), e);
    return 0.0;
}

// ordinal 202/203  rva 0x16DE0  61 bytes  // CNS_SetPartVariantAuthorizations
// signature synthesized from the register analysis: 3 integer register(s), 1 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t CNS_SetPartVariantAuthorizations(std::intptr_t a, std::intptr_t b, std::intptr_t c, double d) {
    lcns::dll::exports::impl::setPartVariantAuthorizations(reinterpret_cast<void*>(a), static_cast<int>(b), static_cast<int>(c), d);
    return 0;
}

// ordinal 204/205  rva 0x16E20  63 bytes  // CNS_AddPartVariantSpecificAuthorizations
// signature synthesized from the register analysis: 2 integer register(s), 2 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t CNS_AddPartVariantSpecificAuthorizations(std::intptr_t, std::intptr_t, double, double) {
    lcns::dll::exports::notReversed(98u);
    return 0;
}

// ordinal 206/207  rva 0x16E60  1727 bytes
// signature from the inferred typed table
extern "C" NestedPart GetNestedPartPartVariant(Nesting, int) {
    lcns::dll::exports::notReversed(99u);
    return 0;
}

// ordinal 208/209  rva 0x16CB0  57 bytes
// signature synthesized from the register analysis: 2 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t sub_16CB0(std::intptr_t, std::intptr_t) {
    lcns::dll::exports::notReversed(100u);
    return 0;
}

// ordinal 210/211  rva 0x16CF0  8 bytes
// signature synthesized from the register analysis: 1 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t sub_16CF0(std::intptr_t) {
    lcns::dll::exports::notReversed(101u);
    return 0;
}

// ordinal 212/213  rva 0x0CEF0  45 bytes
// signature from the inferred typed table
extern "C" void SetShearGap(Order, double) {
    lcns::dll::exports::notReversed(102u);
}

// ordinal 214/215  rva 0x11490  423 bytes
// signature from the inferred typed table
extern "C" void SetIncompatibleSheet(Order, int, int) {
    lcns::dll::exports::notReversed(103u);
}

// ordinal 216/217  rva 0x03360  52 bytes  // LaunchEstimateLocalComputation
// signature from the inferred typed table
extern "C" void* LaunchEstimateLocalComputation(Order, double) {
    lcns::dll::exports::notReversed(104u);
    return nullptr;
}

// ordinal 218/219  rva 0x11640  483 bytes  cns.cpp
// signature from the inferred typed table
extern "C" void AddSuggestedPartsGrouping(Order, int, int) {
    lcns::dll::exports::notReversed(105u);
}

// ordinal 220/221  rva 0x0F7C0  1072 bytes  cns.cpp
// signature from the inferred typed table
extern "C" void AddPartToSuggestedPartsGrouping(Order, int, int) {
    lcns::dll::exports::notReversed(106u);
}

// ordinal 222/223  rva 0x0D340  33 bytes
// signature synthesized from the register analysis: 2 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t CNS_SetNoSheetMixPreference(std::intptr_t, std::intptr_t) {
    lcns::dll::exports::notReversed(107u);
    return 0;
}

// ordinal 224/225  rva 0x0BF70  148 bytes
// signature from the inferred typed table
extern "C" int GenerateDxfNesting(Nesting, const char*) {
    lcns::dll::exports::notReversed(108u);
    return 0;
}

// ordinal 226/227  rva 0x0C010  386 bytes
// signature from the inferred typed table
extern "C" const char* GetPCId() {
    lcns::dll::exports::notReversed(109u);
    return nullptr;
}

// ordinal 228/229  rva 0x0E260  111 bytes
// signature from the inferred typed table
extern "C" int UnLockLaunchingOrderPCId(Order, const char*, const char*) {
    lcns::dll::exports::notReversed(110u);
    return 0;
}

// ordinal 230/231  rva 0x09AF0  452 bytes  // NewNoFitContext
// signature from the inferred typed table
extern "C" NoFitContext NewNoFitContext(void*) {
    lcns::dll::exports::notReversed(111u);
    return 0;
}

// ordinal 232/233  rva 0x09CC0  568 bytes
// signature from the inferred typed table
extern "C" void DeleteNoFitContext(NoFitContext) {
    lcns::dll::exports::notReversed(112u);
}

// ordinal 234/235  rva 0x08AC0  939 bytes  //GetNoFitMap
// signature from the inferred typed table
extern "C" NoFitGeometry GetNoFitMap(NoFitContext, int, int) {
    lcns::dll::exports::notReversed(113u);
    return 0;
}

// ordinal 236/237  rva 0x08A10  171 bytes
// signature from the inferred typed table
extern "C" void DeleteNoFitGeometry(NoFitGeometry) {
    lcns::dll::exports::notReversed(114u);
}

// ordinal 238/239  rva 0x089D0  54 bytes
// signature from the inferred typed table
extern "C" int NoFitGetNumberOfExternalPolygons(NoFitGeometry) {
    lcns::dll::exports::notReversed(115u);
    return 0;
}

// ordinal 240/241  rva 0x08E70  335 bytes  cns_no_fit.cpp
// signature from the inferred typed table
extern "C" int NoFitGetNumberOfInternalHoles(NoFitGeometry, int) {
    lcns::dll::exports::notReversed(116u);
    return 0;
}

// ordinal 242/243  rva 0x08FC0  497 bytes
// signature from the inferred typed table
extern "C" int NoFitGetNumberOfPoints(NoFitGeometry, int, int, int) {
    lcns::dll::exports::notReversed(117u);
    return 0;
}

// ordinal 244/245  rva 0x091C0  366 bytes  cns_no_fit.cpp
// signature from the inferred typed table
extern "C" int NoFitGetPoint(NoFitGeometry, int, int, int, double*, double*) {
    lcns::dll::exports::notReversed(118u);
    return 0;
}

// ordinal 246/247  rva 0x188D0  529 bytes
// signature from the inferred typed table
extern "C" void SetMarkMode(Order, int) {
    lcns::dll::exports::notReversed(119u);
}

// ordinal 248/249  rva 0x18AF0  889 bytes
// signature from the inferred typed table
extern "C" int GetNumberOfMarks(Order) {
    lcns::dll::exports::notReversed(120u);
    return 0;
}

// ordinal 250/251  rva 0x18E70  1312 bytes
// signature from the inferred typed table
extern "C" int GetMark(Order, int) {
    lcns::dll::exports::notReversed(121u);
    return 0;
}

// ordinal 252/253  rva 0x0B540  177 bytes
// signature from the inferred typed table
extern "C" int AsyncCancelAllComputationsAndDeleteLaunchingOrder(Order) {
    lcns::dll::exports::notReversed(122u);
    return 0;
}

// ordinal 254/255  rva 0x17520  3027 bytes
// signature synthesized from the register analysis: 4 integer register(s), 3 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" double AddRotatedPartVariantToPart(std::intptr_t, std::intptr_t, std::intptr_t, std::intptr_t, double, double, double) {
    lcns::dll::exports::notReversed(123u);
    return std::numeric_limits<double>::quiet_NaN();
}

// ordinal 256/257  rva 0x0FBF0  244 bytes
// signature from the inferred typed table
extern "C" void SetRowMode(Order, int) {
    lcns::dll::exports::notReversed(124u);
}

// ordinal 258/259  rva 0x0FCF0  568 bytes
// signature from the inferred typed table
extern "C" void SetPipeMode(Order, int) {
    lcns::dll::exports::notReversed(125u);
}

// ordinal 260/261  rva 0x13410  512 bytes  // AddCircularExternalBoundaryToPart
// signature from the inferred typed table
extern "C" int AddCircularExternalBoundaryToPart(Part, double, double, double) {
    lcns::dll::exports::notReversed(126u);
    return 0;
}

// ordinal 262/263  rva 0x13610  486 bytes  // AddRectangularExternalBoundaryToPart
// signature from the inferred typed table
extern "C" int AddRectangularExternalBoundaryToPart(Part, double, double, double, double) {
    lcns::dll::exports::notReversed(127u);
    return 0;
}

// ordinal 264/265  rva 0x0FF30  271 bytes
// signature from the inferred typed table
extern "C" int GetNumberOfRows(Order) {
    lcns::dll::exports::notReversed(128u);
    return 0;
}

// ordinal 266/267  rva 0x10040  384 bytes  cns.cpp
// signature from the inferred typed table
extern "C" int GetRow(Order, int, double*, double*) {
    lcns::dll::exports::notReversed(129u);
    return 0;
}

// ordinal 268/269  rva 0x0DE80  388 bytes
// signature from the inferred typed table
extern "C" void SetLocalEngineThreads(Order, int, int) {
    lcns::dll::exports::notReversed(130u);
}

// ordinal 270/271  rva 0x0AFE0  13 bytes
// signature synthesized from the register analysis: 1 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t sub_0AFE0(std::intptr_t) {
    lcns::dll::exports::notReversed(131u);
    return 0;
}

// ordinal 272/273  rva 0x19C40  411 bytes
// signature from the inferred typed table
extern "C" void SetLeatherMode(Order, int) {
    lcns::dll::exports::notReversed(132u);
}

// ordinal 274/275  rva 0x19DE0  350 bytes
// signature from the inferred typed table
extern "C" void AddLeatherQualityZoneInPart(Part, int, int, const double*) {
    lcns::dll::exports::notReversed(133u);
}

// ordinal 276/277  rva 0x1A0A0  331 bytes
// signature from the inferred typed table
extern "C" void AddLeatherQualityZoneInSheet(Sheet, int, int, const double*) {
    lcns::dll::exports::notReversed(134u);
}

// ordinal 278/279  rva 0x1AA90  944 bytes
// signature from the inferred typed table
extern "C" void CreateRestrictedZoneConstraint(Order, int, int) {
    lcns::dll::exports::notReversed(135u);
}

// ordinal 280/281  rva 0x1AE40  507 bytes
// signature from the inferred typed table
extern "C" void CNS_SetZoneRestrictedPart(Order, int, int) {
    lcns::dll::exports::notReversed(136u);
}

// ordinal 282/283  rva 0x1A7D0  286 bytes
// signature synthesized from the register analysis: 4 integer register(s), 4 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" double sub_1A7D0(std::intptr_t, std::intptr_t, std::intptr_t, std::intptr_t, double, double, double, double) {
    lcns::dll::exports::notReversed(137u);
    return std::numeric_limits<double>::quiet_NaN();
}

// ordinal 284/285  rva 0x1A210  1468 bytes
// signature from the inferred typed table
extern "C" void CNS_SheetAddRestrictedZone(Order, int, int, const double*) {
    lcns::dll::exports::notReversed(138u);
}

// ordinal 286/287  rva 0x0B000  18 bytes
// signature synthesized from the register analysis: 1 integer register(s), 1 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t sub_0B000(std::intptr_t, double) {
    lcns::dll::exports::notReversed(139u);
    return 0;
}

// ordinal 288/289  rva 0x0AFF0  10 bytes
// signature synthesized from the register analysis: 1 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t sub_0AFF0(std::intptr_t) {
    lcns::dll::exports::notReversed(140u);
    return 0;
}

// ordinal 290/291  rva 0x101C0  127 bytes
// signature from the inferred typed table
extern "C" int AddToolPathToPart(Part, int, const double*) {
    lcns::dll::exports::notReversed(141u);
    return 0;
}

// ordinal 292/293  rva 0x19F40  342 bytes   [label shared with the entry at ordinal 274]
// signature from the inferred typed table
extern "C" void AddLeatherQualityZoneInPart_o292(Part, int, int, const double*) {
    lcns::dll::exports::notReversed(142u);
}

// ordinal 294/295  rva 0x12C60  169 bytes
// signature from the inferred typed table
extern "C" int AddInflatedToolPathToPart(Part, double) {
    lcns::dll::exports::notReversed(143u);
    return 0;
}

// ordinal 296/297  rva 0x10240  124 bytes
// signature from the inferred typed table
extern "C" int AddHoleInToolPath(Part, int, const double*) {
    lcns::dll::exports::notReversed(144u);
    return 0;
}

// ordinal 298/299  rva 0x13E30  417 bytes
// signature from the inferred typed table
extern "C" void SetSpecificSheetOrigin(Order, int, double, double) {
    lcns::dll::exports::notReversed(145u);
}

// ordinal 300/301  rva 0x13FE0  417 bytes
// signature from the inferred typed table
extern "C" void SetSpecificSheetObjective(Order, int, int) {
    lcns::dll::exports::notReversed(146u);
}

// ordinal 302/303  rva 0x1A8F0  411 bytes
// signature from the inferred typed table
extern "C" void CNS_ForcePartOnBottomBorder(Order, int, int) {
    lcns::dll::exports::notReversed(147u);
}

// ordinal 304/305  rva 0x0DE20  33 bytes
// signature from the inferred typed table
extern "C" void SetShearRepulseFromBorders(Order, int) {
    lcns::dll::exports::notReversed(148u);
}

// ordinal 306/307  rva 0x12F40  894 bytes
// signature synthesized from the register analysis: 2 integer register(s), 3 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" double CNS_AddDefectFromNestedPart(std::intptr_t, std::intptr_t, double, double, double) {
    lcns::dll::exports::notReversed(149u);
    return std::numeric_limits<double>::quiet_NaN();
}

// ordinal 308/309  rva 0x10B50  395 bytes
// signature from the inferred typed table
extern "C" void CNS_CreateAssemblyGroup(Order, int) {
    lcns::dll::exports::notReversed(150u);
}

// ordinal 310/311  rva 0x11830  180 bytes
// signature from the inferred typed table
extern "C" void CNS_AddAssemblyGroupPart(Order, int, int, int) {
    lcns::dll::exports::notReversed(151u);
}

// ordinal 312/313  rva 0x0DD60  36 bytes
// signature synthesized from the register analysis: 2 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t CNS_SetOriginPackingMode(std::intptr_t, std::intptr_t) {
    lcns::dll::exports::notReversed(152u);
    return 0;
}

// ordinal 314/315  rva 0x12D10  552 bytes
// signature synthesized from the register analysis: 4 integer register(s), 2 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t CNS_AddOpenToolPathToPart(std::intptr_t, std::intptr_t, std::intptr_t, std::intptr_t, double, double) {
    lcns::dll::exports::notReversed(153u);
    return 0;
}

// ordinal 316/317  rva 0x10440  42 bytes
// signature synthesized from the register analysis: 2 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t CNS_SetEvaluateIntermediateNestingsAsLast(std::intptr_t, std::intptr_t) {
    lcns::dll::exports::notReversed(154u);
    return 0;
}

// ordinal 318/319  rva 0x09330  449 bytes  // NewNoFitNesting
// signature from the inferred typed table
extern "C" NoFitNesting NewNoFitNesting(NoFitContext) {
    lcns::dll::exports::notReversed(155u);
    return 0;
}

// ordinal 320/321  rva 0x0A9D0  240 bytes
// signature from the inferred typed table
extern "C" void NoFitAddNestedPart(NoFitNesting, Part, int, double, double, double) {
    lcns::dll::exports::notReversed(156u);
}

// ordinal 322/323  rva 0x09500  70 bytes
// signature from the inferred typed table
extern "C" void DeleteNoFitNesting(NoFitNesting) {
    lcns::dll::exports::notReversed(157u);
}

// ordinal 324/325  rva 0x0A620  934 bytes
// signature from the inferred typed table
extern "C" NoFitGeometry GetNoFitPlacementMap(NoFitContext, int, int) {
    lcns::dll::exports::notReversed(158u);
    return 0;
}

// ordinal 326/327  rva 0x09550  573 bytes
// signature from the inferred typed table
extern "C" int NoFitGenerateSvgNesting(NoFitNesting, const char*) {
    lcns::dll::exports::notReversed(159u);
    return 0;
}

// ordinal 328/329  rva 0x09790  403 bytes
// signature from the inferred typed table
extern "C" int NoFitGenerateSvgGeometry(NoFitGeometry, const char*) {
    lcns::dll::exports::notReversed(160u);
    return 0;
}

// ordinal 330/331  rva 0x0DDF0  36 bytes
// signature from the inferred typed table
extern "C" void SetPartialShearMode(Order, int) {
    lcns::dll::exports::notReversed(161u);
}

// ordinal 332/333  rva 0x0B750  384 bytes  cns.cpp
// signature from the inferred typed table
extern "C" int GetNestingBoundingBox(Order, double*, double*, double*, double*) {
    lcns::dll::exports::notReversed(162u);
    return 0;
}

// ordinal 334/335  rva 0x0C610  43 bytes
// signature synthesized from the register analysis: 1 integer register(s), 0 xmm; the
// interleaving of the two classes is not recoverable, so treat the parameter list as opaque
extern "C" std::intptr_t ForcePartInsideHole(std::intptr_t) {
    lcns::dll::exports::notReversed(163u);
    return 0;
}

// ordinal 336/337  rva 0x10470  42 bytes
// signature from the inferred typed table
extern "C" void SetReorganizeBiggestPartNearOrigin(Order, int) {
    lcns::dll::exports::notReversed(164u);
}

// ordinal 338/339  rva 0x104A0  42 bytes
// signature from the inferred typed table
extern "C" void SetReorganizeLongestPartNearOrigin(Order, int) {
    lcns::dll::exports::notReversed(165u);
}

// ordinal 340/341  rva 0x09930  443 bytes
// signature from the inferred typed table
extern "C" void NoFitSetMaximumComplexity(NoFitContext, int) {
    lcns::dll::exports::notReversed(166u);
}

// ordinal 342/343  rva 0x0E1F0  111 bytes
// signature from the inferred typed table
extern "C" int UnLockLaunchingOrderOxy(Order, const char*, const char*) {
    lcns::dll::exports::notReversed(167u);
    return 0;
}

}  // namespace dll
}  // namespace lcns

namespace lcns {
namespace dll {
namespace exports {
namespace {

// The addresses of the definitions above, so a test can call every entry point through the ABI without
// knowing its type. The definitions are argument-independent, which is what makes that sound.
using RawFn = void (*)();
RawFn kAddresses[168];
struct AddressBinder {
    AddressBinder() {
        kAddresses[0u] = reinterpret_cast<RawFn>(&AddPolygonHoleToPart);
        kAddresses[1u] = reinterpret_cast<RawFn>(&AddPolygonPart);
        kAddresses[2u] = reinterpret_cast<RawFn>(&AddSheet);
        kAddresses[3u] = reinterpret_cast<RawFn>(&DeleteLaunchingOrder);
        kAddresses[4u] = reinterpret_cast<RawFn>(&GenerateHtmlLaunchingOrderReport);
        kAddresses[5u] = reinterpret_cast<RawFn>(&GenerateHtmlSolutionReport);
        kAddresses[6u] = reinterpret_cast<RawFn>(&GenerateLaunchingOrderProblem);
        kAddresses[7u] = reinterpret_cast<RawFn>(&GetComputationStatus);
        kAddresses[8u] = reinterpret_cast<RawFn>(&GetMultiplicity);
        kAddresses[9u] = reinterpret_cast<RawFn>(&GetNestedPart);
        kAddresses[10u] = reinterpret_cast<RawFn>(&GetNesting);
        kAddresses[11u] = reinterpret_cast<RawFn>(&GetNumberOfNestedParts);
        kAddresses[12u] = reinterpret_cast<RawFn>(&GetNumberOfNestings);
        kAddresses[13u] = reinterpret_cast<RawFn>(&GetPartUserString);
        kAddresses[14u] = reinterpret_cast<RawFn>(&GetPartWithBadGeometry);
        kAddresses[15u] = reinterpret_cast<RawFn>(&GetSheet);
        kAddresses[16u] = reinterpret_cast<RawFn>(&GetSolution);
        kAddresses[17u] = reinterpret_cast<RawFn>(&LaunchComputation);
        kAddresses[18u] = reinterpret_cast<RawFn>(&NewLaunchingOrder);
        kAddresses[19u] = reinterpret_cast<RawFn>(&SetInterpartGap);
        kAddresses[20u] = reinterpret_cast<RawFn>(&SetPartAuthorizations);
        kAddresses[21u] = reinterpret_cast<RawFn>(&SetPartUserString);
        kAddresses[22u] = reinterpret_cast<RawFn>(&SetSheetGaps);
        kAddresses[23u] = reinterpret_cast<RawFn>(&WaitComputationTermination);
        kAddresses[24u] = reinterpret_cast<RawFn>(&WaitNextSolution);
        kAddresses[25u] = reinterpret_cast<RawFn>(&LaunchLocalComputation);
        kAddresses[26u] = reinterpret_cast<RawFn>(&CancelComputation);
        kAddresses[27u] = reinterpret_cast<RawFn>(&GetPartUserStringEx);
        kAddresses[28u] = reinterpret_cast<RawFn>(&SetSheetUserString);
        kAddresses[29u] = reinterpret_cast<RawFn>(&GetSheetUserString);
        kAddresses[30u] = reinterpret_cast<RawFn>(&GetSheetUserStringEx);
        kAddresses[31u] = reinterpret_cast<RawFn>(&SetExtraParameters);
        kAddresses[32u] = reinterpret_cast<RawFn>(&SetSheetPriority);
        kAddresses[33u] = reinterpret_cast<RawFn>(&AddNonRectangularPolygonSheet);
        kAddresses[34u] = reinterpret_cast<RawFn>(&AddPolygonDefectToSheet);
        kAddresses[35u] = reinterpret_cast<RawFn>(&SetLocalEngine);
        kAddresses[36u] = reinterpret_cast<RawFn>(&UnLockLaunchingOrder);
        kAddresses[37u] = reinterpret_cast<RawFn>(&SetObjective);
        kAddresses[38u] = reinterpret_cast<RawFn>(&SetDefectGap);
        kAddresses[39u] = reinterpret_cast<RawFn>(&SetLocalMaximumThreads);
        kAddresses[40u] = reinterpret_cast<RawFn>(&SetLocalMaximumIterations);
        kAddresses[41u] = reinterpret_cast<RawFn>(&SetOrigin);
        kAddresses[42u] = reinterpret_cast<RawFn>(&GetBuildVersion);
        kAddresses[43u] = reinterpret_cast<RawFn>(&GetBuildDate);
        kAddresses[44u] = reinterpret_cast<RawFn>(&GetMajorVersion);
        kAddresses[45u] = reinterpret_cast<RawFn>(&AddPartSpecificAuthorizations);
        kAddresses[46u] = reinterpret_cast<RawFn>(&GetLength);
        kAddresses[47u] = reinterpret_cast<RawFn>(&SetSheetGrainDirection);
        kAddresses[48u] = reinterpret_cast<RawFn>(&GetHeight);
        kAddresses[49u] = reinterpret_cast<RawFn>(&AddExternalPolygonBoundaryToSheet);
        kAddresses[50u] = reinterpret_cast<RawFn>(&AddExternalPolygonBoundaryToPart);
        kAddresses[51u] = reinterpret_cast<RawFn>(&AddPart);
        kAddresses[52u] = reinterpret_cast<RawFn>(&AddHoleToPart);
        kAddresses[53u] = reinterpret_cast<RawFn>(&AddExternalBoundaryToPart);
        kAddresses[54u] = reinterpret_cast<RawFn>(&AddNonRectangularSheet);
        kAddresses[55u] = reinterpret_cast<RawFn>(&AddDefectToSheet);
        kAddresses[56u] = reinterpret_cast<RawFn>(&AddExternalBoundaryToSheet);
        kAddresses[57u] = reinterpret_cast<RawFn>(&TerminateComputation);
        kAddresses[58u] = reinterpret_cast<RawFn>(&AddOpenCuttingPathToPart);
        kAddresses[59u] = reinterpret_cast<RawFn>(&SetPartPriority);
        kAddresses[60u] = reinterpret_cast<RawFn>(&CNS_SetMultiplicityPreference);
        kAddresses[61u] = reinterpret_cast<RawFn>(&AddCircularPart);
        kAddresses[62u] = reinterpret_cast<RawFn>(&AddCircularHoleToPart);
        kAddresses[63u] = reinterpret_cast<RawFn>(&AddRectanglePart);
        kAddresses[64u] = reinterpret_cast<RawFn>(&AddRectangularHoleToPart);
        kAddresses[65u] = reinterpret_cast<RawFn>(&AddOptionalQuantityToPart);
        kAddresses[66u] = reinterpret_cast<RawFn>(&SetAutomaticStop);
        kAddresses[67u] = reinterpret_cast<RawFn>(&SetOffcutEvaluation);
        kAddresses[68u] = reinterpret_cast<RawFn>(&SetFillLastNestingStrategy);
        kAddresses[69u] = reinterpret_cast<RawFn>(&SetShearMode);
        kAddresses[70u] = reinterpret_cast<RawFn>(&SetCommonCutMode);
        kAddresses[71u] = reinterpret_cast<RawFn>(&SetCommonCutSafetyPreference);
        kAddresses[72u] = reinterpret_cast<RawFn>(&SetCommonCutAuthorizations);
        kAddresses[73u] = reinterpret_cast<RawFn>(&SetCommonCutCuttingPreference);
        kAddresses[74u] = reinterpret_cast<RawFn>(&SetCommonCutObjective);
        kAddresses[75u] = reinterpret_cast<RawFn>(&GetNumberOfCommonCuts);
        kAddresses[76u] = reinterpret_cast<RawFn>(&GetCommonCut);
        kAddresses[77u] = reinterpret_cast<RawFn>(&UnLockLaunchingOrderSntl);
        kAddresses[78u] = reinterpret_cast<RawFn>(&LaunchLimitedLocalComputation);
        kAddresses[79u] = reinterpret_cast<RawFn>(&SetPartCommonCutMode);
        kAddresses[80u] = reinterpret_cast<RawFn>(&GetFillRatio);
        kAddresses[81u] = reinterpret_cast<RawFn>(&GetNestingDimensions);
        kAddresses[82u] = reinterpret_cast<RawFn>(&SetSheetPrice);
        kAddresses[83u] = reinterpret_cast<RawFn>(&SetMultiTorchMode);
        kAddresses[84u] = reinterpret_cast<RawFn>(&SetMultiTorchCuttingPreference);
        kAddresses[85u] = reinterpret_cast<RawFn>(&SetMultiTorchObjective);
        kAddresses[86u] = reinterpret_cast<RawFn>(&SetExtraGapOnPart);
        kAddresses[87u] = reinterpret_cast<RawFn>(&CNS_SetFloatingMode);
        kAddresses[88u] = reinterpret_cast<RawFn>(&GetPartTorchInfos);
        kAddresses[89u] = reinterpret_cast<RawFn>(&SetDetailedMultiTorchObjective);
        kAddresses[90u] = reinterpret_cast<RawFn>(&CNS_SetNoMixPreference);
        kAddresses[91u] = reinterpret_cast<RawFn>(&CNS_SetNoOrientationMixOnPart);
        kAddresses[92u] = reinterpret_cast<RawFn>(&GetNestingFillRatio);
        kAddresses[93u] = reinterpret_cast<RawFn>(&AddPartVariantToPart);
        kAddresses[94u] = reinterpret_cast<RawFn>(&AddHoleToPartVariant);
        kAddresses[95u] = reinterpret_cast<RawFn>(&CNS_AddExternalBoundaryToPartVariant);
        kAddresses[96u] = reinterpret_cast<RawFn>(&CNS_AddOpenCuttingPathToPartVariant);
        kAddresses[97u] = reinterpret_cast<RawFn>(&CNS_SetPartVariantAuthorizations);
        kAddresses[98u] = reinterpret_cast<RawFn>(&CNS_AddPartVariantSpecificAuthorizations);
        kAddresses[99u] = reinterpret_cast<RawFn>(&GetNestedPartPartVariant);
        kAddresses[100u] = reinterpret_cast<RawFn>(&sub_16CB0);
        kAddresses[101u] = reinterpret_cast<RawFn>(&sub_16CF0);
        kAddresses[102u] = reinterpret_cast<RawFn>(&SetShearGap);
        kAddresses[103u] = reinterpret_cast<RawFn>(&SetIncompatibleSheet);
        kAddresses[104u] = reinterpret_cast<RawFn>(&LaunchEstimateLocalComputation);
        kAddresses[105u] = reinterpret_cast<RawFn>(&AddSuggestedPartsGrouping);
        kAddresses[106u] = reinterpret_cast<RawFn>(&AddPartToSuggestedPartsGrouping);
        kAddresses[107u] = reinterpret_cast<RawFn>(&CNS_SetNoSheetMixPreference);
        kAddresses[108u] = reinterpret_cast<RawFn>(&GenerateDxfNesting);
        kAddresses[109u] = reinterpret_cast<RawFn>(&GetPCId);
        kAddresses[110u] = reinterpret_cast<RawFn>(&UnLockLaunchingOrderPCId);
        kAddresses[111u] = reinterpret_cast<RawFn>(&NewNoFitContext);
        kAddresses[112u] = reinterpret_cast<RawFn>(&DeleteNoFitContext);
        kAddresses[113u] = reinterpret_cast<RawFn>(&GetNoFitMap);
        kAddresses[114u] = reinterpret_cast<RawFn>(&DeleteNoFitGeometry);
        kAddresses[115u] = reinterpret_cast<RawFn>(&NoFitGetNumberOfExternalPolygons);
        kAddresses[116u] = reinterpret_cast<RawFn>(&NoFitGetNumberOfInternalHoles);
        kAddresses[117u] = reinterpret_cast<RawFn>(&NoFitGetNumberOfPoints);
        kAddresses[118u] = reinterpret_cast<RawFn>(&NoFitGetPoint);
        kAddresses[119u] = reinterpret_cast<RawFn>(&SetMarkMode);
        kAddresses[120u] = reinterpret_cast<RawFn>(&GetNumberOfMarks);
        kAddresses[121u] = reinterpret_cast<RawFn>(&GetMark);
        kAddresses[122u] = reinterpret_cast<RawFn>(&AsyncCancelAllComputationsAndDeleteLaunchingOrder);
        kAddresses[123u] = reinterpret_cast<RawFn>(&AddRotatedPartVariantToPart);
        kAddresses[124u] = reinterpret_cast<RawFn>(&SetRowMode);
        kAddresses[125u] = reinterpret_cast<RawFn>(&SetPipeMode);
        kAddresses[126u] = reinterpret_cast<RawFn>(&AddCircularExternalBoundaryToPart);
        kAddresses[127u] = reinterpret_cast<RawFn>(&AddRectangularExternalBoundaryToPart);
        kAddresses[128u] = reinterpret_cast<RawFn>(&GetNumberOfRows);
        kAddresses[129u] = reinterpret_cast<RawFn>(&GetRow);
        kAddresses[130u] = reinterpret_cast<RawFn>(&SetLocalEngineThreads);
        kAddresses[131u] = reinterpret_cast<RawFn>(&sub_0AFE0);
        kAddresses[132u] = reinterpret_cast<RawFn>(&SetLeatherMode);
        kAddresses[133u] = reinterpret_cast<RawFn>(&AddLeatherQualityZoneInPart);
        kAddresses[134u] = reinterpret_cast<RawFn>(&AddLeatherQualityZoneInSheet);
        kAddresses[135u] = reinterpret_cast<RawFn>(&CreateRestrictedZoneConstraint);
        kAddresses[136u] = reinterpret_cast<RawFn>(&CNS_SetZoneRestrictedPart);
        kAddresses[137u] = reinterpret_cast<RawFn>(&sub_1A7D0);
        kAddresses[138u] = reinterpret_cast<RawFn>(&CNS_SheetAddRestrictedZone);
        kAddresses[139u] = reinterpret_cast<RawFn>(&sub_0B000);
        kAddresses[140u] = reinterpret_cast<RawFn>(&sub_0AFF0);
        kAddresses[141u] = reinterpret_cast<RawFn>(&AddToolPathToPart);
        kAddresses[142u] = reinterpret_cast<RawFn>(&AddLeatherQualityZoneInPart_o292);
        kAddresses[143u] = reinterpret_cast<RawFn>(&AddInflatedToolPathToPart);
        kAddresses[144u] = reinterpret_cast<RawFn>(&AddHoleInToolPath);
        kAddresses[145u] = reinterpret_cast<RawFn>(&SetSpecificSheetOrigin);
        kAddresses[146u] = reinterpret_cast<RawFn>(&SetSpecificSheetObjective);
        kAddresses[147u] = reinterpret_cast<RawFn>(&CNS_ForcePartOnBottomBorder);
        kAddresses[148u] = reinterpret_cast<RawFn>(&SetShearRepulseFromBorders);
        kAddresses[149u] = reinterpret_cast<RawFn>(&CNS_AddDefectFromNestedPart);
        kAddresses[150u] = reinterpret_cast<RawFn>(&CNS_CreateAssemblyGroup);
        kAddresses[151u] = reinterpret_cast<RawFn>(&CNS_AddAssemblyGroupPart);
        kAddresses[152u] = reinterpret_cast<RawFn>(&CNS_SetOriginPackingMode);
        kAddresses[153u] = reinterpret_cast<RawFn>(&CNS_AddOpenToolPathToPart);
        kAddresses[154u] = reinterpret_cast<RawFn>(&CNS_SetEvaluateIntermediateNestingsAsLast);
        kAddresses[155u] = reinterpret_cast<RawFn>(&NewNoFitNesting);
        kAddresses[156u] = reinterpret_cast<RawFn>(&NoFitAddNestedPart);
        kAddresses[157u] = reinterpret_cast<RawFn>(&DeleteNoFitNesting);
        kAddresses[158u] = reinterpret_cast<RawFn>(&GetNoFitPlacementMap);
        kAddresses[159u] = reinterpret_cast<RawFn>(&NoFitGenerateSvgNesting);
        kAddresses[160u] = reinterpret_cast<RawFn>(&NoFitGenerateSvgGeometry);
        kAddresses[161u] = reinterpret_cast<RawFn>(&SetPartialShearMode);
        kAddresses[162u] = reinterpret_cast<RawFn>(&GetNestingBoundingBox);
        kAddresses[163u] = reinterpret_cast<RawFn>(&ForcePartInsideHole);
        kAddresses[164u] = reinterpret_cast<RawFn>(&SetReorganizeBiggestPartNearOrigin);
        kAddresses[165u] = reinterpret_cast<RawFn>(&SetReorganizeLongestPartNearOrigin);
        kAddresses[166u] = reinterpret_cast<RawFn>(&NoFitSetMaximumComplexity);
        kAddresses[167u] = reinterpret_cast<RawFn>(&UnLockLaunchingOrderOxy);
    }
};
AddressBinder kBindAddresses;

}  // namespace

const Entry kEntries[] = {
    {"AddPolygonHoleToPart", 1, 2, 0x16420u, 490u, Status::NotReversed, "// AddPolygonHoleToPart"},
    {"AddPolygonPart", 3, 4, 0x162B0u, 353u, Status::NotReversed, "// AddPolygonPart"},
    {"AddSheet", 5, 6, 0x15BF0u, 1717u, Status::NotReversed, ""},
    {"DeleteLaunchingOrder", 7, 8, 0x118F0u, 3660u, Status::NotReversed, "*** ERROR unterminated/cancelled computation ***"},
    {"GenerateHtmlLaunchingOrderReport", 9, 10, 0x0B1D0u, 370u, Status::NotReversed, "<h1> Problem contains invalid parts. </h1>"},
    {"GenerateHtmlSolutionReport", 11, 12, 0x0B350u, 247u, Status::NotReversed, ""},
    {"GenerateLaunchingOrderProblem", 13, 14, 0x0B8D0u, 378u, Status::NotReversed, "source_version"},
    {"GetComputationStatus", 15, 16, 0x107E0u, 155u, Status::NotReversed, "// GetComputationStatus"},
    {"GetMultiplicity", 17, 18, 0x0B100u, 34u, Status::NotReversed, ""},
    {"GetNestedPart", 19, 20, 0x0D460u, 688u, Status::NotReversed, "cns.cpp"},
    {"GetNesting", 21, 22, 0x10F30u, 490u, Status::NotReversed, "cns.cpp"},
    {"GetNumberOfNestedParts", 23, 24, 0x0B190u, 63u, Status::NotReversed, ""},
    {"GetNumberOfNestings", 25, 26, 0x0B0C0u, 52u, Status::NotReversed, ""},
    {"GetPartUserString", 27, 28, 0x0C5E0u, 36u, Status::NotReversed, ""},
    {"GetPartWithBadGeometry", 29, 30, 0x0B510u, 43u, Status::NotReversed, ""},
    {"GetSheet", 31, 32, 0x0B600u, 332u, Status::NotReversed, "number <= order->sheets.size()"},
    {"GetSolution", 33, 34, 0x0B0A0u, 29u, Status::NotReversed, ""},
    {"LaunchComputation", 35, 36, 0x06100u, 3894u, Status::NotReversed, "c:/Temp/cns.pb.json"},
    {"NewLaunchingOrder", 37, 38, 0x14620u, 1081u, Status::NotReversed, ""},
    {"SetInterpartGap", 39, 40, 0x0CF20u, 303u, Status::NotReversed, "cns.cpp"},
    {"SetPartAuthorizations", 41, 42, 0x0C1A0u, 241u, Status::NotReversed, ""},
    {"SetPartUserString", 43, 44, 0x0C420u, 446u, Status::NotReversed, ""},
    {"SetSheetGaps", 45, 46, 0x0CCB0u, 527u, Status::NotReversed, ""},
    {"WaitComputationTermination", 47, 48, 0x104D0u, 370u, Status::NotReversed, "// WaitComputationTermination"},
    {"WaitNextSolution", 49, 50, 0x10650u, 386u, Status::NotReversed, "c:/Temp/computation_solution.html"},
    {"LaunchLocalComputation", 51, 52, 0x02AB0u, 2134u, Status::NotReversed, "cns_force_cloud"},
    {"CancelComputation", 53, 54, 0x10880u, 155u, Status::NotReversed, "CancelComputation "},
    {"GetPartUserStringEx", 55, 56, 0x0B020u, 52u, Status::NotReversed, ""},
    {"SetSheetUserString", 57, 58, 0x0C670u, 446u, Status::NotReversed, ""},
    {"GetSheetUserString", 59, 60, 0x0C830u, 353u, Status::NotReversed, ""},
    {"GetSheetUserStringEx", 61, 62, 0x0B060u, 52u, Status::NotReversed, ""},
    {"SetExtraParameters", 65, 66, 0x11120u, 868u, Status::NotReversed, ""},
    {"SetSheetPriority", 67, 68, 0x13C90u, 411u, Status::NotReversed, ""},
    {"AddNonRectangularPolygonSheet", 69, 70, 0x16B20u, 353u, Status::NotReversed, "// AddNonRectangularPolygonSheet"},
    {"AddPolygonDefectToSheet", 71, 72, 0x16970u, 426u, Status::NotReversed, "// AddPolygonDefectToSheet"},
    {"SetLocalEngine", 73, 74, 0x0D370u, 61u, Status::NotReversed, ""},
    {"UnLockLaunchingOrder", 76, 77, 0x0D430u, 36u, Status::NotReversed, ""},
    {"SetObjective", 78, 79, 0x0CEC0u, 45u, Status::NotReversed, ""},
    {"SetDefectGap", 80, 81, 0x109C0u, 388u, Status::NotReversed, ""},
    {"SetLocalMaximumThreads", 82, 83, 0x0D3B0u, 68u, Status::NotReversed, ""},
    {"SetLocalMaximumIterations", 84, 85, 0x0D400u, 36u, Status::NotReversed, ""},
    {"SetOrigin", 86, 87, 0x0D050u, 334u, Status::NotReversed, ""},
    {"GetBuildVersion", 88, 89, 0x0B490u, 31u, Status::NotReversed, ""},
    {"GetBuildDate", 90, 91, 0x0B470u, 31u, Status::NotReversed, ""},
    {"GetMajorVersion", 92, 93, 0x0B450u, 31u, Status::NotReversed, ""},
    {"AddPartSpecificAuthorizations", 94, 95, 0x10CE0u, 584u, Status::NotReversed, ""},
    {"GetLength", 96, 97, 0x0B130u, 36u, Status::NotReversed, ""},
    {"SetSheetGrainDirection", 98, 99, 0x0C9A0u, 372u, Status::NotReversed, ""},
    {"GetHeight", 100, 101, 0x0B160u, 36u, Status::NotReversed, ""},
    {"AddExternalPolygonBoundaryToSheet", 102, 103, 0x16610u, 419u, Status::NotReversed, "// AddExternalPolygonBoundaryToSheet"},
    {"AddExternalPolygonBoundaryToPart", 104, 105, 0x167C0u, 426u, Status::NotReversed, "// AddExternalPolygonBoundaryToPart"},
    {"AddPart", 110, 111, 0x14D10u, 1891u, Status::NotReversed, ""},
    {"AddHoleToPart", 112, 113, 0x132E0u, 176u, Status::NotReversed, ""},
    {"AddExternalBoundaryToPart", 114, 115, 0x13390u, 124u, Status::NotReversed, ""},
    {"AddNonRectangularSheet", 116, 117, 0x157A0u, 1098u, Status::NotReversed, ""},
    {"AddDefectToSheet", 118, 119, 0x14190u, 124u, Status::NotReversed, ""},
    {"AddExternalBoundaryToSheet", 120, 121, 0x14210u, 117u, Status::NotReversed, ""},
    {"TerminateComputation", 122, 123, 0x10920u, 155u, Status::NotReversed, "TerminateComputation "},
    {"AddOpenCuttingPathToPart", 124, 125, 0x14A60u, 678u, Status::NotReversed, ""},
    {"SetPartPriority", 126, 127, 0x0C2A0u, 382u, Status::NotReversed, ""},
    {"CNS_SetMultiplicityPreference", 128, 129, 0x0D1A0u, 353u, Status::NotReversed, ""},
    {"AddCircularPart", 130, 131, 0x15480u, 404u, Status::NotReversed, "// AddCircularPart"},
    {"AddCircularHoleToPart", 132, 133, 0x13800u, 581u, Status::NotReversed, "// AddCircularHoleToPart"},
    {"AddRectanglePart", 134, 135, 0x15620u, 374u, Status::NotReversed, "// AddRectanglePart"},
    {"AddRectangularHoleToPart", 136, 137, 0x13A50u, 569u, Status::NotReversed, "// AddRectangularHoleToPart"},
    {"AddOptionalQuantityToPart", 138, 139, 0x14290u, 440u, Status::NotReversed, ""},
    {"SetAutomaticStop", 140, 141, 0x0E010u, 353u, Status::NotReversed, ""},
    {"SetOffcutEvaluation", 142, 143, 0x0E2D0u, 399u, Status::NotReversed, ""},
    {"SetFillLastNestingStrategy", 144, 145, 0x0DD90u, 36u, Status::NotReversed, ""},
    {"SetShearMode", 146, 147, 0x0DDC0u, 33u, Status::NotReversed, ""},
    {"SetCommonCutMode", 148, 149, 0x0E460u, 404u, Status::NotReversed, ""},
    {"SetCommonCutSafetyPreference", 150, 151, 0x0E940u, 354u, Status::NotReversed, ""},
    {"SetCommonCutAuthorizations", 152, 153, 0x0EAB0u, 468u, Status::NotReversed, ""},
    {"SetCommonCutCuttingPreference", 154, 155, 0x0EC90u, 340u, Status::NotReversed, ""},
    {"SetCommonCutObjective", 156, 157, 0x0EDF0u, 337u, Status::NotReversed, ""},
    {"GetNumberOfCommonCuts", 158, 159, 0x0D710u, 346u, Status::NotReversed, "cns.cpp"},
    {"GetCommonCut", 160, 161, 0x0BA50u, 825u, Status::NotReversed, "cns.cpp"},
    {"UnLockLaunchingOrderSntl", 162, 163, 0x0E180u, 111u, Status::NotReversed, ""},
    {"LaunchLimitedLocalComputation", 164, 165, 0x03310u, 66u, Status::NotReversed, ""},
    {"SetPartCommonCutMode", 166, 167, 0x0DE50u, 36u, Status::NotReversed, ""},
    {"GetFillRatio", 168, 169, 0x0B4B0u, 34u, Status::NotReversed, ""},
    {"GetNestingDimensions", 170, 171, 0x0BD90u, 470u, Status::NotReversed, "cns.cpp"},
    {"SetSheetPrice", 172, 173, 0x0CB20u, 388u, Status::NotReversed, ""},
    {"SetMultiTorchMode", 174, 175, 0x0EF50u, 479u, Status::NotReversed, ""},
    {"SetMultiTorchCuttingPreference", 176, 177, 0x0F130u, 388u, Status::NotReversed, ""},
    {"SetMultiTorchObjective", 178, 179, 0x0F2C0u, 633u, Status::NotReversed, ""},
    {"SetExtraGapOnPart", 180, 181, 0x14450u, 449u, Status::NotReversed, ""},
    {"CNS_SetFloatingMode", 182, 183, 0x0DD30u, 36u, Status::NotReversed, ""},
    {"GetPartTorchInfos", 184, 185, 0x0D870u, 826u, Status::NotReversed, "cns.cpp"},
    {"SetDetailedMultiTorchObjective", 186, 187, 0x0F540u, 629u, Status::NotReversed, ""},
    {"CNS_SetNoMixPreference", 188, 189, 0x0D310u, 33u, Status::NotReversed, ""},
    {"CNS_SetNoOrientationMixOnPart", 190, 191, 0x0DBB0u, 382u, Status::NotReversed, ""},
    {"GetNestingFillRatio", 192, 193, 0x0B4E0u, 38u, Status::NotReversed, ""},
    {"AddPartVariantToPart", 194, 195, 0x18100u, 1955u, Status::NotReversed, ""},
    {"AddHoleToPartVariant", 196, 197, 0x16D00u, 49u, Status::NotReversed, "// AddHoleToPartVariant"},
    {"CNS_AddExternalBoundaryToPartVariant", 198, 199, 0x16D40u, 49u, Status::NotReversed, "// CNS_AddExternalBoundaryToPartVariant"},
    {"CNS_AddOpenCuttingPathToPartVariant", 200, 201, 0x16D80u, 96u, Status::NotReversed, "// CNS_AddOpenCuttingPathToPartVariant"},
    {"CNS_SetPartVariantAuthorizations", 202, 203, 0x16DE0u, 61u, Status::NotReversed, "// CNS_SetPartVariantAuthorizations"},
    {"CNS_AddPartVariantSpecificAuthorizations", 204, 205, 0x16E20u, 63u, Status::NotReversed, "// CNS_AddPartVariantSpecificAuthorizations"},
    {"GetNestedPartPartVariant", 206, 207, 0x16E60u, 1727u, Status::NotReversed, ""},
    {"sub_16CB0", 208, 209, 0x16CB0u, 57u, Status::NotReversed, ""},
    {"sub_16CF0", 210, 211, 0x16CF0u, 8u, Status::NotReversed, ""},
    {"SetShearGap", 212, 213, 0x0CEF0u, 45u, Status::NotReversed, ""},
    {"SetIncompatibleSheet", 214, 215, 0x11490u, 423u, Status::NotReversed, ""},
    {"LaunchEstimateLocalComputation", 216, 217, 0x03360u, 52u, Status::NotReversed, "// LaunchEstimateLocalComputation"},
    {"AddSuggestedPartsGrouping", 218, 219, 0x11640u, 483u, Status::NotReversed, "cns.cpp"},
    {"AddPartToSuggestedPartsGrouping", 220, 221, 0x0F7C0u, 1072u, Status::NotReversed, "cns.cpp"},
    {"CNS_SetNoSheetMixPreference", 222, 223, 0x0D340u, 33u, Status::NotReversed, ""},
    {"GenerateDxfNesting", 224, 225, 0x0BF70u, 148u, Status::NotReversed, ""},
    {"GetPCId", 226, 227, 0x0C010u, 386u, Status::NotReversed, ""},
    {"UnLockLaunchingOrderPCId", 228, 229, 0x0E260u, 111u, Status::NotReversed, ""},
    {"NewNoFitContext", 230, 231, 0x09AF0u, 452u, Status::NotReversed, "// NewNoFitContext"},
    {"DeleteNoFitContext", 232, 233, 0x09CC0u, 568u, Status::NotReversed, ""},
    {"GetNoFitMap", 234, 235, 0x08AC0u, 939u, Status::NotReversed, "//GetNoFitMap"},
    {"DeleteNoFitGeometry", 236, 237, 0x08A10u, 171u, Status::NotReversed, ""},
    {"NoFitGetNumberOfExternalPolygons", 238, 239, 0x089D0u, 54u, Status::NotReversed, ""},
    {"NoFitGetNumberOfInternalHoles", 240, 241, 0x08E70u, 335u, Status::NotReversed, "cns_no_fit.cpp"},
    {"NoFitGetNumberOfPoints", 242, 243, 0x08FC0u, 497u, Status::NotReversed, ""},
    {"NoFitGetPoint", 244, 245, 0x091C0u, 366u, Status::NotReversed, "cns_no_fit.cpp"},
    {"SetMarkMode", 246, 247, 0x188D0u, 529u, Status::NotReversed, ""},
    {"GetNumberOfMarks", 248, 249, 0x18AF0u, 889u, Status::NotReversed, ""},
    {"GetMark", 250, 251, 0x18E70u, 1312u, Status::NotReversed, ""},
    {"AsyncCancelAllComputationsAndDeleteLaunchingOrder", 252, 253, 0x0B540u, 177u, Status::NotReversed, ""},
    {"AddRotatedPartVariantToPart", 254, 255, 0x17520u, 3027u, Status::NotReversed, ""},
    {"SetRowMode", 256, 257, 0x0FBF0u, 244u, Status::NotReversed, ""},
    {"SetPipeMode", 258, 259, 0x0FCF0u, 568u, Status::NotReversed, ""},
    {"AddCircularExternalBoundaryToPart", 260, 261, 0x13410u, 512u, Status::NotReversed, "// AddCircularExternalBoundaryToPart"},
    {"AddRectangularExternalBoundaryToPart", 262, 263, 0x13610u, 486u, Status::NotReversed, "// AddRectangularExternalBoundaryToPart"},
    {"GetNumberOfRows", 264, 265, 0x0FF30u, 271u, Status::NotReversed, ""},
    {"GetRow", 266, 267, 0x10040u, 384u, Status::NotReversed, "cns.cpp"},
    {"SetLocalEngineThreads", 268, 269, 0x0DE80u, 388u, Status::NotReversed, ""},
    {"sub_0AFE0", 270, 271, 0x0AFE0u, 13u, Status::NotReversed, ""},
    {"SetLeatherMode", 272, 273, 0x19C40u, 411u, Status::NotReversed, ""},
    {"AddLeatherQualityZoneInPart", 274, 275, 0x19DE0u, 350u, Status::NotReversed, ""},
    {"AddLeatherQualityZoneInSheet", 276, 277, 0x1A0A0u, 331u, Status::NotReversed, ""},
    {"CreateRestrictedZoneConstraint", 278, 279, 0x1AA90u, 944u, Status::NotReversed, ""},
    {"CNS_SetZoneRestrictedPart", 280, 281, 0x1AE40u, 507u, Status::NotReversed, ""},
    {"sub_1A7D0", 282, 283, 0x1A7D0u, 286u, Status::NotReversed, ""},
    {"CNS_SheetAddRestrictedZone", 284, 285, 0x1A210u, 1468u, Status::NotReversed, ""},
    {"sub_0B000", 286, 287, 0x0B000u, 18u, Status::NotReversed, ""},
    {"sub_0AFF0", 288, 289, 0x0AFF0u, 10u, Status::NotReversed, ""},
    {"AddToolPathToPart", 290, 291, 0x101C0u, 127u, Status::NotReversed, ""},
    {"AddLeatherQualityZoneInPart", 292, 293, 0x19F40u, 342u, Status::NotReversed, " [label shared with the entry at ordinal 274]"},
    {"AddInflatedToolPathToPart", 294, 295, 0x12C60u, 169u, Status::NotReversed, ""},
    {"AddHoleInToolPath", 296, 297, 0x10240u, 124u, Status::NotReversed, ""},
    {"SetSpecificSheetOrigin", 298, 299, 0x13E30u, 417u, Status::NotReversed, ""},
    {"SetSpecificSheetObjective", 300, 301, 0x13FE0u, 417u, Status::NotReversed, ""},
    {"CNS_ForcePartOnBottomBorder", 302, 303, 0x1A8F0u, 411u, Status::NotReversed, ""},
    {"SetShearRepulseFromBorders", 304, 305, 0x0DE20u, 33u, Status::NotReversed, ""},
    {"CNS_AddDefectFromNestedPart", 306, 307, 0x12F40u, 894u, Status::NotReversed, ""},
    {"CNS_CreateAssemblyGroup", 308, 309, 0x10B50u, 395u, Status::NotReversed, ""},
    {"CNS_AddAssemblyGroupPart", 310, 311, 0x11830u, 180u, Status::NotReversed, ""},
    {"CNS_SetOriginPackingMode", 312, 313, 0x0DD60u, 36u, Status::NotReversed, ""},
    {"CNS_AddOpenToolPathToPart", 314, 315, 0x12D10u, 552u, Status::NotReversed, ""},
    {"CNS_SetEvaluateIntermediateNestingsAsLast", 316, 317, 0x10440u, 42u, Status::NotReversed, ""},
    {"NewNoFitNesting", 318, 319, 0x09330u, 449u, Status::NotReversed, "// NewNoFitNesting"},
    {"NoFitAddNestedPart", 320, 321, 0x0A9D0u, 240u, Status::NotReversed, ""},
    {"DeleteNoFitNesting", 322, 323, 0x09500u, 70u, Status::NotReversed, ""},
    {"GetNoFitPlacementMap", 324, 325, 0x0A620u, 934u, Status::NotReversed, ""},
    {"NoFitGenerateSvgNesting", 326, 327, 0x09550u, 573u, Status::NotReversed, ""},
    {"NoFitGenerateSvgGeometry", 328, 329, 0x09790u, 403u, Status::NotReversed, ""},
    {"SetPartialShearMode", 330, 331, 0x0DDF0u, 36u, Status::NotReversed, ""},
    {"GetNestingBoundingBox", 332, 333, 0x0B750u, 384u, Status::NotReversed, "cns.cpp"},
    {"ForcePartInsideHole", 334, 335, 0x0C610u, 43u, Status::NotReversed, ""},
    {"SetReorganizeBiggestPartNearOrigin", 336, 337, 0x10470u, 42u, Status::NotReversed, ""},
    {"SetReorganizeLongestPartNearOrigin", 338, 339, 0x104A0u, 42u, Status::NotReversed, ""},
    {"NoFitSetMaximumComplexity", 340, 341, 0x09930u, 443u, Status::NotReversed, ""},
    {"UnLockLaunchingOrderOxy", 342, 343, 0x0E1F0u, 111u, Status::NotReversed, ""},
};
const std::size_t kEntryCount = sizeof(kEntries) / sizeof(kEntries[0]);

const Entry* entries() { return kEntries; }
std::size_t count() { return kEntryCount; }
RawFn addressOf(std::size_t index) { return index < kEntryCount ? kAddresses[index] : nullptr; }

}  // namespace exports
}  // namespace dll
}  // namespace lcns

