// generated by re/g_embed.py -- do not edit by hand.
//
// Addresses of the executable copies in gen_orig.S, in the registry's callable order. Only this translation
// unit references the assembly symbols, so a toolchain without ASM support can drop it and still link.
#include "lcns/embedded.hpp"

// Each symbol is declared as a C function with no parameters: that is what gives &symbol the type RawFn.
extern "C" {
void lcns_orig_51d2f0();
void lcns_orig_4f8370();
void lcns_orig_4f8380();
void lcns_orig_4ddd10();
void lcns_orig_16c270();
void lcns_orig_24b440();
void lcns_orig_5cfd80();
void lcns_orig_5cfdc0();
void lcns_orig_5cea80();
void lcns_orig_5cf6b0();
void lcns_orig_5ce970();
void lcns_orig_5ce7b0();
void lcns_orig_5ced50();
void lcns_orig_55e190();
void lcns_orig_50fd40();
void lcns_orig_5c8a10();
}

namespace lcns {
namespace embedded {

#if defined(LCNS_HAS_EMBEDDED_ASM)
const RawFn kOrigTable[] = {
    &lcns_orig_51d2f0,  // 0x51d2f0  pointer getter: returns [rcx+0x60]
    &lcns_orig_4f8370,  // 0x4f8370  double accessor: returns [rcx+0x28]
    &lcns_orig_4f8380,  // 0x4f8380  double accessor: returns [rcx+0x30]
    &lcns_orig_4ddd10,  // 0x4ddd10  returns the address of the field at +0x48
    &lcns_orig_16c270,  // 0x16c270  packed double addition of two 2D points (addpd)
    &lcns_orig_24b440,  // 0x24b440  two-dimensional cross product / orientation determinant
    &lcns_orig_5cfd80,  // 0x5cfd80  in-place 2x3 affine transform of one point
    &lcns_orig_5cfdc0,  // 0x5cfdc0  in-place 2x3 affine transform of both points of a segment
    &lcns_orig_5cea80,  // 0x5cea80  affine transform applied to a source record, functional form
    &lcns_orig_5cf6b0,  // 0x5cf6b0  affine transform, out of place
    &lcns_orig_5ce970,  // 0x5ce970  composition of two 2x3 affine transforms
    &lcns_orig_5ce7b0,  // 0x5ce7b0  builds a translation matrix (identity basis + point)
    &lcns_orig_5ced50,  // 0x5ced50  inverse of a 2x3 affine matrix
    &lcns_orig_55e190,  // 0x55e190  segment length pair, min and max, with a square-root guard
    &lcns_orig_50fd40,  // 0x50fd40  accumulator over a range of 312-byte elements
    &lcns_orig_5c8a10,  // 0x5c8a10  the box accumulator it calls: init-or-extend a min/max box with one pair (flag at +0x00, then minX +0x08, minY +0x10, maxX +0x18, maxY +0x20); the flag means UNINITIALISED when non-zero, which is why the caller sets it to 1 before the loop and the first call clears it
};
const std::size_t kOrigTableCount = sizeof(kOrigTable) / sizeof(kOrigTable[0]);
#else
// No assembler: the bytes are still embedded as data, but nothing can be executed from them.
const RawFn kOrigTable[] = {nullptr};
const std::size_t kOrigTableCount = 0;
#endif

}  // namespace embedded
}  // namespace lcns
