// lcns/include/lcns/class_constructors.hpp -- every class's constructor and the fields it writes.
//
// GENERATED by re/g_gen_class_ctors.py from re/all_class_fields.json, which re/g_all_class_fields.py produced by joining
// re/g_find_ctors.py (a constructor references its vtable's slot-0 ADDRESS, which is vtable_rva+0x10) to re/g_class_fields.py (a field's
// position is a store through a register the function has been shown to hold the object in, before that register is reassigned).
//
// 93 classes have a constructor candidate; 84 of them write at least one field. **A class with a constructor and no field
// writes is a real shape rather than a failure**: its constructor installs the vtable and nothing else, which is what a class with only
// virtual methods and no state looks like.
//
// THE FIELD COUNT IS A COUNT OF DISTINCT OFFSETS, so a class that writes 0x30 twice -- once zeroed and once from a double, as
// Multi::NestingNester does -- counts once. It is the number of POSITIONS the constructor names, not the number of stores.
#pragma once

#include <cstddef>
#include <cstdint>

namespace lcns {

struct ClassConstructor {
    const char* qualified;
    std::uintptr_t constructor;     // the candidate that writes the most fields
    std::uintptr_t vtable;
    unsigned fields;                // distinct offsets written
    unsigned candidates;            // functions referencing the slot-0 address
    unsigned functionsWriting;      // of those, how many write any field
};

inline const ClassConstructor* classConstructors(std::size_t& count) {
    static const ClassConstructor table[] = {
        {"Tiling::SqueezeMultiTiler", 0x76E440, 0xA3D2D0, 32, 3, 3},
        {"Utils::LogSink", 0x199570, 0xA3BD40, 27, 7, 6},
        {"Tiling::WarpCanceller", 0x4ED480, 0xA3D160, 15, 1, 1},
        {"Multi::SplitNode", 0x99910, 0xA3BB70, 11, 3, 3},
        {"Multi::TerminalNode", 0x99360, 0xA3B570, 10, 3, 3},
        {"Engine::CloudEngine", 0x268A0, 0xA3CED0, 9, 2, 2},
        {"Multi::AdvancedStrategist", 0x2EC50, 0xA3B970, 8, 1, 1},
        {"Multi::LimitedNester", 0x4AAD0, 0xA3B650, 7, 3, 3},
        {"Multi::NestingNester", 0x342E0, 0xA3B690, 7, 3, 3},
        {"Multi::TraceObserver", 0x5F000, 0xA3B700, 6, 1, 1},
        {"Structure::ClusterObserver", 0x553100, 0xA53420, 6, 3, 3},
        {"Utils::Canceller", 0x68AB50, 0xA3BD70, 6, 26, 8},
        {"Multi::CompactNester", 0xB0270, 0xA3B610, 5, 4, 4},
        {"Multi::SupervisorCanceller", 0x30A30, 0xA3BA90, 5, 3, 3},
        {"Tiling::CompositePart", 0x4DBA70, 0xA3D140, 5, 3, 3},
        {"Multi::NoMixSheetSelector", 0xAFD60, 0xA3B9D0, 4, 3, 3},
        {"Pack::KnapsackNester", 0x15D1D0, 0xA3B430, 4, 1, 1},
        {"Pack::RecursiveNester", 0x162280, 0xA3B460, 4, 3, 3},
        {"Tiling::Part", 0x4DB0D0, 0xA3D420, 4, 6, 6},
        {"Tiling::QuantityEvaluator", 0x4E81B0, 0xA3D270, 4, 1, 1},
        {"Engine::NestingEngine", 0x23E70, 0xA3CFA0, 3, 3, 3},
        {"Multi::FilterNester", 0xB3A70, 0xA3B4F0, 3, 3, 3},
        {"Multi::FlipNester", 0x4B570, 0xA3B490, 3, 3, 3},
        {"Pack::BestNester", 0x15E3B0, 0xA3B400, 3, 3, 3},
        {"Tiling::BiModulePattern", 0x7E8520, 0xA3D1C0, 3, 2, 2},
        {"Utils::OstreamSink::<<subst>>", 0x19DA20, 0xA3BBA0, 3, 4, 3},
        {"dbg::file_error", 0x60C160, 0xA3B210, 3, 8, 6},
        {"dbg::symlog", 0x60B4E0, 0xA3B240, 3, 1, 1},
        {"Engine::CompositeObserver", 0x8D4500, 0xA3D060, 2, 2, 1},
        {"Multi::CompactCanceller", 0x68A6E0, 0xA3B870, 2, 3, 3},
        {"Multi::DatabaseNester", 0x5B1F0, 0xA3B740, 2, 3, 3},
        {"Multi::MultiTorchNester", 0x780E0, 0xA3B8A0, 2, 3, 3},
        {"Multi::NoFillNester", 0x7EE50, 0xA3B530, 2, 3, 3},
        {"Multi::PartUpdaterLimiter", 0x695C70, 0xA3BA00, 2, 2, 1},
        {"Multi::RectangleNester", 0x77440, 0xA3B800, 2, 3, 3},
        {"Multi::RowNester", 0x8F210, 0xA3BB30, 2, 3, 3},
        {"Multi::WrapObserver", 0x83DC0, 0xA3B5E0, 2, 3, 3},
        {"Structure::Observer", 0x83DC0, 0xA53550, 2, 1, 1},
        {"Tiling::BasicCandidater", 0x4F3630, 0xA3D190, 2, 1, 1},
        {"Tiling::DensityEvaluator", 0x4E8470, 0xA3D210, 2, 3, 3},
        {"Tiling::ReusableEvaluator", 0x4E8540, 0xA3D2A0, 2, 2, 2},
        {"Utils::BadResponseException", 0x2B660, 0xA3BC80, 2, 6, 3},
        {"Coin::CoinLP", 0x267760, 0xA3B270, 1, 3, 3},
        {"Compact::Compacter::Implementation", 0x266E00, 0xA3D470, 1, 3, 3},
        {"Engine::BestObserver", 0x756B20, 0xA3CF30, 1, 3, 2},
        {"Engine::CompositeEngine", 0x24C40, 0xA3D000, 1, 3, 3},
        {"Engine::DelayedEngine", 0x24B80, 0xA3CF70, 1, 3, 3},
        {"Engine::EquivalentEngine", 0x24AB0, 0xA3D030, 1, 5, 5},
        {"Engine::EquivalentObserver", 0x75E0E0, 0xA3D0A0, 1, 3, 2},
        {"Engine::InfiniteEngine", 0x24FD0, 0xA3CFD0, 1, 3, 3},
        {"Engine::MultiEngine", 0x240D0, 0xA3CF00, 1, 3, 3},
        {"Multi::AllSheetSelector", 0xB00E0, 0xA3B840, 1, 1, 1},
        {"Multi::LargestSheetSelector", 0xB0000, 0xA3BAC0, 1, 1, 1},
        {"Multi::NestingContextPool", 0x32700, 0xA3B9A0, 1, 1, 1},
        {"Multi::NoFitMapCanceller", 0x32700, 0xA3B8E0, 1, 1, 1},
        {"Multi::RandomSheetSelector", 0xB0040, 0xA3BA60, 1, 1, 1},
        {"Multi::Supervisor", 0x30B60, 0xA3B4D0, 1, 3, 3},
        {"Multi::TilingNester", 0x45680, 0xA3B5A0, 1, 3, 2},
        {"Prc::AlphaPriceComputer", 0x4D9B30, 0xA3B130, 1, 2, 2},
        {"Prc::BoxPriceComputer", 0x4D9AD0, 0xA3B0B0, 1, 2, 2},
        {"Prc::HullPriceComputer", 0x4D9B00, 0xA3B0F0, 1, 2, 2},
        {"Prc::LinearCombinationPricer", 0x4D9CD0, 0xA3B170, 1, 6, 6},
        {"Row::BasicDistancer", 0x136AE0, 0xA3B1B0, 1, 1, 1},
        {"Row::Squeezer", 0x138A20, 0xA3B1E0, 1, 4, 4},
        {"Structure::ParseProblemException", 0x50CF70, 0xA534F0, 1, 4, 3},
        {"Structure::ParseSolutionException", 0x50FA10, 0xA53520, 1, 4, 3},
        {"Tiling::BoxMultiTiler", 0x4F4850, 0xA3D100, 1, 4, 4},
        {"Tiling::MultiOrientedPartPattern", 0x4F2910, 0xA3D370, 1, 2, 1},
        {"Tiling::MultitorchEvaluator", 0x4E8410, 0xA3D310, 1, 1, 1},
        {"Tiling::ObliqueEvaluator", 0x4E8170, 0xA3D240, 1, 3, 3},
        {"Tiling::OldMultitorchEvaluator", 0x4E83E0, 0xA3D340, 1, 1, 1},
        {"Tiling::PackerCache", 0x158BE0, 0xA3D0E0, 1, 3, 3},
        {"Tiling::UnlimitedDensityEvaluator", 0x4E80A0, 0xA3D3C0, 1, 1, 1},
        {"Tiling::UnlimitedXDensityEvaluator", 0x4E80D0, 0xA3D3F0, 1, 1, 1},
        {"Utils::ConnectException", 0x6D3240, 0xA3BBF0, 1, 4, 2},
        {"Utils::ResolveException", 0x6D3280, 0xA3BC20, 1, 4, 2},
        {"Utils::TimeoutException", 0x6D32C0, 0xA3BC50, 1, 4, 2},
        {"__cxxabiv1::__class_type_info", 0x656310, 0xA3AD90, 1, 2, 2},
        {"__cxxabiv1::__enum_type_info", 0x6562D0, 0xA3AD50, 1, 2, 2},
        {"__cxxabiv1::__fundamental_type_info", 0x656470, 0xA3AF80, 1, 2, 2},
        {"__cxxabiv1::__pbase_type_info", 0x656350, 0xA3ADF0, 1, 2, 2},
        {"__cxxabiv1::__pointer_type_info", 0x6563B0, 0xA3AE70, 1, 2, 2},
        {"__cxxabiv1::__si_class_type_info", 0x6563F0, 0xA3AEC0, 1, 2, 2},
        {"__cxxabiv1::__vmi_class_type_info", 0x656430, 0xA3AF20, 1, 2, 2},
        {"Multi::NestingObserver", 0x378E0, 0xA3B7C0, 0, 1, 0},
        {"Multi::RCompactCanceller", 0x67460, 0xA3B910, 0, 1, 0},
        {"Multi::StrategyBasicAdder", 0xAF750, 0xA3BA30, 0, 1, 0},
        {"Multi::StrategyDescriber", 0xAF720, 0xA3B940, 0, 1, 0},
        {"RCompact::RotateLogger", 0x24A1C0, 0xA533D0, 0, 1, 0},
        {"Structure::BoxAreaDimensioner", 0x5247F0, 0xA534C0, 0, 2, 0},
        {"Structure::SizeDimensioner", 0x5247D0, 0xA53460, 0, 2, 0},
        {"Structure::WidthDimensioner", 0x5247B0, 0xA53490, 0, 3, 0},
        {"Utils::TimerWinImplementation", 0x5F47C0, 0xA3BCB0, 0, 1, 0},
    };
    count = sizeof(table) / sizeof(table[0]);
    return table;
}

constexpr std::size_t kClassesWithConstructor = 93;
constexpr std::size_t kClassesWritingFields = 84;

}  // namespace lcns
