// lcns/include/lcns/class_definitions.hpp -- every class the module's RTTI names, DECLARED, in its own namespace.
//
// GENERATED by re/g_gen_class_definitions.py from re/vtables.json. Do not edit by hand.
//
// The repository used to name classes in prose and declare almost none -- re/g_defined_classes.py finds places where a header names one of
// the module's own classes more than once and declares it nowhere. This is the systematic answer: 46 declarations, one per class.
//
// WHAT A DECLARATION HERE CLAIMS: that the class exists, that its vtable is at the named address, and that it has that many virtual slots
// of which slot 2 is the first declared. WHAT IT DOES NOT CLAIM: anything about the class's data. **No member is invented**, because the
// vtable does not say what a class holds.
//
// 36 classes already defined by hand are NOT repeated, because two declarations of one class is a compile error and one of them
// would have to be wrong. Their names are listed in the comment beside the table.
#pragma once

#include <cstddef>
#include <cstdint>

namespace lcns {

/** The facts the RTTI and the profile establish about one class. */
struct ClassFacts {
    const char* qualified;
    std::uintptr_t vtable;
    unsigned slots;
    std::uintptr_t firstVirtual;    // slot 2, past the destructor pair
    unsigned firstVirtualBytes;     // its size, or 0 when the profile does not know it
    bool definedByHand;             // a hand-written header declares it, so it is not repeated below
};

inline const ClassFacts* classFacts(std::size_t& count) {
    static const ClassFacts table[] = {
        {"Compact::Compacter::Implementation", 0xA3D470, 3, 0x7F4140, 115, false},
        {"Engine::BestObserver", 0xA3CF30, 6, 0x755A40, 11, true},
        {"Engine::CloudEngine", 0xA3CED0, 3, 0x26A60, 15430, true},
        {"Engine::CompositeEngine", 0xA3D000, 3, 0x759B70, 8230, true},
        {"Engine::CompositeObserver", 0xA3D060, 6, 0x75CBC0, 193, false},
        {"Engine::DelayedEngine", 0xA3CF70, 3, 0x756EC0, 750, true},
        {"Engine::EquivalentEngine", 0xA3D030, 3, 0x75BCC0, 3569, true},
        {"Engine::EquivalentObserver", 0xA3D0A0, 6, 0x75DDD0, 11, false},
        {"Engine::InfiniteEngine", 0xA3CFD0, 3, 0x759A80, 80, true},
        {"Engine::MultiEngine", 0xA3CF00, 3, 0x755050, 2329, true},
        {"Engine::NestingEngine", 0xA3CFA0, 3, 0x757250, 1975, true},
        {"Json::DefaultValueAllocator", 0xA3B390, 6, 0x681B40, 98, false},
        {"Json::FastWriter", 0xA3B2F0, 3, 0x602BE0, 268, false},
        {"Json::StyledWriter", 0xA3B320, 3, 0x604020, 332, false},
        {"Multi::AdvancedStrategist", 0xA3B970, 3, 0x2DF60, 481, false},
        {"Multi::AllSheetSelector", 0xA3B840, 4, 0x7D2500, 217, false},
        {"Multi::CompactCanceller", 0xA3B870, 3, 0x7D2610, 991, false},
        {"Multi::CompactNester", 0xA3B610, 6, 0xB3890, 115, true},
        {"Multi::DatabaseNester", 0xA3B740, 6, 0xB4430, 4, true},
        {"Multi::FilterNester", 0xA3B4F0, 6, 0xB43B0, 115, true},
        {"Multi::FlipNester", 0xA3B490, 6, 0xB4440, 31, true},
        {"Multi::LargestSheetSelector", 0xA3BAC0, 4, 0x7D3C50, 136, false},
        {"Multi::LimitedNester", 0xA3B650, 6, 0xB4440, 31, true},
        {"Multi::MultiTorchNester", 0xA3B8A0, 6, 0xB4440, 31, true},
        {"Multi::NestingContextPool", 0xA3B9A0, 3, 0x7D2E20, 176, false},
        {"Multi::NestingNester", 0xA3B690, 6, 0x3B110, 115, true},
        {"Multi::NestingObserver", 0xA3B7C0, 6, 0x697060, 66, false},
        {"Multi::NoFillNester", 0xA3B530, 6, 0xB4440, 31, true},
        {"Multi::NoFitMapCanceller", 0xA3B8E0, 3, 0x7D29F0, 698, false},
        {"Multi::NoMixSheetSelector", 0xA3B9D0, 4, 0x7D2ED0, 1299, false},
        {"Multi::PartUpdaterLimiter", 0xA3BA00, 4, 0x7D3530, 201, false},
        {"Multi::RCompactCanceller", 0xA3B910, 3, 0x7D2CB0, 9, false},
        {"Multi::RandomSheetSelector", 0xA3BA60, 4, 0x7D36E0, 1316, false},
        {"Multi::RectangleNester", 0xA3B800, 6, 0xB4430, 4, true},
        {"Multi::RowNester", 0xA3BB30, 6, 0xB4430, 4, true},
        {"Multi::SplitNode", 0xA3BB70, 4, 0x97510, 6, false},
        {"Multi::StrategyBasicAdder", 0xA3BA30, 3, 0x7D3600, 214, false},
        {"Multi::StrategyDescriber", 0xA3B940, 3, 0x7D2CC0, 341, true},
        {"Multi::SupervisorCanceller", 0xA3BA90, 3, 0x30030, 485, false},
        {"Multi::TerminalNode", 0xA3B570, 4, 0x974F0, 6, false},
        {"Multi::TilingNester", 0xA3B5A0, 6, 0xB4430, 4, true},
        {"Multi::TraceObserver", 0xA3B700, 6, 0x7C2460, 3, false},
        {"Multi::WrapObserver", 0xA3B5E0, 3, 0x7D2160, 55, false},
        {"Pack::BestNester", 0xA3B400, 3, 0x15E410, 316, true},
        {"Pack::KnapsackNester", 0xA3B430, 3, 0x15DD70, 59, true},
        {"Pack::RecursiveNester", 0xA3B460, 3, 0x165680, 125, true},
        {"Prc::AlphaPriceComputer", 0xA3B130, 5, 0x7CA1B0, 6, false},
        {"Prc::BoxPriceComputer", 0xA3B0B0, 5, 0x7C9D90, 822, false},
        {"Prc::HullPriceComputer", 0xA3B0F0, 5, 0x7CA130, 6, false},
        {"Prc::LinearCombinationPricer", 0xA3B170, 5, 0x7CA370, 578, false},
        {"RCompact::RotateLogger", 0xA533D0, 8, 0x7B3030, 1, false},
        {"Row::BasicDistancer", 0xA3B1B0, 3, 0x7CA810, 6, false},
        {"Row::Squeezer", 0xA3B1E0, 3, 0x13A360, 221, true},
        {"Structure::BoxAreaDimensioner", 0xA534C0, 3, 0x81E1E0, 333, false},
        {"Structure::ClusterObserver", 0xA53420, 6, 0x7C2460, 3, false},
        {"Structure::Observer", 0xA53550, 6, 0x7C2460, 3, false},
        {"Structure::ParseProblemException", 0xA534F0, 3, 0x81ED10, 8, false},
        {"Structure::ParseSolutionException", 0xA53520, 3, 0x81ED20, 8, false},
        {"Structure::SizeDimensioner", 0xA53460, 3, 0x81DF30, 381, false},
        {"Structure::WidthDimensioner", 0xA53490, 3, 0x81E0B0, 297, false},
        {"Tiling::BasicCandidater", 0xA3D190, 3, 0x4F4600, 340, false},
        {"Tiling::BiModulePattern", 0xA3D1C0, 8, 0x7E84F0, 34, true},
        {"Tiling::BoxMultiTiler", 0xA3D100, 5, 0x7E7FC0, 278, true},
        {"Tiling::DensityEvaluator", 0xA3D210, 4, 0x7E8910, 90, true},
        {"Tiling::MultiOrientedPartPattern", 0xA3D370, 8, 0x7EBB90, 152, true},
        {"Tiling::MultitorchEvaluator", 0xA3D310, 4, 0x7E9240, 798, true},
        {"Tiling::ObliqueEvaluator", 0xA3D240, 4, 0x7E8B30, 619, true},
        {"Tiling::OldMultitorchEvaluator", 0xA3D340, 4, 0x7EB320, 699, false},
        {"Tiling::QuantityEvaluator", 0xA3D270, 4, 0x7E8DD0, 390, true},
        {"Tiling::ReusableEvaluator", 0xA3D2A0, 4, 0x7E8F60, 542, true},
        {"Tiling::SqueezeMultiTiler", 0xA3D2D0, 5, 0x7E91A0, 157, true},
        {"Tiling::UnlimitedDensityEvaluator", 0xA3D3C0, 4, 0x7EBFC0, 578, true},
        {"Tiling::UnlimitedXDensityEvaluator", 0xA3D3F0, 4, 0x7EC210, 590, true},
        {"Tiling::WarpCanceller", 0xA3D160, 3, 0x7E80E0, 19, false},
        {"Utils::BadResponseException", 0xA3BC80, 3, 0x7D7940, 8, false},
        {"Utils::Canceller", 0xA3BD70, 3, 0x7D7D20, 3, true},
        {"Utils::ConnectException", 0xA3BBF0, 3, 0x7D7910, 8, false},
        {"Utils::ResolveException", 0xA3BC20, 3, 0x7D7920, 8, false},
        {"Utils::TimeoutException", 0xA3BC50, 3, 0x7D7930, 8, false},
        {"Utils::TimerWinImplementation", 0xA3BCB0, 3, 0x6D5910, 67, false},
        {"dbg::file_error", 0xA3B210, 3, 0x7CA820, 5, false},
        {"dbg::symlog", 0xA3B240, 3, 0x60B330, 418, false},
    };
    count = sizeof(table) / sizeof(table[0]);
    return table;
}

constexpr std::size_t kDeclaredIn_Compact__Compacter = 1;
constexpr std::size_t kDeclaredIn_EngineNS = 2;
constexpr std::size_t kDeclaredIn_Json = 3;
constexpr std::size_t kDeclaredIn_Multi = 17;
constexpr std::size_t kDeclaredIn_Prc = 4;
constexpr std::size_t kDeclaredIn_RCompact = 1;
constexpr std::size_t kDeclaredIn_Row = 1;
constexpr std::size_t kDeclaredIn_Structure = 7;
constexpr std::size_t kDeclaredIn_Tiling = 3;
constexpr std::size_t kDeclaredIn_Utils = 5;
constexpr std::size_t kDeclaredIn_dbg = 2;

// ------------------------------------------------------------------------------------------------
// THE DECLARATIONS. Each carries the virtual count the RTTI gives it; the only method named is the destructor, because
// the ABI gives that one and the module does not have to say it.

namespace Compact { namespace Compacter {

/** Compact::Compacter::Implementation -- vtable 0xA3D470, 3 virtual slot(s). */
class Implementation {
public:
    virtual ~Implementation() = default;

    // Slot 2, the first DECLARED virtual, is 0x7F4140 -- 115 bytes, read.
};
}  // namespace
}  // namespace

namespace EngineNS {

/** Engine::CompositeObserver -- vtable 0xA3D060, 6 virtual slot(s). */
class CompositeObserver {
public:
    virtual ~CompositeObserver() = default;

    // Slot 2, the first DECLARED virtual, is 0x75CBC0 -- 193 bytes, read.
};

/** Engine::EquivalentObserver -- vtable 0xA3D0A0, 6 virtual slot(s). */
class EquivalentObserver {
public:
    virtual ~EquivalentObserver() = default;

    // Slot 2, the first DECLARED virtual, is 0x75DDD0 -- 11 bytes, read.
};
}  // namespace

namespace Json {

/** Json::DefaultValueAllocator -- vtable 0xA3B390, 6 virtual slot(s). */
class DefaultValueAllocator {
public:
    virtual ~DefaultValueAllocator() = default;

    // Slot 2, the first DECLARED virtual, is 0x681B40 -- 98 bytes, read.
};

/** Json::FastWriter -- vtable 0xA3B2F0, 3 virtual slot(s). */
class FastWriter {
public:
    virtual ~FastWriter() = default;

    // Slot 2, the first DECLARED virtual, is 0x602BE0 -- 268 bytes, read.
};

/** Json::StyledWriter -- vtable 0xA3B320, 3 virtual slot(s). */
class StyledWriter {
public:
    virtual ~StyledWriter() = default;

    // Slot 2, the first DECLARED virtual, is 0x604020 -- 332 bytes, read.
};
}  // namespace

namespace Multi {

/** Multi::AdvancedStrategist -- vtable 0xA3B970, 3 virtual slot(s). */
class AdvancedStrategist {
public:
    virtual ~AdvancedStrategist() = default;

    // Slot 2, the first DECLARED virtual, is 0x2DF60 -- 481 bytes, read.
};

/** Multi::AllSheetSelector -- vtable 0xA3B840, 4 virtual slot(s). */
class AllSheetSelector {
public:
    virtual ~AllSheetSelector() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D2500 -- 217 bytes, read.
};

/** Multi::CompactCanceller -- vtable 0xA3B870, 3 virtual slot(s). */
class CompactCanceller {
public:
    virtual ~CompactCanceller() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D2610 -- 991 bytes, read.
};

/** Multi::LargestSheetSelector -- vtable 0xA3BAC0, 4 virtual slot(s). */
class LargestSheetSelector {
public:
    virtual ~LargestSheetSelector() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D3C50 -- 136 bytes, read.
};

/** Multi::NestingContextPool -- vtable 0xA3B9A0, 3 virtual slot(s). */
class NestingContextPool {
public:
    virtual ~NestingContextPool() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D2E20 -- 176 bytes, read.
};

/** Multi::NestingObserver -- vtable 0xA3B7C0, 6 virtual slot(s). */
class NestingObserver {
public:
    virtual ~NestingObserver() = default;

    // Slot 2, the first DECLARED virtual, is 0x697060 -- 66 bytes, read.
};

/** Multi::NoFitMapCanceller -- vtable 0xA3B8E0, 3 virtual slot(s). */
class NoFitMapCanceller {
public:
    virtual ~NoFitMapCanceller() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D29F0 -- 698 bytes, read.
};

/** Multi::NoMixSheetSelector -- vtable 0xA3B9D0, 4 virtual slot(s). */
class NoMixSheetSelector {
public:
    virtual ~NoMixSheetSelector() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D2ED0 -- 1299 bytes, read.
};

/** Multi::PartUpdaterLimiter -- vtable 0xA3BA00, 4 virtual slot(s). */
class PartUpdaterLimiter {
public:
    virtual ~PartUpdaterLimiter() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D3530 -- 201 bytes, read.
};

/** Multi::RCompactCanceller -- vtable 0xA3B910, 3 virtual slot(s). */
class RCompactCanceller {
public:
    virtual ~RCompactCanceller() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D2CB0 -- 9 bytes, read.
};

/** Multi::RandomSheetSelector -- vtable 0xA3BA60, 4 virtual slot(s). */
class RandomSheetSelector {
public:
    virtual ~RandomSheetSelector() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D36E0 -- 1316 bytes, read.
};

/** Multi::SplitNode -- vtable 0xA3BB70, 4 virtual slot(s). */
class SplitNode {
public:
    virtual ~SplitNode() = default;

    // Slot 2, the first DECLARED virtual, is 0x97510 -- 6 bytes, read.
};

/** Multi::StrategyBasicAdder -- vtable 0xA3BA30, 3 virtual slot(s). */
class StrategyBasicAdder {
public:
    virtual ~StrategyBasicAdder() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D3600 -- 214 bytes, read.
};

/** Multi::SupervisorCanceller -- vtable 0xA3BA90, 3 virtual slot(s). */
class SupervisorCanceller {
public:
    virtual ~SupervisorCanceller() = default;

    // Slot 2, the first DECLARED virtual, is 0x30030 -- 485 bytes, read.
};

/** Multi::TerminalNode -- vtable 0xA3B570, 4 virtual slot(s). */
class TerminalNode {
public:
    virtual ~TerminalNode() = default;

    // Slot 2, the first DECLARED virtual, is 0x974F0 -- 6 bytes, read.
};

/** Multi::TraceObserver -- vtable 0xA3B700, 6 virtual slot(s). */
class TraceObserver {
public:
    virtual ~TraceObserver() = default;

    // Slot 2, the first DECLARED virtual, is 0x7C2460 -- 3 bytes, read.
};

/** Multi::WrapObserver -- vtable 0xA3B5E0, 3 virtual slot(s). */
class WrapObserver {
public:
    virtual ~WrapObserver() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D2160 -- 55 bytes, read.
};
}  // namespace

namespace Prc {

/** Prc::AlphaPriceComputer -- vtable 0xA3B130, 5 virtual slot(s). */
class AlphaPriceComputer {
public:
    virtual ~AlphaPriceComputer() = default;

    // Slot 2, the first DECLARED virtual, is 0x7CA1B0 -- 6 bytes, read.
};

/** Prc::BoxPriceComputer -- vtable 0xA3B0B0, 5 virtual slot(s). */
class BoxPriceComputer {
public:
    virtual ~BoxPriceComputer() = default;

    // Slot 2, the first DECLARED virtual, is 0x7C9D90 -- 822 bytes, read.
};

/** Prc::HullPriceComputer -- vtable 0xA3B0F0, 5 virtual slot(s). */
class HullPriceComputer {
public:
    virtual ~HullPriceComputer() = default;

    // Slot 2, the first DECLARED virtual, is 0x7CA130 -- 6 bytes, read.
};

/** Prc::LinearCombinationPricer -- vtable 0xA3B170, 5 virtual slot(s). */
class LinearCombinationPricer {
public:
    virtual ~LinearCombinationPricer() = default;

    // Slot 2, the first DECLARED virtual, is 0x7CA370 -- 578 bytes, read.
};
}  // namespace

namespace RCompact {

/** RCompact::RotateLogger -- vtable 0xA533D0, 8 virtual slot(s). */
class RotateLogger {
public:
    virtual ~RotateLogger() = default;

    // Slot 2, the first DECLARED virtual, is 0x7B3030 -- 1 bytes, read.
};
}  // namespace

namespace Row {

/** Row::BasicDistancer -- vtable 0xA3B1B0, 3 virtual slot(s). */
class BasicDistancer {
public:
    virtual ~BasicDistancer() = default;

    // Slot 2, the first DECLARED virtual, is 0x7CA810 -- 6 bytes, read.
};
}  // namespace

namespace Structure {

/** Structure::BoxAreaDimensioner -- vtable 0xA534C0, 3 virtual slot(s). */
class BoxAreaDimensioner {
public:
    virtual ~BoxAreaDimensioner() = default;

    // Slot 2, the first DECLARED virtual, is 0x81E1E0 -- 333 bytes, read.
};

/** Structure::ClusterObserver -- vtable 0xA53420, 6 virtual slot(s). */
class ClusterObserver {
public:
    virtual ~ClusterObserver() = default;

    // Slot 2, the first DECLARED virtual, is 0x7C2460 -- 3 bytes, read.
};

/** Structure::Observer -- vtable 0xA53550, 6 virtual slot(s). */
class Observer {
public:
    virtual ~Observer() = default;

    // Slot 2, the first DECLARED virtual, is 0x7C2460 -- 3 bytes, read.
};

/** Structure::ParseProblemException -- vtable 0xA534F0, 3 virtual slot(s). */
class ParseProblemException {
public:
    virtual ~ParseProblemException() = default;

    // Slot 2, the first DECLARED virtual, is 0x81ED10 -- 8 bytes, read.
};

/** Structure::ParseSolutionException -- vtable 0xA53520, 3 virtual slot(s). */
class ParseSolutionException {
public:
    virtual ~ParseSolutionException() = default;

    // Slot 2, the first DECLARED virtual, is 0x81ED20 -- 8 bytes, read.
};

/** Structure::SizeDimensioner -- vtable 0xA53460, 3 virtual slot(s). */
class SizeDimensioner {
public:
    virtual ~SizeDimensioner() = default;

    // Slot 2, the first DECLARED virtual, is 0x81DF30 -- 381 bytes, read.
};

/** Structure::WidthDimensioner -- vtable 0xA53490, 3 virtual slot(s). */
class WidthDimensioner {
public:
    virtual ~WidthDimensioner() = default;

    // Slot 2, the first DECLARED virtual, is 0x81E0B0 -- 297 bytes, read.
};
}  // namespace

namespace Tiling {

/** Tiling::BasicCandidater -- vtable 0xA3D190, 3 virtual slot(s). */
class BasicCandidater {
public:
    virtual ~BasicCandidater() = default;

    // Slot 2, the first DECLARED virtual, is 0x4F4600 -- 340 bytes, read.
};

/** Tiling::OldMultitorchEvaluator -- vtable 0xA3D340, 4 virtual slot(s). */
class OldMultitorchEvaluator {
public:
    virtual ~OldMultitorchEvaluator() = default;

    // Slot 2, the first DECLARED virtual, is 0x7EB320 -- 699 bytes, read.
};

/** Tiling::WarpCanceller -- vtable 0xA3D160, 3 virtual slot(s). */
class WarpCanceller {
public:
    virtual ~WarpCanceller() = default;

    // Slot 2, the first DECLARED virtual, is 0x7E80E0 -- 19 bytes, read.
};
}  // namespace

namespace Utils {

/** Utils::BadResponseException -- vtable 0xA3BC80, 3 virtual slot(s). */
class BadResponseException {
public:
    virtual ~BadResponseException() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D7940 -- 8 bytes, read.
};

/** Utils::ConnectException -- vtable 0xA3BBF0, 3 virtual slot(s). */
class ConnectException {
public:
    virtual ~ConnectException() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D7910 -- 8 bytes, read.
};

/** Utils::ResolveException -- vtable 0xA3BC20, 3 virtual slot(s). */
class ResolveException {
public:
    virtual ~ResolveException() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D7920 -- 8 bytes, read.
};

/** Utils::TimeoutException -- vtable 0xA3BC50, 3 virtual slot(s). */
class TimeoutException {
public:
    virtual ~TimeoutException() = default;

    // Slot 2, the first DECLARED virtual, is 0x7D7930 -- 8 bytes, read.
};

/** Utils::TimerWinImplementation -- vtable 0xA3BCB0, 3 virtual slot(s). */
class TimerWinImplementation {
public:
    virtual ~TimerWinImplementation() = default;

    // Slot 2, the first DECLARED virtual, is 0x6D5910 -- 67 bytes, read.
};
}  // namespace

namespace dbg {

/** dbg::file_error -- vtable 0xA3B210, 3 virtual slot(s). */
class file_error {
public:
    virtual ~file_error() = default;

    // Slot 2, the first DECLARED virtual, is 0x7CA820 -- 5 bytes, read.
};

/** dbg::symlog -- vtable 0xA3B240, 3 virtual slot(s). */
class symlog {
public:
    virtual ~symlog() = default;

    // Slot 2, the first DECLARED virtual, is 0x60B330 -- 418 bytes, read.
};
}  // namespace

}  // namespace lcns
