// lcns/include/lcns/classes.hpp -- the module's own classes, generated from its RTTI.
//
// GENERATED by re/g_gen_classes.py from re/vtables.json. Do not edit by hand.
//
// The human asked why InfiniteEngine had only a comment. It did, and so did every other class: the repository listed slot RVAs in prose
// and defined none of them. This file states the hierarchy the module's OWN RTTI states -- 96 classes after the standard library,
// boost, CryptoPP, Json, Coin and Clp are set aside -- each with its vtable address, its slot count and its mangled name.
//
// WHAT A DECLARATION HERE MEANS: that this class exists, that its type_info is at the named vtable, and that it has that many virtual
// slots. WHAT IT DOES NOT MEAN: anything about its data. The vtable does not say what a class holds, so members are not invented -- and
// the mangled name is carried beside the demangled one because the demangling is a decode and the mangling is not.
#pragma once

#include <cstddef>
#include <cstdint>

namespace lcns {

/** The vtable and slot count of one class, as its RTTI states them. */
struct ClassInfo {
    const char* mangled;
    const char* qualified;      // the demangled name, which is a decode of the mangling
    std::uintptr_t vtable;
    unsigned slots;
};

inline const ClassInfo* moduleClasses(std::size_t& count) {
    static const ClassInfo table[] = {
        {"NSt13__future_base12_Result_baseE", "<subst>::__future_base::_Result_base", 0xA541F0, 1},
        {"NSt8ios_base7failureE", "<subst>::ios_base::failure", 0xA55020, 3},
        {"NSt6thread11_State_implISt12_Bind_simpleIFPFvP21CNS_SingleComputationRKSt10shared_ptrIN6Engine6EngineEEES3_S7_EEEE", "<subst>::thread::_State_impl::<<subst>::<subst>::<subst>::shared_ptr::<Engine::Engine>>::<subst>::<subst>", 0xA542C0, 3},
        {"NSt6thread11_State_implISt12_Bind_simpleIFPFvP18CNS_LaunchingOrderES3_EEEE", "<subst>::thread::_State_impl::<<subst>>::<subst>", 0xA54290, 3},
        {"NSt6thread11_State_implISt12_Bind_simpleIFPFvPKSt10shared_ptrIN6Engine6EngineEEPKN9Structure7ProblemEdPNS8_8ObserverEPNS3_6ResultEES7_SB_dPNS3_17CompositeObserverESF_EEEE", "<subst>::thread::_State_impl::<Engine::Engine>::Structure::Problem", 0xA542F0, 3},
        {"NSt6thread11_State_implISt12_Bind_simpleIFPFvPN5Multi10SupervisorEjjES4_jjEEEE", "<subst>::thread::_State_impl::<Multi::Supervisor>", 0xA54320, 3},
        {"NSt6thread11_State_implISt12_Bind_simpleIFZN24NoFitMultiThreadComputer18RunAllComputationsEvEUlvE_vEEEE", "<subst>::thread::_State_impl::<NoFitMultiThreadComputer::RunAllComputations>", 0xA54350, 3},
        {"NSt6thread11_State_implISt12_Bind_simpleIFZN6Tiling11PackerCache14Implementation16PreUpdateTilingsERKSt6vectorISt4pairIjiESaIS7_EEddPNS2_19PartUpdaterInformerEEUlvE_vEEEE", "<subst>::thread::_State_impl::<Tiling::PackerCache::Implementation::PreUpdateTilings>::<subst>::vector::<<subst>::PartUpdaterInformer>", 0xA54380, 3},
        {"N7Compact9Compacter14ImplementationE", "Compact::Compacter::Implementation", 0xA3D470, 3},
        {"N6Engine12BestObserverE", "Engine::BestObserver", 0xA3CF30, 6},
        {"N6Engine11CloudEngineE", "Engine::CloudEngine", 0xA3CED0, 3},
        {"N6Engine15CompositeEngineE", "Engine::CompositeEngine", 0xA3D000, 3},
        {"N6Engine17CompositeObserverE", "Engine::CompositeObserver", 0xA3D060, 6},
        {"N6Engine13DelayedEngineE", "Engine::DelayedEngine", 0xA3CF70, 3},
        {"N6Engine16EquivalentEngineE", "Engine::EquivalentEngine", 0xA3D030, 3},
        {"N6Engine18EquivalentObserverE", "Engine::EquivalentObserver", 0xA3D0A0, 6},
        {"N6Engine14InfiniteEngineE", "Engine::InfiniteEngine", 0xA3CFD0, 3},
        {"N6Engine11MultiEngineE", "Engine::MultiEngine", 0xA3CF00, 3},
        {"N6Engine13NestingEngineE", "Engine::NestingEngine", 0xA3CFA0, 3},
        {"N4Json21DefaultValueAllocatorE", "Json::DefaultValueAllocator", 0xA3B390, 6},
        {"N4Json10FastWriterE", "Json::FastWriter", 0xA3B2F0, 3},
        {"N4Json12StyledWriterE", "Json::StyledWriter", 0xA3B320, 3},
        {"N5Multi18AdvancedStrategistE", "Multi::AdvancedStrategist", 0xA3B970, 3},
        {"N5Multi16AllSheetSelectorE", "Multi::AllSheetSelector", 0xA3B840, 4},
        {"N5Multi16CompactCancellerE", "Multi::CompactCanceller", 0xA3B870, 3},
        {"N5Multi13CompactNesterE", "Multi::CompactNester", 0xA3B610, 6},
        {"N5Multi14DatabaseNesterE", "Multi::DatabaseNester", 0xA3B740, 6},
        {"N5Multi12FilterNesterE", "Multi::FilterNester", 0xA3B4F0, 6},
        {"N5Multi10FlipNesterE", "Multi::FlipNester", 0xA3B490, 6},
        {"N5Multi20LargestSheetSelectorE", "Multi::LargestSheetSelector", 0xA3BAC0, 4},
        {"N5Multi13LimitedNesterE", "Multi::LimitedNester", 0xA3B650, 6},
        {"N5Multi16MultiTorchNesterE", "Multi::MultiTorchNester", 0xA3B8A0, 6},
        {"N5Multi18NestingContextPoolE", "Multi::NestingContextPool", 0xA3B9A0, 3},
        {"N5Multi13NestingNesterE", "Multi::NestingNester", 0xA3B690, 6},
        {"N5Multi15NestingObserverE", "Multi::NestingObserver", 0xA3B7C0, 6},
        {"N5Multi12NoFillNesterE", "Multi::NoFillNester", 0xA3B530, 6},
        {"N5Multi17NoFitMapCancellerE", "Multi::NoFitMapCanceller", 0xA3B8E0, 3},
        {"N5Multi18NoMixSheetSelectorE", "Multi::NoMixSheetSelector", 0xA3B9D0, 4},
        {"N5Multi18PartUpdaterLimiterE", "Multi::PartUpdaterLimiter", 0xA3BA00, 4},
        {"N5Multi17RCompactCancellerE", "Multi::RCompactCanceller", 0xA3B910, 3},
        {"N5Multi19RandomSheetSelectorE", "Multi::RandomSheetSelector", 0xA3BA60, 4},
        {"N5Multi15RectangleNesterE", "Multi::RectangleNester", 0xA3B800, 6},
        {"N5Multi9RowNesterE", "Multi::RowNester", 0xA3BB30, 6},
        {"N5Multi9SplitNodeE", "Multi::SplitNode", 0xA3BB70, 4},
        {"N5Multi18StrategyBasicAdderE", "Multi::StrategyBasicAdder", 0xA3BA30, 3},
        {"N5Multi17StrategyDescriberE", "Multi::StrategyDescriber", 0xA3B940, 3},
        {"N5Multi10SupervisorE", "Multi::Supervisor", 0xA3B4D0, 2},
        {"N5Multi19SupervisorCancellerE", "Multi::SupervisorCanceller", 0xA3BA90, 3},
        {"N5Multi12TerminalNodeE", "Multi::TerminalNode", 0xA3B570, 4},
        {"N5Multi12TilingNesterE", "Multi::TilingNester", 0xA3B5A0, 6},
        {"N5Multi13TraceObserverE", "Multi::TraceObserver", 0xA3B700, 6},
        {"N5Multi12WrapObserverE", "Multi::WrapObserver", 0xA3B5E0, 3},
        {"N4Pack10BestNesterE", "Pack::BestNester", 0xA3B400, 3},
        {"N4Pack14KnapsackNesterE", "Pack::KnapsackNester", 0xA3B430, 3},
        {"N4Pack15RecursiveNesterE", "Pack::RecursiveNester", 0xA3B460, 3},
        {"N3Prc18AlphaPriceComputerE", "Prc::AlphaPriceComputer", 0xA3B130, 5},
        {"N3Prc16BoxPriceComputerE", "Prc::BoxPriceComputer", 0xA3B0B0, 5},
        {"N3Prc17HullPriceComputerE", "Prc::HullPriceComputer", 0xA3B0F0, 5},
        {"N3Prc23LinearCombinationPricerE", "Prc::LinearCombinationPricer", 0xA3B170, 5},
        {"N8RCompact12RotateLoggerE", "RCompact::RotateLogger", 0xA533D0, 8},
        {"N3Row14BasicDistancerE", "Row::BasicDistancer", 0xA3B1B0, 3},
        {"N3Row8SqueezerE", "Row::Squeezer", 0xA3B1E0, 3},
        {"N9Structure18BoxAreaDimensionerE", "Structure::BoxAreaDimensioner", 0xA534C0, 3},
        {"N9Structure15ClusterObserverE", "Structure::ClusterObserver", 0xA53420, 6},
        {"N9Structure8ObserverE", "Structure::Observer", 0xA53550, 6},
        {"N9Structure21ParseProblemExceptionE", "Structure::ParseProblemException", 0xA534F0, 3},
        {"N9Structure22ParseSolutionExceptionE", "Structure::ParseSolutionException", 0xA53520, 3},
        {"N9Structure15SizeDimensionerE", "Structure::SizeDimensioner", 0xA53460, 3},
        {"N9Structure16WidthDimensionerE", "Structure::WidthDimensioner", 0xA53490, 3},
        {"N6Tiling15BasicCandidaterE", "Tiling::BasicCandidater", 0xA3D190, 3},
        {"N6Tiling15BiModulePatternE", "Tiling::BiModulePattern", 0xA3D1C0, 8},
        {"N6Tiling13BoxMultiTilerE", "Tiling::BoxMultiTiler", 0xA3D100, 5},
        {"N6Tiling13CompositePartE", "Tiling::CompositePart", 0xA3D140, 2},
        {"N6Tiling16DensityEvaluatorE", "Tiling::DensityEvaluator", 0xA3D210, 4},
        {"N6Tiling24MultiOrientedPartPatternE", "Tiling::MultiOrientedPartPattern", 0xA3D370, 8},
        {"N6Tiling19MultitorchEvaluatorE", "Tiling::MultitorchEvaluator", 0xA3D310, 4},
        {"N6Tiling16ObliqueEvaluatorE", "Tiling::ObliqueEvaluator", 0xA3D240, 4},
        {"N6Tiling22OldMultitorchEvaluatorE", "Tiling::OldMultitorchEvaluator", 0xA3D340, 4},
        {"N6Tiling11PackerCacheE", "Tiling::PackerCache", 0xA3D0E0, 2},
        {"N6Tiling4PartE", "Tiling::Part", 0xA3D420, 2},
        {"N6Tiling17QuantityEvaluatorE", "Tiling::QuantityEvaluator", 0xA3D270, 4},
        {"N6Tiling17ReusableEvaluatorE", "Tiling::ReusableEvaluator", 0xA3D2A0, 4},
        {"N6Tiling17SqueezeMultiTilerE", "Tiling::SqueezeMultiTiler", 0xA3D2D0, 5},
        {"N6Tiling25UnlimitedDensityEvaluatorE", "Tiling::UnlimitedDensityEvaluator", 0xA3D3C0, 4},
        {"N6Tiling26UnlimitedXDensityEvaluatorE", "Tiling::UnlimitedXDensityEvaluator", 0xA3D3F0, 4},
        {"N6Tiling13WarpCancellerE", "Tiling::WarpCanceller", 0xA3D160, 3},
        {"N5Utils20BadResponseExceptionE", "Utils::BadResponseException", 0xA3BC80, 3},
        {"N5Utils9CancellerE", "Utils::Canceller", 0xA3BD70, 3},
        {"N5Utils16ConnectExceptionE", "Utils::ConnectException", 0xA3BBF0, 3},
        {"N5Utils7LogSinkE", "Utils::LogSink", 0xA3BD40, 1},
        {"N5Utils11OstreamSinkI16NestingSinkModelEE", "Utils::OstreamSink::<<subst>>", 0xA3BBA0, 8},
        {"N5Utils16ResolveExceptionE", "Utils::ResolveException", 0xA3BC20, 3},
        {"N5Utils16TimeoutExceptionE", "Utils::TimeoutException", 0xA3BC50, 3},
        {"N5Utils22TimerWinImplementationE", "Utils::TimerWinImplementation", 0xA3BCB0, 3},
        {"N3dbg10file_errorE", "dbg::file_error", 0xA3B210, 3},
        {"N3dbg6symlogE", "dbg::symlog", 0xA3B240, 3},
    };
    count = sizeof(table) / sizeof(table[0]);
    return table;
}

constexpr std::size_t kClassesIn_Multi = 30;
constexpr std::size_t kClassesIn_Tiling = 17;
constexpr std::size_t kClassesIn_Engine = 10;
constexpr std::size_t kClassesIn__subst_ = 8;
constexpr std::size_t kClassesIn_Utils = 8;
constexpr std::size_t kClassesIn_Structure = 7;
constexpr std::size_t kClassesIn_Prc = 4;
constexpr std::size_t kClassesIn_Json = 3;
constexpr std::size_t kClassesIn_Pack = 3;
constexpr std::size_t kClassesIn_Row = 2;
constexpr std::size_t kClassesIn_dbg = 2;
constexpr std::size_t kClassesIn_Compact = 1;
constexpr std::size_t kClassesIn_RCompact = 1;
}  // namespace lcns
