// lcns/field_accessors.hpp -- the three and four byte field accessors read out of the closures.
//
// Generated by re/g_add_accessors.py. Every name carries the RVA it was read from, because the field meanings
// are not recoverable from the code: these functions only move a value in or out. They are inline so that the
// build files do not have to change for each batch.
#pragma once

#include <cstdint>
#include <cstring>

namespace lcns {
namespace dll {
namespace accessors {

/** RE 0x52F920: reads the 32-bit field at +0x00. */
inline std::uint32_t getDword00_52F920(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x54CE90: reads the 32-bit field at +0x00. */
inline std::uint32_t getDword00_54CE90(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x54D110: writes the 8-bit field at +0x00 and nothing else. */
inline void setByte00_54D110(void* object, std::uint8_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x00, &value, sizeof(value));
}

/** RE 0x4F8C60: reads the 32-bit field at +0x60. */
inline std::uint32_t getDword60_4F8C60(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x60, sizeof(value));
    return value;
}

/** RE 0x4F8CC0: writes the 32-bit field at +0x64 and nothing else. */
inline void setDword64_4F8CC0(void* object, std::uint32_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x64, &value, sizeof(value));
}

/** RE 0x4F76C0: writes the 32-bit field at +0x6C and nothing else. */
inline void setDword6C_4F76C0(void* object, std::uint32_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x6C, &value, sizeof(value));
}

/** RE 0x4F7270: writes the 32-bit field at +0x28 and nothing else. */
inline void setDword28_4F7270(void* object, std::uint32_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x28, &value, sizeof(value));
}

/** RE 0x4F7290: writes the 8-bit field at +0x2C and nothing else. */
inline void setByte2C_4F7290(void* object, std::uint8_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x2C, &value, sizeof(value));
}

/** RE 0x4F7380: writes the 8-bit field at +0x6A and nothing else. */
inline void setByte6A_4F7380(void* object, std::uint8_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x6A, &value, sizeof(value));
}

/** RE 0x4F8360: reads the 32-bit field at +0x20. */
inline std::uint32_t getDword20_4F8360(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x20, sizeof(value));
    return value;
}

/** RE 0x4F8CD0: reads the 32-bit field at +0x64. */
inline std::uint32_t getDword64_4F8CD0(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x64, sizeof(value));
    return value;
}

/** RE 0x4F7060: reads the 32-bit field at +0x24. */
inline std::uint32_t getDword24_4F7060(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x24, sizeof(value));
    return value;
}

/** RE 0x4F76D0: reads the 32-bit field at +0x6C. */
inline std::uint32_t getDword6C_4F76D0(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x6C, sizeof(value));
    return value;
}

/** RE 0x52F8D0: writes the 8-bit field at +0x20 and nothing else. */
inline void setByte20_52F8D0(void* object, std::uint8_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x20, &value, sizeof(value));
}

/** RE 0x52F8E0: writes the 8-bit field at +0x21 and nothing else. */
inline void setByte21_52F8E0(void* object, std::uint8_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x21, &value, sizeof(value));
}
/** RE 0x54D100: reads the 8-bit value at +0x00. */
inline std::uint8_t getByte00_54D100(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x5C4CD0: reads the 8-bit value at +0x00. */
inline std::uint8_t getByte00_5C4CD0(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x4F7050: reads the 32-bit value at +0x24. */
inline std::uint32_t getDword24_4F7050(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x24, sizeof(value));
    return value;
}

/** RE 0x4FC1D0: reads the 64-bit value at +0x00. */
inline std::uint64_t getPtr00_4FC1D0(const void* object) {
    std::uint64_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x5FC7E0: reads the 64-bit value at +0x00. */
inline std::uint64_t getPtr00_5FC7E0(const void* object) {
    std::uint64_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x4FC200: reads the 64-bit value at +0x00. */
inline std::uint64_t getPtr00_4FC200(const void* object) {
    std::uint64_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x4F8C70: writes the 32-bit value at +0x60 and nothing else. */
inline void setDword60_4F8C70(void* object, std::uint32_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x60, &value, sizeof(value));
}

/** RE 0x4F76B0: writes the 32-bit value at +0x20 and nothing else. */
inline void setDword20_4F76B0(void* object, std::uint32_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x20, &value, sizeof(value));
}

/** RE 0x548390: reads the 32-bit value at +0x20. */
inline std::uint32_t getDword20_548390(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x20, sizeof(value));
    return value;
}
/** RE 0x52F930: reads the 8-bit value at +0x20. */
inline std::uint8_t getByte20_52F930(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x20, sizeof(value));
    return value;
}

/** RE 0x52F940: reads the 8-bit value at +0x21. */
inline std::uint8_t getByte21_52F940(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x21, sizeof(value));
    return value;
}

/** RE 0x4F7350: reads the 8-bit value at +0x68. */
inline std::uint8_t getByte68_4F7350(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x68, sizeof(value));
    return value;
}

/** RE 0x4F7360: reads the 8-bit value at +0x69. */
inline std::uint8_t getByte69_4F7360(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x69, sizeof(value));
    return value;
}

/** RE 0x4F73A0: reads the 8-bit value at +0x6A. */
inline std::uint8_t getByte6A_4F73A0(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x6A, sizeof(value));
    return value;
}

/** RE 0x5FBC70: reads the 8-bit value at +0x08. */
inline std::uint8_t getByte08_5FBC70(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x08, sizeof(value));
    return value;
}

/** RE 0x5C4CE0: reads the 64-bit value at +0x08. */
inline std::uint64_t getPtr08_5C4CE0(const void* object) {
    std::uint64_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x08, sizeof(value));
    return value;
}

/** RE 0x4F73C0: returns the address of the member at +0x70, not its value. */
inline void* addr70_4F73C0(void* object) {
    return static_cast<unsigned char*>(object) + 0x70;
}

/** RE 0x5C5F40: returns the address of the member at +0x18, not its value. */
inline void* addr18_5C5F40(void* object) {
    return static_cast<unsigned char*>(object) + 0x18;
}

/** RE 0x54D120: returns the address of the member at +0x08, not its value. */
inline void* addr08_54D120(void* object) {
    return static_cast<unsigned char*>(object) + 0x08;
}

/** RE 0x5C5F60: returns the address of the member at +0x18, not its value. */
inline void* addr18_5C5F60(void* object) {
    return static_cast<unsigned char*>(object) + 0x18;
}

/** RE 0x5483B0: returns the address of the member at +0x38, not its value. */
inline void* addr38_5483B0(void* object) {
    return static_cast<unsigned char*>(object) + 0x38;
}

/** RE 0x5483A0: returns the address of the member at +0x28, not its value. */
inline void* addr28_5483A0(void* object) {
    return static_cast<unsigned char*>(object) + 0x28;
}

/** RE 0x54CE60: copies one dword from the second argument to the first. */
inline void copyDword_54CE60(void* destination, const void* source) {
    std::uint32_t value = 0;
    std::memcpy(&value, source, sizeof(value));
    std::memcpy(destination, &value, sizeof(value));
}

/** RE 0x52F8A0: copies one dword from the second argument to the first. */
inline void copyDword_52F8A0(void* destination, const void* source) {
    std::uint32_t value = 0;
    std::memcpy(&value, source, sizeof(value));
    std::memcpy(destination, &value, sizeof(value));
}
/** RE 0x4F8F80: reads the 32-bit value at +0xA0. */
inline std::uint32_t getA0_4F8F80(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0xA0, sizeof(value));
    return value;
}

/** RE 0x4F8F90: reads the 32-bit value at +0xA4. */
inline std::uint32_t getA4_4F8F90(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0xA4, sizeof(value));
    return value;
}

/** RE 0x4F73B0: reads the 32-bit value at +0xA0. */
inline std::uint32_t getA0_4F73B0(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0xA0, sizeof(value));
    return value;
}

/** RE 0x4F8540: reads the 8-bit value at +0x90. */
inline std::uint8_t get90_4F8540(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x90, sizeof(value));
    return value;
}

/** RE 0x4F7390: writes the 32-bit value at +0xA0 and nothing else. */
inline void setA0_4F7390(void* object, std::uint32_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0xA0, &value, sizeof(value));
}

/** RE 0x895F80: writes the 64-bit value at +0x00 and nothing else. */
inline void set00_895F80(void* object, std::uint64_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x00, &value, sizeof(value));
}

/** RE 0x5479B0: returns the address of the member at +0x68, not its value. */
inline void* addr68_5479B0(void* object) {
    return static_cast<unsigned char*>(object) + 0x68;
}

/** RE 0x4F77C0: returns the address of the member at +0x88, not its value. */
inline void* addr88_4F77C0(void* object) {
    return static_cast<unsigned char*>(object) + 0x88;
}

/** RE 0x547670: returns the address of the member at +0x90, not its value. */
inline void* addr90_547670(void* object) {
    return static_cast<unsigned char*>(object) + 0x90;
}

/** RE 0x4F8FA0: returns the address of the member at +0xA8, not its value. */
inline void* addrA8_4F8FA0(void* object) {
    return static_cast<unsigned char*>(object) + 0xA8;
}
/** RE 0x4F8370: reads the double at +0x28, as movsd does. */
inline double getDouble28_4F8370(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x28, sizeof(value));
    return value;
}

/** RE 0x4F8380: reads the double at +0x30, as movsd does. */
inline double getDouble30_4F8380(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x30, sizeof(value));
    return value;
}

/** RE 0x4F8C80: reads the double at +0x38, as movsd does. */
inline double getDouble38_4F8C80(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x38, sizeof(value));
    return value;
}

/** RE 0x4F8C90: reads the double at +0x40, as movsd does. */
inline double getDouble40_4F8C90(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x40, sizeof(value));
    return value;
}

/** RE 0x4F8CA0: reads the double at +0x48, as movsd does. */
inline double getDouble48_4F8CA0(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x48, sizeof(value));
    return value;
}

/** RE 0x4F8CB0: reads the double at +0x50, as movsd does. */
inline double getDouble50_4F8CB0(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x50, sizeof(value));
    return value;
}

/** RE 0x4F9C30: reads the double at +0x58, as movsd does. */
inline double getDouble58_4F9C30(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x58, sizeof(value));
    return value;
}

/** RE 0x52F900: reads the double at +0x10, as movsd does. */
inline double getDouble10_52F900(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x10, sizeof(value));
    return value;
}

/** RE 0x52F910: reads the double at +0x18, as movsd does. */
inline double getDouble18_52F910(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x18, sizeof(value));
    return value;
}

/** RE 0x4F7330: reads the double at +0x60, as movsd does. */
inline double getDouble60_4F7330(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x60, sizeof(value));
    return value;
}

/** RE 0x547650: reads the double at +0x58, as movsd does. */
inline double getDouble58_547650(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x58, sizeof(value));
    return value;
}

/** RE 0x547630: reads the double at +0x48, as movsd does. */
inline double getDouble48_547630(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x48, sizeof(value));
    return value;
}

/** RE 0x4F9C20: writes the double at +0x58 and nothing else. */
inline void setDouble58_4F9C20(void* object, double value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x58, &value, sizeof(value));
}

/** RE 0x4F7340: writes the double at +0x60 and nothing else. */
inline void setDouble60_4F7340(void* object, double value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x60, &value, sizeof(value));
}

/** RE 0x52F8B0: writes the double at +0x18 and nothing else. */
inline void setDouble18_52F8B0(void* object, double value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x18, &value, sizeof(value));
}
/** RE 0x52F8F0: reads the double at +0x08, as movsd does. */
inline double getDouble08_52F8F0(const void* object) {
    double value = 0.0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x08, sizeof(value));
    return value;
}
/** RE 0x4F8D20: copies one dword from the second argument into the field at +0xA4. */
inline void copyDwordToA4_4F8D20(void* destination, const void* source) {
    std::uint32_t value = 0;
    std::memcpy(&value, source, sizeof(value));
    std::memcpy(static_cast<unsigned char*>(destination) + 0xA4, &value, sizeof(value));
}

/** RE 0x4F8D10: copies one dword from the second argument into the field at +0xA0. */
inline void copyDwordToA0_4F8D10(void* destination, const void* source) {
    std::uint32_t value = 0;
    std::memcpy(&value, source, sizeof(value));
    std::memcpy(static_cast<unsigned char*>(destination) + 0xA0, &value, sizeof(value));
}

/** RE 0x4F7600: returns the pointer held at +0x70, the tail call to 0x547610 being the identity. */
inline void* member70_4F7600(const void* object) {
    void* value = nullptr;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x70, sizeof(value));
    return value;
}
/** RE 0x4FC240: reads the 32-bit field at +0xA8 of the object the first member points at. */
inline std::uint32_t igetA8_4FC240(const void* object) {
    const unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::uint32_t value = 0;
    std::memcpy(&value, inner + 0xA8, sizeof(value));
    return value;
}

/** RE 0x4FC250: reads the 32-bit field at +0xAC of the object the first member points at. */
inline std::uint32_t igetAC_4FC250(const void* object) {
    const unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::uint32_t value = 0;
    std::memcpy(&value, inner + 0xAC, sizeof(value));
    return value;
}

/** RE 0x4FC2F0: reads the 8-bit field at +0x170 of the object the first member points at. */
inline std::uint8_t iget170_4FC2F0(const void* object) {
    const unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::uint8_t value = 0;
    std::memcpy(&value, inner + 0x170, sizeof(value));
    return value;
}

/** RE 0x4FC300: reads the 8-bit field at +0x1A0 of the object the first member points at. */
inline std::uint8_t iget1A0_4FC300(const void* object) {
    const unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::uint8_t value = 0;
    std::memcpy(&value, inner + 0x1A0, sizeof(value));
    return value;
}

/** RE 0x4FC260: reads the 8-bit field at +0xC8 of the object the first member points at. */
inline std::uint8_t igetC8_4FC260(const void* object) {
    const unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::uint8_t value = 0;
    std::memcpy(&value, inner + 0xC8, sizeof(value));
    return value;
}

/** RE 0x4FC2D0: reads the 8-bit field at +0xE8 of the object the first member points at. */
inline std::uint8_t igetE8_4FC2D0(const void* object) {
    const unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::uint8_t value = 0;
    std::memcpy(&value, inner + 0xE8, sizeof(value));
    return value;
}

/** RE 0x4FC320: reads the 8-bit field at +0x1E8 of the object the first member points at. */
inline std::uint8_t iget1E8_4FC320(const void* object) {
    const unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::uint8_t value = 0;
    std::memcpy(&value, inner + 0x1E8, sizeof(value));
    return value;
}

/** RE 0x4FC340: reads the 8-bit field at +0x1E9 of the object the first member points at. */
inline std::uint8_t iget1E9_4FC340(const void* object) {
    const unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::uint8_t value = 0;
    std::memcpy(&value, inner + 0x1E9, sizeof(value));
    return value;
}

/** RE 0x4FC290: reads the 8-bit field at +0xE0 of the object the first member points at. */
inline std::uint8_t igetE0_4FC290(const void* object) {
    const unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::uint8_t value = 0;
    std::memcpy(&value, inner + 0xE0, sizeof(value));
    return value;
}

/** RE 0x4FBE90: writes the 32-bit field at +0xA8 of the object the first member points at. */
inline void isetA8_4FBE90(void* object, std::uint32_t value) {
    unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::memcpy(inner + 0xA8, &value, sizeof(value));
}

/** RE 0x4FBEA0: writes the 32-bit field at +0xAC of the object the first member points at. */
inline void isetAC_4FBEA0(void* object, std::uint32_t value) {
    unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::memcpy(inner + 0xAC, &value, sizeof(value));
}

/** RE 0x4FC330: writes the 8-bit field at +0x1E8 of the object the first member points at. */
inline void iset1E8_4FC330(void* object, std::uint8_t value) {
    unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::memcpy(inner + 0x1E8, &value, sizeof(value));
}
/** RE 0x54CBC0: stores 0x0 in the 32-bit field at +0x00 and returns the object. */
inline void* init00_54CBC0(void* object) {
    const std::uint32_t value = 0x0;
    std::memcpy(static_cast<unsigned char*>(object) + 0x00, &value, sizeof(value));
    return object;
}

/** RE 0x4F7690: takes the member at +0x70 and returns the address of its +0x90. */
inline void* compose70_90_4F7690(void* object) {
    void* member = nullptr;
    std::memcpy(&member, object, sizeof(member));
    return static_cast<unsigned char*>(member) + 0x90;
}

/** RE 0x4F7660: takes the member at +0x70 and reads the double at its +0x58. */
inline double compose70_58_4F7660(const void* object) {
    const unsigned char* member = nullptr;
    std::memcpy(&member, object, sizeof(member));
    double value = 0.0;
    std::memcpy(&value, member + 0x58, sizeof(value));
    return value;
}

/** RE 0x4F7640: takes the member at +0x70 and reads the double at its +0x48. */
inline double compose70_48_4F7640(const void* object) {
    const unsigned char* member = nullptr;
    std::memcpy(&member, object, sizeof(member));
    double value = 0.0;
    std::memcpy(&value, member + 0x48, sizeof(value));
    return value;
}

/** RE 0x4F7680: takes the member at +0x70 and returns the address of its +0x68. */
inline void* compose70_68_4F7680(void* object) {
    void* member = nullptr;
    std::memcpy(&member, object, sizeof(member));
    return static_cast<unsigned char*>(member) + 0x68;
}
/** RE 0x8774E0: clears the qword at +0x00 and the byte at +0x08, returning nothing. */
inline void clear2_8774E0(void* object) {
    const std::uint64_t zero64 = 0;
    const std::uint8_t zero8 = 0;
    std::memcpy(object, &zero64, sizeof(zero64));
    std::memcpy(static_cast<unsigned char*>(object) + 0x08, &zero8, sizeof(zero8));
}
/** RE 0x4FBE70: writes the double at +0x98 of the object the first member points at. */
inline void isetDouble98_4FBE70(void* object, double value) {
    unsigned char* inner = nullptr;
    std::memcpy(&inner, object, sizeof(inner));
    std::memcpy(inner + 0x98, &value, sizeof(value));
}

/** RE 0x822590: true when the first member is not null, the setne on a compare against zero. */
inline bool notNullMember_822590(const void* object) {
    const void* member = nullptr;
    std::memcpy(&member, object, sizeof(member));
    return member != nullptr;
}

}  // namespace accessors
}  // namespace dll
}  // namespace lcns
