// lcns/field_accessors.hpp -- the three and four byte field accessors read out of the closures.
//
// Generated by re/g_add_accessors.py. Every name carries the RVA it was read from, because the field meanings
// are not recoverable from the code: these functions only move a value in or out. They are inline so that the
// build files do not have to change for each batch.
#pragma once

#include <cstdint>
#include <cstring>

namespace lcns {
namespace dll {
namespace accessors {

/** RE 0x52F920: reads the 32-bit field at +0x00. */
inline std::uint32_t getDword00_52F920(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x54CE90: reads the 32-bit field at +0x00. */
inline std::uint32_t getDword00_54CE90(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x54D110: writes the 8-bit field at +0x00 and nothing else. */
inline void setByte00_54D110(void* object, std::uint8_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x00, &value, sizeof(value));
}

/** RE 0x4F8C60: reads the 32-bit field at +0x60. */
inline std::uint32_t getDword60_4F8C60(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x60, sizeof(value));
    return value;
}

/** RE 0x4F8CC0: writes the 32-bit field at +0x64 and nothing else. */
inline void setDword64_4F8CC0(void* object, std::uint32_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x64, &value, sizeof(value));
}

/** RE 0x4F76C0: writes the 32-bit field at +0x6C and nothing else. */
inline void setDword6C_4F76C0(void* object, std::uint32_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x6C, &value, sizeof(value));
}

/** RE 0x4F7270: writes the 32-bit field at +0x28 and nothing else. */
inline void setDword28_4F7270(void* object, std::uint32_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x28, &value, sizeof(value));
}

/** RE 0x4F7290: writes the 8-bit field at +0x2C and nothing else. */
inline void setByte2C_4F7290(void* object, std::uint8_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x2C, &value, sizeof(value));
}

/** RE 0x4F7380: writes the 8-bit field at +0x6A and nothing else. */
inline void setByte6A_4F7380(void* object, std::uint8_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x6A, &value, sizeof(value));
}

/** RE 0x4F8360: reads the 32-bit field at +0x20. */
inline std::uint32_t getDword20_4F8360(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x20, sizeof(value));
    return value;
}

/** RE 0x4F8CD0: reads the 32-bit field at +0x64. */
inline std::uint32_t getDword64_4F8CD0(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x64, sizeof(value));
    return value;
}

/** RE 0x4F7060: reads the 32-bit field at +0x24. */
inline std::uint32_t getDword24_4F7060(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x24, sizeof(value));
    return value;
}

/** RE 0x4F76D0: reads the 32-bit field at +0x6C. */
inline std::uint32_t getDword6C_4F76D0(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x6C, sizeof(value));
    return value;
}

/** RE 0x52F8D0: writes the 8-bit field at +0x20 and nothing else. */
inline void setByte20_52F8D0(void* object, std::uint8_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x20, &value, sizeof(value));
}

/** RE 0x52F8E0: writes the 8-bit field at +0x21 and nothing else. */
inline void setByte21_52F8E0(void* object, std::uint8_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x21, &value, sizeof(value));
}
/** RE 0x54D100: reads the 8-bit value at +0x00. */
inline std::uint8_t getByte00_54D100(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x5C4CD0: reads the 8-bit value at +0x00. */
inline std::uint8_t getByte00_5C4CD0(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x4F7050: reads the 32-bit value at +0x24. */
inline std::uint32_t getDword24_4F7050(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x24, sizeof(value));
    return value;
}

/** RE 0x4FC1D0: reads the 64-bit value at +0x00. */
inline std::uint64_t getPtr00_4FC1D0(const void* object) {
    std::uint64_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x5FC7E0: reads the 64-bit value at +0x00. */
inline std::uint64_t getPtr00_5FC7E0(const void* object) {
    std::uint64_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x4FC200: reads the 64-bit value at +0x00. */
inline std::uint64_t getPtr00_4FC200(const void* object) {
    std::uint64_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x00, sizeof(value));
    return value;
}

/** RE 0x4F8C70: writes the 32-bit value at +0x60 and nothing else. */
inline void setDword60_4F8C70(void* object, std::uint32_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x60, &value, sizeof(value));
}

/** RE 0x4F76B0: writes the 32-bit value at +0x20 and nothing else. */
inline void setDword20_4F76B0(void* object, std::uint32_t value) {
    std::memcpy(static_cast<unsigned char*>(object) + 0x20, &value, sizeof(value));
}

/** RE 0x548390: reads the 32-bit value at +0x20. */
inline std::uint32_t getDword20_548390(const void* object) {
    std::uint32_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x20, sizeof(value));
    return value;
}
/** RE 0x52F930: reads the 8-bit value at +0x20. */
inline std::uint8_t getByte20_52F930(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x20, sizeof(value));
    return value;
}

/** RE 0x52F940: reads the 8-bit value at +0x21. */
inline std::uint8_t getByte21_52F940(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x21, sizeof(value));
    return value;
}

/** RE 0x4F7350: reads the 8-bit value at +0x68. */
inline std::uint8_t getByte68_4F7350(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x68, sizeof(value));
    return value;
}

/** RE 0x4F7360: reads the 8-bit value at +0x69. */
inline std::uint8_t getByte69_4F7360(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x69, sizeof(value));
    return value;
}

/** RE 0x4F73A0: reads the 8-bit value at +0x6A. */
inline std::uint8_t getByte6A_4F73A0(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x6A, sizeof(value));
    return value;
}

/** RE 0x5FBC70: reads the 8-bit value at +0x08. */
inline std::uint8_t getByte08_5FBC70(const void* object) {
    std::uint8_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x08, sizeof(value));
    return value;
}

/** RE 0x5C4CE0: reads the 64-bit value at +0x08. */
inline std::uint64_t getPtr08_5C4CE0(const void* object) {
    std::uint64_t value = 0;
    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x08, sizeof(value));
    return value;
}

/** RE 0x4F73C0: returns the address of the member at +0x70, not its value. */
inline void* addr70_4F73C0(void* object) {
    return static_cast<unsigned char*>(object) + 0x70;
}

/** RE 0x5C5F40: returns the address of the member at +0x18, not its value. */
inline void* addr18_5C5F40(void* object) {
    return static_cast<unsigned char*>(object) + 0x18;
}

/** RE 0x54D120: returns the address of the member at +0x08, not its value. */
inline void* addr08_54D120(void* object) {
    return static_cast<unsigned char*>(object) + 0x08;
}

/** RE 0x5C5F60: returns the address of the member at +0x18, not its value. */
inline void* addr18_5C5F60(void* object) {
    return static_cast<unsigned char*>(object) + 0x18;
}

/** RE 0x5483B0: returns the address of the member at +0x38, not its value. */
inline void* addr38_5483B0(void* object) {
    return static_cast<unsigned char*>(object) + 0x38;
}

/** RE 0x5483A0: returns the address of the member at +0x28, not its value. */
inline void* addr28_5483A0(void* object) {
    return static_cast<unsigned char*>(object) + 0x28;
}

/** RE 0x54CE60: copies one dword from the second argument to the first. */
inline void copyDword_54CE60(void* destination, const void* source) {
    std::uint32_t value = 0;
    std::memcpy(&value, source, sizeof(value));
    std::memcpy(destination, &value, sizeof(value));
}

/** RE 0x52F8A0: copies one dword from the second argument to the first. */
inline void copyDword_52F8A0(void* destination, const void* source) {
    std::uint32_t value = 0;
    std::memcpy(&value, source, sizeof(value));
    std::memcpy(destination, &value, sizeof(value));
}
}  // namespace accessors
}  // namespace dll
}  // namespace lcns
