// lcns/include/lcns/named_members.hpp -- the class members an ORACLE names, and nothing else.
//
// GENERATED by re/g_gen_named_members.py. **A field with no name does not belong in a class.** Every member below is named by an option
// key the module ANSWERS TO -- its own vocabulary -- paired with the offset its lookup result is stored into. **The MIPLIB benchmark
// names are excluded**: the module CONTAINS those strings and does not answer to them, which re/param_split.json records and a first
// version of this generator ignored, emitting `void* air03` as a member of Tiling::SqueezeMultiTiler.
//
// 24 classes, 202 named members, 51 distinct names. See lcns/docs/WHAT_IS_NORMAL_CPP.md.
#pragma once

#include <cstddef>
#include <cstdint>

namespace lcns {

/** Tiling::SqueezeMultiTiler -- vtable 0xA3D2D0. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x76E440 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct SqueezeMultiTilerMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x76E55F
    std::byte unplaced_0040[0x8]{};   // +0x40 .. +0x48: no name is known for these bytes
    std::uint64_t nb_iterations_first                          = {}; // +0x48, RE 0x76E56F
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x76E577
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x76E57F
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x76E587
    std::byte unplaced_0068[0x10]{};   // +0x68 .. +0x78: no name is known for these bytes
    std::uint64_t nb_iterations_before_partial_multi_fill_tiling = {}; // +0x78, RE 0x76E60C
    std::uint64_t enable_rectangle                             = {}; // +0x80, RE 0x76E65A
    std::uint32_t nb_iterations_before_rectangle_advance       = {}; // +0x88, RE 0x76E672
    std::byte unplaced_008C[0x4]{};   // +0x8C .. +0x90: no name is known for these bytes
    std::uint64_t nb_rectangle_advance_try                     = {}; // +0x90, RE 0x76E653
    std::byte unplaced_0098[0x28]{};   // +0x98 .. +0xC0: no name is known for these bytes
    std::uint64_t nb_iterations_before_tiling_evaluated        = {}; // +0xC0, RE 0x76EC5E
    std::byte unplaced_00C8[0x18]{};   // +0xC8 .. +0xE0: no name is known for these bytes
    double     nesting_offset_ratio                         = {}; // +0xE0, RE 0x76E7F4
    std::byte unplaced_00E4[0x4]{};   // +0xE4 .. +0xE8: no name is known for these bytes
    std::uint64_t nb_iterations_before_advanced_nesting        = {}; // +0xE8, RE 0x76E7FE
    std::uint64_t nb_iterations_before_small_rotation_nesting  = {}; // +0xF0, RE 0x76E7B6
    std::byte unplaced_00F8[0x8]{};   // +0xF8 .. +0x100: no name is known for these bytes
    std::uint64_t nesting_pow_boost                            = {}; // +0x100, RE 0x76E809
    std::uint64_t nesting_max_context_size                     = {}; // +0x108, RE 0x76E95C
    std::uint32_t nb_iterations_before_enlarge                 = {}; // +0x110, RE 0x76E814
    std::byte unplaced_0114[0x4]{};   // +0x114 .. +0x118: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop_2 = {}; // +0x118, RE 0x76E822  (oracle name: nb_iterations_before_rotate_compact_postop)
    std::uint64_t default_enlarge                              = {}; // +0x120, RE 0x76E7CB
    std::byte unplaced_0128[0x10]{};   // +0x128 .. +0x138: no name is known for these bytes
    std::uint32_t enable_beam                                  = {}; // +0x138, RE 0x76E849
    std::byte unplaced_013C[0x4]{};   // +0x13C .. +0x140: no name is known for these bytes
    double     beam_frequency_ratio                         = {}; // +0x140, RE 0x76E79B
    std::byte unplaced_0148[0x38]{};   // +0x148 .. +0x180: no name is known for these bytes
    std::uint64_t nb_iterations_before_beam_advanced           = {}; // +0x180, RE 0x76E982
};

/** Utils::LogSink -- vtable 0xA3BD40. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x199570 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct LogSinkMembers {
    std::byte unplaced_0008[0x14]{};   // +0x8 .. +0x1C: no name is known for these bytes
    std::uint16_t enable_last_compaction                       = {}; // +0x1C, RE 0x199A2A
    std::byte unplaced_001E[0x1A]{};   // +0x1E .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x1995A4
    std::byte unplaced_0040[0x10]{};   // +0x40 .. +0x50: no name is known for these bytes
    std::uint32_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x19969A
    std::byte unplaced_0054[0x4]{};   // +0x54 .. +0x58: no name is known for these bytes
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x1996B5
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x1996A1
    std::byte unplaced_0068[0x10]{};   // +0x68 .. +0x78: no name is known for these bytes
    std::uint64_t nb_iterations_before_partial_multi_fill_tiling = {}; // +0x78, RE 0x1995E2
    std::uint64_t enable_rectangle                             = {}; // +0x80, RE 0x199823
    std::uint64_t nb_iterations_before_rectangle_advance       = {}; // +0x88, RE 0x199C68
    std::byte unplaced_0090[0xB8]{};   // +0x90 .. +0x148: no name is known for these bytes
    double     beam_flip_frequency_ratio                    = {}; // +0x148, RE 0x1997FB
    std::uint64_t beam_width                                   = {}; // +0x150, RE 0x1995C1
    std::byte unplaced_0158[0x8]{};   // +0x158 .. +0x160: no name is known for these bytes
    std::uint64_t beam_buckets_per_part                        = {}; // +0x160, RE 0x1995D3
    std::uint64_t enable_filter                                = {}; // +0x168, RE 0x1995ED
    std::byte unplaced_0170[0x10]{};   // +0x170 .. +0x180: no name is known for these bytes
    std::uint64_t nb_iterations_before_beam_advanced           = {}; // +0x180, RE 0x1996CF
    std::byte unplaced_0188[0x8]{};   // +0x188 .. +0x190: no name is known for these bytes
    std::uint64_t nb_iterations_before_beam_expert             = {}; // +0x190, RE 0x199CFE
    std::byte unplaced_0198[0x10]{};   // +0x198 .. +0x1A8: no name is known for these bytes
    std::uint64_t beam_distinct_angle                          = {}; // +0x1A8, RE 0x19977D
    std::uint64_t nb_iterations_before_cut_nesting             = {}; // +0x1B0, RE 0x199788
    std::uint8_t cut_nesting_probabilty                       = {}; // +0x1B8, RE 0x199793
    std::byte unplaced_01B9[0x67]{};   // +0x1B9 .. +0x220: no name is known for these bytes
    double     boost_price_frequency                        = {}; // +0x220, RE 0x19980A
    double     linear_fill_frequency                        = {}; // +0x228, RE 0x1997D5
};

/** Tiling::WarpCanceller -- vtable 0xA3D160. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x4ED480 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct WarpCancellerMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x4ED842
    std::byte unplaced_0040[0x8]{};   // +0x40 .. +0x48: no name is known for these bytes
    std::uint64_t nb_iterations_first                          = {}; // +0x48, RE 0x4ED83D
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x4ED4E0
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x4ED84D
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x4ED859
    std::byte unplaced_0068[0x10]{};   // +0x68 .. +0x78: no name is known for these bytes
    std::uint64_t nb_iterations_before_partial_multi_fill_tiling = {}; // +0x78, RE 0x4EDBBA
    std::byte unplaced_0080[0x60]{};   // +0x80 .. +0xE0: no name is known for these bytes
    double     nesting_offset_ratio                         = {}; // +0xE0, RE 0x4ED9BB
    std::uint64_t nb_iterations_before_advanced_nesting        = {}; // +0xE8, RE 0x4ED9C7
    std::uint64_t nb_iterations_before_small_rotation_nesting  = {}; // +0xF0, RE 0x4ED9D6
    std::byte unplaced_00F8[0x8]{};   // +0xF8 .. +0x100: no name is known for these bytes
    std::uint64_t nesting_pow_boost                            = {}; // +0x100, RE 0x4EDA39
    std::uint64_t nesting_max_context_size                     = {}; // +0x108, RE 0x4EDA45
    std::uint64_t nb_iterations_before_enlarge                 = {}; // +0x110, RE 0x4EDA25
    std::byte unplaced_0118[0x8]{};   // +0x118 .. +0x120: no name is known for these bytes
    std::uint64_t default_enlarge                              = {}; // +0x120, RE 0x4ED6F2
};

/** Multi::SplitNode -- vtable 0xA3BB70. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x99910 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct SplitNodeMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x9994E
    std::byte unplaced_0040[0x8]{};   // +0x40 .. +0x48: no name is known for these bytes
    std::uint64_t nb_iterations_first                          = {}; // +0x48, RE 0x999A2
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x99A56
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x99A5B
};

/** Multi::TerminalNode -- vtable 0xA3B570. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x99360 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct TerminalNodeMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x993FD
    std::byte unplaced_0040[0x8]{};   // +0x40 .. +0x48: no name is known for these bytes
    std::uint64_t nb_iterations_first                          = {}; // +0x48, RE 0x99504
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x99509
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x9972D
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x994D8
    std::byte unplaced_0068[0x18]{};   // +0x68 .. +0x80: no name is known for these bytes
    std::uint64_t enable_rectangle                             = {}; // +0x80, RE 0x994B4
    std::uint64_t nb_iterations_before_rectangle_advance       = {}; // +0x88, RE 0x995F1
    std::byte unplaced_0090[0x88]{};   // +0x90 .. +0x118: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop_2 = {}; // +0x118, RE 0x99386  (oracle name: nb_iterations_before_rotate_compact_postop)
};

/** Engine::CloudEngine -- vtable 0xA3CED0. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x268A0 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct CloudEngineMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x2696D
    std::byte unplaced_0040[0x10]{};   // +0x40 .. +0x50: no name is known for these bytes
    std::uint8_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x26975
};

/** Multi::AdvancedStrategist -- vtable 0xA3B970. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x2EC50 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct AdvancedStrategistMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint8_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x2ECE8
    std::byte unplaced_0039[0xF]{};   // +0x39 .. +0x48: no name is known for these bytes
    std::uint64_t nb_iterations_first                          = {}; // +0x48, RE 0x2ED84
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x2ED49
    std::byte unplaced_0058[0x8]{};   // +0x58 .. +0x60: no name is known for these bytes
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x2EE13
    std::byte unplaced_0068[0x28]{};   // +0x68 .. +0x90: no name is known for these bytes
    std::uint64_t nb_rectangle_advance_try                     = {}; // +0x90, RE 0x2F01D
    std::byte unplaced_0098[0x2B6]{};   // +0x98 .. +0x34E: no name is known for these bytes
    std::uint8_t trace_dxf                                    = {}; // +0x34E, RE 0x2EC8E
};

/** Multi::LimitedNester -- vtable 0xA3B650. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x4AAD0 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct LimitedNesterMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x4AB03
    std::byte unplaced_0040[0x4]{};   // +0x40 .. +0x44: no name is known for these bytes
    std::uint8_t nb_strips_first                              = {}; // +0x44, RE 0x4AB12
};

/** Multi::NestingNester -- vtable 0xA3B690. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x342E0 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct NestingNesterMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint32_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x34335
};

/** Structure::ClusterObserver -- vtable 0xA53420. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x553100 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct ClusterObserverMembers {
    std::byte unplaced_0008[0x50]{};   // +0x8 .. +0x58: no name is known for these bytes
    std::uint8_t enable_flip                                  = {}; // +0x58, RE 0x553122
    std::byte unplaced_0059[0x3]{};   // +0x59 .. +0x5C: no name is known for these bytes
    std::uint32_t enable_oblique_pentagon_tiling               = {}; // +0x5C, RE 0x553126
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x55312D
};

/** Utils::Canceller -- vtable 0xA3BD70. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x68AB50 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct CancellerMembers {
    std::byte unplaced_0008[0x14]{};   // +0x8 .. +0x1C: no name is known for these bytes
    std::uint16_t enable_last_compaction                       = {}; // +0x1C, RE 0x68CBF6
    std::byte unplaced_001E[0x1A]{};   // +0x1E .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x68AC97
    std::byte unplaced_0040[0x8]{};   // +0x40 .. +0x48: no name is known for these bytes
    std::uint64_t nb_iterations_first                          = {}; // +0x48, RE 0x68AF27
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x68AC8A
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x68ACB1
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x68ACA4
    std::byte unplaced_0068[0x10]{};   // +0x68 .. +0x78: no name is known for these bytes
    std::uint64_t nb_iterations_before_partial_multi_fill_tiling = {}; // +0x78, RE 0x68BAC2
    std::uint64_t enable_rectangle                             = {}; // +0x80, RE 0x68AFC2
    std::uint64_t nb_iterations_before_rectangle_advance       = {}; // +0x88, RE 0x68ABBA
    std::uint64_t nb_rectangle_advance_try                     = {}; // +0x90, RE 0x68B027
    std::byte unplaced_0098[0x28]{};   // +0x98 .. +0xC0: no name is known for these bytes
    std::uint64_t nb_iterations_before_tiling_evaluated        = {}; // +0xC0, RE 0x68C790
    std::byte unplaced_00C8[0x10]{};   // +0xC8 .. +0xD8: no name is known for these bytes
    std::uint64_t enable_common_cut_filling                    = {}; // +0xD8, RE 0x68C7DD
    double     nesting_offset_ratio                         = {}; // +0xE0, RE 0x68C7FA
    std::byte unplaced_00E4[0x4]{};   // +0xE4 .. +0xE8: no name is known for these bytes
    std::uint64_t nb_iterations_before_advanced_nesting        = {}; // +0xE8, RE 0x68C807
    std::uint64_t nb_iterations_before_small_rotation_nesting  = {}; // +0xF0, RE 0x68AD12
    std::byte unplaced_00F8[0x8]{};   // +0xF8 .. +0x100: no name is known for these bytes
    std::uint64_t nesting_pow_boost                            = {}; // +0x100, RE 0x68AE38
    std::uint64_t nesting_max_context_size                     = {}; // +0x108, RE 0x68B0A6
    std::uint64_t nb_iterations_before_enlarge                 = {}; // +0x110, RE 0x68AF65
    std::uint64_t nb_iterations_before_rotate_compact_postop_2 = {}; // +0x118, RE 0x68B1D2  (oracle name: nb_iterations_before_rotate_compact_postop)
    std::uint64_t default_enlarge                              = {}; // +0x120, RE 0x68B8D4
    std::byte unplaced_0128[0x10]{};   // +0x128 .. +0x138: no name is known for these bytes
    std::uint64_t enable_beam                                  = {}; // +0x138, RE 0x68C114
    double     beam_frequency_ratio                         = {}; // +0x140, RE 0x68BB48
    double     beam_flip_frequency_ratio                    = {}; // +0x148, RE 0x68C253
    std::uint64_t beam_width                                   = {}; // +0x150, RE 0x68C318
    std::byte unplaced_0158[0x8]{};   // +0x158 .. +0x160: no name is known for these bytes
    std::uint64_t beam_buckets_per_part                        = {}; // +0x160, RE 0x68D1CA
    std::uint64_t enable_filter                                = {}; // +0x168, RE 0x68D25B
    std::byte unplaced_0170[0x20]{};   // +0x170 .. +0x190: no name is known for these bytes
    std::uint64_t nb_iterations_before_beam_expert             = {}; // +0x190, RE 0x68AC41
    std::byte unplaced_0198[0x48]{};   // +0x198 .. +0x1E0: no name is known for these bytes
    double     float_filler_reduction_ratio                 = {}; // +0x1E0, RE 0x68CE35
    std::byte unplaced_01E8[0x28]{};   // +0x1E8 .. +0x210: no name is known for these bytes
    double     combined_price_frequency                     = {}; // +0x210, RE 0x68D7F7
    std::byte unplaced_0218[0x18]{};   // +0x218 .. +0x230: no name is known for these bytes
    double     simple_fill_frequency                        = {}; // +0x230, RE 0x68D7CD
    std::byte unplaced_0238[0x38]{};   // +0x238 .. +0x270: no name is known for these bytes
    std::uint64_t mono_relaxed_max_bonus                       = {}; // +0x270, RE 0x68D71B
    std::byte unplaced_0278[0x38]{};   // +0x278 .. +0x2B0: no name is known for these bytes
    std::uint64_t min_cutting_cost_ratio                       = {}; // +0x2B0, RE 0x68AE30
    std::uint64_t use_old_evaluation_ratio                     = {}; // +0x2B8, RE 0x68AEA7
    std::uint64_t enable_multi_sheet                           = {}; // +0x2C0, RE 0x68AE66
    std::byte unplaced_02C8[0x10]{};   // +0x2C8 .. +0x2D8: no name is known for these bytes
    std::uint64_t enable_beautifier_multiplicity               = {}; // +0x2D8, RE 0x68AE18
    std::uint64_t enable_beautifier_common_cut                 = {}; // +0x2E0, RE 0x68ADE0
    std::byte unplaced_02E8[0x38]{};   // +0x2E8 .. +0x320: no name is known for these bytes
    std::uint64_t nb_iterations_before_free_parts              = {}; // +0x320, RE 0x68D28D
    std::byte unplaced_0328[0x8]{};   // +0x328 .. +0x330: no name is known for these bytes
    std::uint64_t use_multitorch_tiling                        = {}; // +0x330, RE 0x68D1D6
    std::uint64_t force_single_orientation_tiling              = {}; // +0x338, RE 0x68D23B
    std::uint64_t enable_multi_thread                          = {}; // +0x340, RE 0x68D200
};

/** Tiling::CompositePart -- vtable 0xA3D140. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x4DBA70 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct CompositePartMembers {
    std::byte unplaced_0008[0x70]{};   // +0x8 .. +0x78: no name is known for these bytes
    std::uint64_t nb_iterations_before_partial_multi_fill_tiling = {}; // +0x78, RE 0x4DBBB1
    std::uint64_t enable_rectangle                             = {}; // +0x80, RE 0x4DBBB9
    std::uint64_t nb_iterations_before_rectangle_advance       = {}; // +0x88, RE 0x4DBBC4
    std::byte unplaced_0090[0x48]{};   // +0x90 .. +0xD8: no name is known for these bytes
    std::uint64_t enable_common_cut_filling                    = {}; // +0xD8, RE 0x4DBA88
};

/** Multi::NoMixSheetSelector -- vtable 0xA3B9D0. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0xAFD60 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct NoMixSheetSelectorMembers {
    std::byte unplaced_0008[0x14]{};   // +0x8 .. +0x1C: no name is known for these bytes
    std::uint16_t enable_last_compaction                       = {}; // +0x1C, RE 0xAFE10
    std::byte unplaced_001E[0x1A]{};   // +0x1E .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0xAFF19
    std::byte unplaced_0040[0x10]{};   // +0x40 .. +0x50: no name is known for these bytes
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0xAFE39
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0xAFE9C
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0xAFE6B
    std::byte unplaced_0068[0x10]{};   // +0x68 .. +0x78: no name is known for these bytes
    std::uint64_t nb_iterations_before_partial_multi_fill_tiling = {}; // +0x78, RE 0xAFDF5
    std::uint64_t enable_rectangle                             = {}; // +0x80, RE 0xAFE03
};

/** Pack::RecursiveNester -- vtable 0xA3B460. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x162280 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct RecursiveNesterMembers {
    std::byte unplaced_0008[0x14]{};   // +0x8 .. +0x1C: no name is known for these bytes
    std::uint32_t enable_last_compaction                       = {}; // +0x1C, RE 0x1622C4
    std::byte unplaced_0020[0x18]{};   // +0x20 .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x162585
    std::byte unplaced_0040[0x10]{};   // +0x40 .. +0x50: no name is known for these bytes
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x1623A9
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x16241F
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x1623EE
    std::byte unplaced_0068[0x10]{};   // +0x68 .. +0x78: no name is known for these bytes
    std::uint64_t nb_iterations_before_partial_multi_fill_tiling = {}; // +0x78, RE 0x1623AE
    std::uint64_t enable_rectangle                             = {}; // +0x80, RE 0x16237C
    std::byte unplaced_0088[0x8]{};   // +0x88 .. +0x90: no name is known for these bytes
    std::uint64_t nb_rectangle_advance_try                     = {}; // +0x90, RE 0x162303
};

/** Tiling::Part -- vtable 0xA3D420. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x4DB0D0 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct PartMembers {
    std::byte unplaced_0008[0x50]{};   // +0x8 .. +0x58: no name is known for these bytes
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x4DB10B
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x4DB113
};

/** Tiling::QuantityEvaluator -- vtable 0xA3D270. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x4E81B0 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct QuantityEvaluatorMembers {
    std::byte unplaced_0008[0x14]{};   // +0x8 .. +0x1C: no name is known for these bytes
    std::uint16_t enable_last_compaction                       = {}; // +0x1C, RE 0x4E823B
    std::byte unplaced_001E[0x1A]{};   // +0x1E .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x4E832C
    std::byte unplaced_0040[0x10]{};   // +0x40 .. +0x50: no name is known for these bytes
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x4E8261
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x4E82B6
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x4E828F
    std::byte unplaced_0068[0x10]{};   // +0x68 .. +0x78: no name is known for these bytes
    std::uint64_t nb_iterations_before_partial_multi_fill_tiling = {}; // +0x78, RE 0x4E820D
    std::uint64_t enable_rectangle                             = {}; // +0x80, RE 0x4E822E
};

/** Engine::NestingEngine -- vtable 0xA3CFA0. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x23E70 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct NestingEngineMembers {
    std::byte unplaced_0008[0x14]{};   // +0x8 .. +0x1C: no name is known for these bytes
    std::uint8_t enable_last_compaction                       = {}; // +0x1C, RE 0x23ED2
    std::uint8_t enable_last_postop                           = {}; // +0x1D, RE 0x23ED9
    std::byte unplaced_001E[0x6]{};   // +0x1E .. +0x24: no name is known for these bytes
    std::uint32_t nb_iterations_before_postop                  = {}; // +0x24, RE 0x23EE5
    std::byte unplaced_0028[0x10]{};   // +0x28 .. +0x38: no name is known for these bytes
    std::uint32_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x23EEB
    std::byte unplaced_003C[0xC]{};   // +0x3C .. +0x48: no name is known for these bytes
    std::uint64_t nb_iterations_first                          = {}; // +0x48, RE 0x23EFE
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x23F09
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x23F20
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x23F65
};

/** Engine::CompositeObserver -- vtable 0xA3D060. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x8D4500 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct CompositeObserverMembers {
    std::byte unplaced_0008[0x58]{};   // +0x8 .. +0x60: no name is known for these bytes
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x8D4693
};

/** Multi::CompactCanceller -- vtable 0xA3B870. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x68A6E0 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct CompactCancellerMembers {
    std::byte unplaced_0008[0xB8]{};   // +0x8 .. +0xC0: no name is known for these bytes
    std::uint64_t nb_iterations_before_tiling_evaluated        = {}; // +0xC0, RE 0x68A831
    std::byte unplaced_00C8[0x18]{};   // +0xC8 .. +0xE0: no name is known for these bytes
    double     nesting_offset_ratio                         = {}; // +0xE0, RE 0x68A7F8
    std::uint64_t nb_iterations_before_advanced_nesting        = {}; // +0xE8, RE 0x68A800
};

/** Multi::PartUpdaterLimiter -- vtable 0xA3BA00. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x695C70 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct PartUpdaterLimiterMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x695C89
    std::byte unplaced_0040[0x8]{};   // +0x40 .. +0x48: no name is known for these bytes
    std::uint64_t nb_iterations_first                          = {}; // +0x48, RE 0x695CCD
    std::uint8_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x695CBA
};

/** Multi::RectangleNester -- vtable 0xA3B800. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x77440 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct RectangleNesterMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x774C9
    std::byte unplaced_0040[0x4]{};   // +0x40 .. +0x44: no name is known for these bytes
    std::uint32_t nb_strips_first                              = {}; // +0x44, RE 0x774D9
    std::uint32_t nb_iterations_first                          = {}; // +0x48, RE 0x774E0
    std::byte unplaced_004C[0x4]{};   // +0x4C .. +0x50: no name is known for these bytes
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x776CB
    std::byte unplaced_0058[0x8]{};   // +0x58 .. +0x60: no name is known for these bytes
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x77562
};

/** Multi::WrapObserver -- vtable 0xA3B5E0. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x83DC0 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct WrapObserverMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x841E6
    std::byte unplaced_0040[0x8]{};   // +0x40 .. +0x48: no name is known for these bytes
    std::uint64_t nb_iterations_first                          = {}; // +0x48, RE 0x83EA0
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x83FFE
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x8402F
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x83E2F
    std::byte unplaced_0068[0x88]{};   // +0x68 .. +0xF0: no name is known for these bytes
    std::uint8_t nb_iterations_before_small_rotation_nesting  = {}; // +0xF0, RE 0x83F07
    std::byte unplaced_00F1[0xF]{};   // +0xF1 .. +0x100: no name is known for these bytes
    std::uint64_t nesting_pow_boost                            = {}; // +0x100, RE 0x83F40
    std::byte unplaced_0108[0x8]{};   // +0x108 .. +0x110: no name is known for these bytes
    std::uint64_t nb_iterations_before_enlarge                 = {}; // +0x110, RE 0x83F0F
    std::uint64_t nb_iterations_before_rotate_compact_postop_2 = {}; // +0x118, RE 0x83FEF  (oracle name: nb_iterations_before_rotate_compact_postop)
    std::uint64_t default_enlarge                              = {}; // +0x120, RE 0x84003
    std::byte unplaced_0128[0x210]{};   // +0x128 .. +0x338: no name is known for these bytes
    std::uint8_t force_single_orientation_tiling              = {}; // +0x338, RE 0x83EDC
    std::uint8_t force_single_orientation_asit                = {}; // +0x339, RE 0x83EEB
};

/** Structure::Observer -- vtable 0xA53550. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x83DC0 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct ObserverMembers {
    std::byte unplaced_0008[0x30]{};   // +0x8 .. +0x38: no name is known for these bytes
    std::uint64_t nb_iterations_before_rotate_compact_postop   = {}; // +0x38, RE 0x841E6
    std::byte unplaced_0040[0x8]{};   // +0x40 .. +0x48: no name is known for these bytes
    std::uint64_t nb_iterations_first                          = {}; // +0x48, RE 0x83EA0
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x83FFE
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x8402F
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x83E2F
    std::byte unplaced_0068[0x88]{};   // +0x68 .. +0xF0: no name is known for these bytes
    std::uint8_t nb_iterations_before_small_rotation_nesting  = {}; // +0xF0, RE 0x83F07
    std::byte unplaced_00F1[0xF]{};   // +0xF1 .. +0x100: no name is known for these bytes
    std::uint64_t nesting_pow_boost                            = {}; // +0x100, RE 0x83F40
    std::byte unplaced_0108[0x8]{};   // +0x108 .. +0x110: no name is known for these bytes
    std::uint64_t nb_iterations_before_enlarge                 = {}; // +0x110, RE 0x83F0F
    std::uint64_t nb_iterations_before_rotate_compact_postop_2 = {}; // +0x118, RE 0x83FEF  (oracle name: nb_iterations_before_rotate_compact_postop)
    std::uint64_t default_enlarge                              = {}; // +0x120, RE 0x84003
    std::byte unplaced_0128[0x210]{};   // +0x128 .. +0x338: no name is known for these bytes
    std::uint8_t force_single_orientation_tiling              = {}; // +0x338, RE 0x83EDC
    std::uint8_t force_single_orientation_asit                = {}; // +0x339, RE 0x83EEB
};

/** Utils::BadResponseException -- vtable 0xA3BC80. ONLY THE MEMBERS AN ORACLE NAMES.
 *
 *  A field with no name does not belong in a class: `at_0010` is a position wearing a name-shaped label. Every other offset
 *  this class's constructor 0x2B660 writes is a named unplaced region, and the class waits for a name rather than inventing one.
 */
struct BadResponseExceptionMembers {
    std::byte unplaced_0008[0x40]{};   // +0x8 .. +0x48: no name is known for these bytes
    std::uint64_t nb_iterations_first                          = {}; // +0x48, RE 0x2B95B
    std::uint64_t nb_strips_filling_advanced                   = {}; // +0x50, RE 0x2B6F3
    std::uint64_t enable_flip                                  = {}; // +0x58, RE 0x2B751
    std::uint64_t nb_iterations_before_tiling                  = {}; // +0x60, RE 0x2B689
    std::byte unplaced_0068[0x18]{};   // +0x68 .. +0x80: no name is known for these bytes
    std::uint64_t enable_rectangle                             = {}; // +0x80, RE 0x2B71A
    std::byte unplaced_0088[0x8]{};   // +0x88 .. +0x90: no name is known for these bytes
    std::uint64_t nb_rectangle_advance_try                     = {}; // +0x90, RE 0x2B924
    std::byte unplaced_0098[0x28]{};   // +0x98 .. +0xC0: no name is known for these bytes
    std::uint64_t nb_iterations_before_tiling_evaluated        = {}; // +0xC0, RE 0x2B91C
    std::byte unplaced_00C8[0x10]{};   // +0xC8 .. +0xD8: no name is known for these bytes
    std::uint64_t enable_common_cut_filling                    = {}; // +0xD8, RE 0x2B809
    std::byte unplaced_00E0[0x20]{};   // +0xE0 .. +0x100: no name is known for these bytes
    std::uint64_t nesting_pow_boost                            = {}; // +0x100, RE 0x2B70C
    std::uint64_t nesting_max_context_size                     = {}; // +0x108, RE 0x2B726
    std::uint64_t nb_iterations_before_enlarge                 = {}; // +0x110, RE 0x2B734
};

}  // namespace lcns
