// lcns/include/lcns/option_keys.hpp -- the nesting engine's option names, each confirmed by a store.
//
// GENERATED by re/g_gen_option_keys.py from re/param_split.json. Do not edit by hand.
//
// A name is here when an identifier-like string precedes a call to RE 0x82A3E0 AND the lookup's result is stored into a field of an
// object. The second condition is the one that matters: a `lea` of a rip-relative string precedes the lookup whether or not the string is
// a parameter, which is how an earlier count came to include MIPLIB benchmark names -- air03, bell3a, danoint, egout -- as if they were
// options.
//
// TWO SOURCES CONFIRM 54 OF THEM. The findings archive's option-key table was built by reading a rodata range; this list is built
// by following call sites and checking the store. All 54 of the archive's names are here, and the remaining 54 are confirmed
// by the store test alone, which is a weaker but still mechanical witness.
//
// 108 names in all. The archive's table is the smaller because a rodata range does not contain every option string.
#pragma once

#include <cstddef>

namespace lcns {

/** One option name with how often it is looked up and how often the result is stored.
 *
 *  `lookups` counts every site that loads the name; `stores` counts the sites whose result reaches a field. A name with lookups greater
 *  than stores is loaded at sites that do not store -- which happens when a parser reads an option to TEST it and writes elsewhere.
 */
struct OptionKey {
    const char* name;
    unsigned lookups;
    unsigned stores;
};

inline const OptionKey* optionKeys(std::size_t& count) {
    static const OptionKey table[] = {
        {"adaptative_price_max_random", 1, 1},
        {"beam_advanced_width", 1, 1},
        {"beam_buckets_per_part", 1, 1},
        {"beam_distinct_angle", 1, 1},
        {"beam_expert_width", 1, 1},
        {"beam_flip_frequency_ratio", 1, 1},
        {"beam_frequency_ratio", 1, 1},
        {"beam_width", 1, 1},
        {"boost_price_frequency", 1, 1},
        {"boost_price_max_random", 1, 1},
        {"combined_price_frequency", 1, 1},
        {"cut_nesting_probabilty", 1, 1},
        {"database_relax_every", 1, 1},
        {"default_enlarge", 1, 1},
        {"detect_overlap", 2, 1},
        {"enable_beam", 1, 1},
        {"enable_beautifier", 1, 1},
        {"enable_beautifier_common_cut", 1, 1},
        {"enable_beautifier_floating", 1, 1},
        {"enable_beautifier_improve_common_cut", 1, 1},
        {"enable_beautifier_intermediate", 1, 1},
        {"enable_beautifier_multiplicity", 1, 1},
        {"enable_beautifier_optimizer", 1, 1},
        {"enable_beautifier_reorganizer", 1, 1},
        {"enable_best_float_filler", 1, 1},
        {"enable_common_cut_filling", 1, 1},
        {"enable_common_cut_nesting", 1, 1},
        {"enable_common_cut_relax_objective", 1, 1},
        {"enable_common_cut_repair", 1, 1},
        {"enable_common_cut_tiling", 1, 1},
        {"enable_composite_tiling", 1, 1},
        {"enable_database", 1, 1},
        {"enable_database_float_filler", 1, 1},
        {"enable_enlarge_and_postop", 1, 1},
        {"enable_filter", 1, 1},
        {"enable_flip", 1, 1},
        {"enable_last_compaction", 1, 1},
        {"enable_last_postop", 1, 1},
        {"enable_multi_sheet", 1, 1},
        {"enable_multi_thread", 1, 1},
        {"enable_nesting_boost", 1, 1},
        {"enable_oblique_pentagon_tiling", 1, 1},
        {"enable_oblique_tiling", 1, 1},
        {"enable_pentagon_tiling", 1, 1},
        {"enable_rectangle", 1, 1},
        {"enable_recursive_tiling", 1, 1},
        {"enable_rotate_compact_postop", 3, 1},
        {"enable_tiling", 1, 1},
        {"float_filler_reduction_ratio", 1, 1},
        {"force_nb_max_active_parts", 1, 1},
        {"force_rectangle", 1, 1},
        {"force_single_orientation_asit", 1, 1},
        {"force_single_orientation_tiling", 1, 1},
        {"limited_intermediate", 1, 1},
        {"linear_fill_frequency", 1, 1},
        {"linear_price_frequency", 1, 1},
        {"max_cutting_cost_ratio", 1, 1},
        {"max_dual_ratio", 1, 1},
        {"min_cutting_cost_ratio", 1, 1},
        {"mono_relaxed_frequency", 1, 1},
        {"mono_relaxed_max_bonus", 1, 1},
        {"nb_iterations_before_advanced_nesting", 1, 1},
        {"nb_iterations_before_beam_advanced", 1, 1},
        {"nb_iterations_before_beam_expert", 1, 1},
        {"nb_iterations_before_beautifier_advanced", 1, 1},
        {"nb_iterations_before_cut_nesting", 1, 1},
        {"nb_iterations_before_enlarge", 1, 1},
        {"nb_iterations_before_enlarge_tiling", 1, 1},
        {"nb_iterations_before_expert_nesting", 1, 1},
        {"nb_iterations_before_float_filler", 1, 1},
        {"nb_iterations_before_free_parts", 1, 1},
        {"nb_iterations_before_intermediate_beautifier", 1, 1},
        {"nb_iterations_before_partial_multi_fill_tiling", 1, 1},
        {"nb_iterations_before_postop", 1, 1},
        {"nb_iterations_before_rectangle_advance", 1, 1},
        {"nb_iterations_before_rectangle_dual", 1, 1},
        {"nb_iterations_before_relaxed_mono", 1, 1},
        {"nb_iterations_before_rotate_compact_postop", 3, 2},
        {"nb_iterations_before_small_rotation_nesting", 1, 1},
        {"nb_iterations_before_tiling", 1, 1},
        {"nb_iterations_before_tiling_evaluated", 1, 1},
        {"nb_iterations_first", 1, 1},
        {"nb_max_nested_parts_float_filler", 1, 1},
        {"nb_max_threads", 1, 1},
        {"nb_rectangle_advance_try", 1, 1},
        {"nb_rectangle_try", 1, 1},
        {"nb_strips_default", 1, 1},
        {"nb_strips_filling_advanced", 1, 1},
        {"nb_strips_first", 1, 1},
        {"nesting_max_context_size", 1, 1},
        {"nesting_offset_ratio", 1, 1},
        {"nesting_pow_boost", 1, 1},
        {"per_worker_database", 1, 1},
        {"random_price_frequency", 1, 1},
        {"simple_fill_frequency", 1, 1},
        {"stable_results", 1, 1},
        {"stdin", 3, 2},
        {"stdout", 1, 1},
        {"tooling_with_rectangle", 1, 1},
        {"trace_best_solution", 1, 1},
        {"trace_dxf", 1, 1},
        {"trace_nesting", 1, 1},
        {"trace_solution", 1, 1},
        {"try_fill_free_parts", 1, 1},
        {"use_clusters", 1, 1},
        {"use_multitorch_tiling", 1, 1},
        {"use_old_evaluation_ratio", 1, 1},
        {"verbose", 1, 1},
    };
    count = sizeof(table) / sizeof(table[0]);
    return table;
}

/** The count of names confirmed by BOTH the archive and the store test. */
constexpr std::size_t kOptionKeysConfirmedTwice = 54;
/** And the total. */
constexpr std::size_t kOptionKeyCount = 108;

}  // namespace lcns
