#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the C++ ordinal/name table for the recovered liblcns.dll export surface.

Input : ..\\re\\exports_table.json   (produced by re\\18_final_names.py / 27_final_names2.py)
Output: ..\\include\\lcns\\detail\\api_table.inc

The real DLL exports 168 unique functions BY ORDINAL ONLY (NumberOfNames == 0) and every
function occupies TWO adjacent ordinals, so the runtime binding must be ordinal based.

Run from anywhere:
    python tools/gen_api.py
"""
from __future__ import annotations
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC_JSON = os.path.join(ROOT, os.pardir, "re", "exports_table.json")
OUT = os.path.join(ROOT, "include", "lcns", "detail", "api_table.inc")

# Functions recovered from the dbg::symlog entry label -> HIGH confidence.
# Functions without a tracer label -> only behaviourally identified -> MEDIUM/LOW.
FALLBACK_NAMES = {
    0x16CB0: "AddPartVariantUserString",
    0x16CF0: "GetPartVariantUserString",
    0xAFE0: "SetGlobalFlagFromInt",
    0x1A7D0: "SheetAddRectangularRestrictedZone",
    0xB000: "SetOrderDoubleAndFlag",
    0xAFF0: "SetOrderFlag",
}


def cstr(s):
    if s is None:
        return "nullptr"
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    with open(SRC_JSON, encoding="utf-8") as fh:
        rows = json.load(fh)

    rows.sort(key=lambda r: r["ords"][0])
    lines = []
    A = lines.append
    A("// AUTO-GENERATED by tools/gen_api.py -- DO NOT EDIT BY HAND.")
    A("// Source: re/exports_table.json (reverse engineering of libcns_dump_64.dll)")
    A("//")
    A("// confidence: 2 = name recovered from the dbg::symlog entry label (high),")
    A("//             1 = name inferred from behaviour (medium),")
    A("//             0 = unknown")
    A("")
    A("// clang-format off")
    for r in rows:
        rva = r["rva"]
        name = r["name"] or FALLBACK_NAMES.get(rva)
        conf = 2 if r.get("name") else (1 if name else 0)
        if not name:
            name = "sub_%05X" % rva
        ords = r["ords"]
        ord0 = ords[0]
        ord1 = ords[-1] if len(ords) > 1 else -1
        A(
            "LCNS_EXPORT_ROW(%s, %d, %d, 0x%05X, %d, %s, %s, %d)"
            % (
                name,
                ord0,
                ord1,
                rva,
                r["size"],
                cstr(r.get("label")),
                cstr((r.get("alias") or [None])[0]),
                conf,
            )
        )
    A("// clang-format on")
    A("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))

    known = sum(1 for r in rows if r.get("name"))
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    print("  rows      : %d" % len(rows))
    print("  named     : %d (%.1f%%)" % (known, 100.0 * known / len(rows)))
    print("  ordinals  : %d..%d" % (rows[0]["ords"][0], rows[-1]["ords"][-1]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
