# -*- coding: utf-8 -*-
"""Generate the field accessor header from the accessors read out of the closures, and test them.

The deepest layer of the LaunchLocalComputation closure turned out to be, at last, real domain code: three and four byte
functions that read or write one field. Read in round 512:

    0x52F920  mov eax, [rcx]        ; 32-bit getter at +0x00
    0x54CE90  mov eax, [rcx]        ; 32-bit getter at +0x00, another object
    0x54D110  mov [rcx], dl         ; byte setter at +0x00
    0x4F8C60  mov eax, [rcx+0x60]   ; 32-bit getter at +0x60
    0x4F8CC0  mov [rcx+0x64], edx   ; 32-bit setter at +0x64
    0x4F76C0  mov [rcx+0x6C], edx   ; 32-bit setter at +0x6C
    0x4F7270  mov [rcx+0x28], edx   ; 32-bit setter at +0x28
    0x4F7290  mov [rcx+0x2C], dl    ; byte setter at +0x2C

and seven functions that are nothing but `xor eax, eax ; ret`, which are default overrides returning zero:

    0xB5D60, 0x6FC810, 0xD5970, 0xD59A0 and three more of the same shape

The accessors are generated rather than hand written so that the offset, the width and the RVA of each one travel
together, and so that adding the next batch is a line in the table below. They are inline in a header, which keeps the
build files untouched. Each name carries its RVA, because the log labels do not tell us what the fields mean and inventing
a meaning would be a guess.
"""
import io
import os

ROOT = r"D:\Nesting\nestfab"
HDR = os.path.join(ROOT, "lcns", "include", "lcns", "field_accessors.hpp")
TEST = os.path.join(ROOT, "lcns", "tests", "test_boxacc.cpp")
TOOLCHAIN = os.path.join(ROOT, "re", "g_toolchain.py")

# (name, rva, access, offset, width)
ACCESSORS = [
    ("getDword00_52F920", 0x52F920, "get", 0x00, 4),
    ("getDword00_54CE90", 0x54CE90, "get", 0x00, 4),
    ("setByte00_54D110", 0x54D110, "set", 0x00, 1),
    ("getDword60_4F8C60", 0x4F8C60, "get", 0x60, 4),
    ("setDword64_4F8CC0", 0x4F8CC0, "set", 0x64, 4),
    ("setDword6C_4F76C0", 0x4F76C0, "set", 0x6C, 4),
    ("setDword28_4F7270", 0x4F7270, "set", 0x28, 4),
    ("setByte2C_4F7290", 0x4F7290, "set", 0x2C, 1),
]

DEFAULT_FALSE = [0xB5D60, 0x6FC810, 0xD5970, 0xD59A0]


def header_text():
    lines = []
    lines.append("// lcns/field_accessors.hpp -- the three and four byte field accessors read out of the closures.")
    lines.append("//")
    lines.append("// Generated by re/g_add_accessors.py. Every name carries the RVA it was read from, because the field meanings")
    lines.append("// are not recoverable from the code: these functions only move a value in or out. They are inline so that the")
    lines.append("// build files do not have to change for each batch.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("#include <cstring>")
    lines.append("")
    lines.append("namespace lcns {")
    lines.append("namespace dll {")
    lines.append("namespace accessors {")
    lines.append("")
    for name, rva, access, offset, width in ACCESSORS:
        if access == "get":
            lines.append("/** RE 0x%X: reads the %d-bit field at +0x%02X. */" % (rva, width * 8, offset))
            lines.append("inline std::uint%d_t %s(const void* object) {" % (width * 8, name))
            lines.append("    std::uint%d_t value = 0;" % (width * 8))
            lines.append("    std::memcpy(&value, static_cast<const unsigned char*>(object) + 0x%02X, sizeof(value));" % offset)
            lines.append("    return value;")
            lines.append("}")
        else:
            lines.append("/** RE 0x%X: writes the %d-bit field at +0x%02X and nothing else. */" % (rva, width * 8, offset))
            lines.append("inline void %s(void* object, std::uint%d_t value) {" % (name, width * 8))
            lines.append("    std::memcpy(static_cast<unsigned char*>(object) + 0x%02X, &value, sizeof(value));" % offset)
            lines.append("}")
        lines.append("")
    lines.append("}  // namespace accessors")
    lines.append("}  // namespace dll")
    lines.append("}  // namespace lcns")
    lines.append("")
    return "\n".join(lines)


def test_text():
    lines = []
    lines.append("    // ------------------- the field accessors, each against its own offset and width")
    lines.append("    {")
    lines.append("        // A large noisy buffer, so writing the wrong offset or the wrong width shows up immediately.")
    lines.append("        unsigned char object[0x80];")
    lines.append("        std::memset(object, 0xA5, sizeof(object));")
    for name, rva, access, offset, width in ACCESSORS:
        if access == "set":
            lines.append("        lcns::dll::accessors::%s(object, 0x%02X);   // RE 0x%X" % (name, (0x5A if width == 1 else 0x12345678), rva))
            lines.append("        {")
            lines.append("            std::uint%d_t got = 0;" % (width * 8))
            lines.append("            std::memcpy(&got, object + 0x%02X, sizeof(got));" % offset)
            lines.append("            CHECK(got == 0x%02X);" % (0x5A if width == 1 else 0x12345678))
            lines.append("        }")
        else:
            lines.append("        {")
            lines.append("            const std::uint%d_t put = 0x%02X;" % (width * 8, (0x5A if width == 1 else 0x12345678)))
            lines.append("            std::memcpy(object + 0x%02X, &put, sizeof(put));" % offset)
            lines.append("            CHECK(lcns::dll::accessors::%s(object) == put);   // RE 0x%X" % (name, rva))
            lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append('    return check::finish("boxacc");')
    return "\n".join(lines)


def main():
    io.open(HDR, "w", encoding="utf-8", newline="\n").write(header_text())
    print("field_accessors.hpp written with %d accessors" % len(ACCESSORS))

    t = io.open(TEST, encoding="utf-8", newline="").read().replace("\r\n", "\n")
    anchor = '    return check::finish("boxacc");'
    assert anchor in t, "the boxacc finish anchor is missing"
    t = t.replace(anchor, test_text(), 1)
    if '#include "lcns/field_accessors.hpp"' not in t:
        first = t.find("#include")
        assert first >= 0
        eol = t.find("\n", first)
        t = t[:eol + 1] + '#include "lcns/field_accessors.hpp"\n' + t[eol + 1:]
        print("test_boxacc.cpp   accessor header included")
    io.open(TEST, "w", encoding="utf-8", newline="\n").write(t)
    print("test_boxacc.cpp   accessor checks added")

    # the zero returning stubs are default overrides, not domain functions
    s = io.open(TOOLCHAIN, encoding="utf-8", newline="").read().replace("\r\n", "\n")
    a = "    0x877AD0,  # destructor thunk for the same family as 0x875FD0"
    assert a in s, "the boilerplate anchor was not found"
    add = [a]
    for rva in DEFAULT_FALSE:
        add.append("    0x%X,  # xor eax, eax ; ret -- a default override returning zero" % rva)
    io.open(TOOLCHAIN, "w", encoding="utf-8", newline="\n").write(s.replace(a, "\n".join(add), 1))
    print("g_toolchain.py    %d default overrides classified" % len(DEFAULT_FALSE))
    print("")
    print("done")


if __name__ == "__main__":
    main()
