# -*- coding: utf-8 -*-
"""The dependency closure of every unimplemented export, and the order to work in.

This is the map the rest of the work is scheduled from. For each unimplemented export it walks the call and jump edges
transitively, in the profile's own function set only, and keeps the functions that are neither already implemented nor
boilerplate nor toolchain nor diagnostic. What is left is the real domain code standing between the export and a complete
implementation.

For every such function it reports:

  * its size, which bounds the reading cost;
  * how many unimplemented exports need it, which is the leverage: a function needed by twenty exports is worth twenty
    times one needed by a single export;
  * its depth, meaning the fewest edges from any export, so the deepest leaves can be done first and unblock the rest;
  * how many functions it itself needs, so a leaf with no domain dependencies can be implemented immediately.

It also lists the exports whose closure is already empty, which are implementable right now with no further reading, and
writes the whole thing to re/WORKLIST.md so it survives the conversation.
"""
import io
import json
import os
import sys
from collections import deque

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import g_leverage as L          # noqa: E402
import g_toolchain as T         # noqa: E402
from lib import disasm, load_prof  # noqa: E402


def callees(addr, profile):
    """Every call or jmp target in this function, restricted to real function starts."""
    out = []
    size = (profile.get(addr) or {}).get("size")
    for ins in disasm(addr):
        if size and ins.address >= addr + size:
            break
        if ins.mnemonic not in ("call", "jmp"):
            continue
        m = L.re.search(r"0x([0-9a-f]+)", ins.op_str)
        if not m:
            continue
        t = int(m.group(1), 16)
        if t == addr:
            continue
        out.append(t)
    return out


def is_domain(addr, profile, kinds):
    if addr in L.VERIFIED or addr in T.BOILERPLATE:
        return False
    if addr not in profile:
        return False
    if addr not in kinds:
        k = T.kind(addr, profile)
        kinds[addr] = k if k is not None else "unknown"
    return kinds[addr] == "domain"


def main():
    profile = load_prof()
    kinds = {}
    done = L.forwarded_ordinals()
    table = json.loads(io.open(os.path.join(L.ROOT, "re", "exports_table.json"), encoding="utf-8").read())

    exports = []
    for e in table:
        ord0 = (e.get("ords") or [0])[0]
        if ord0 in done:
            continue
        exports.append(((e.get("name") or ("sub_%05X" % e["rva"])), ord0, e["rva"], e["size"]))

    closure = {}
    depth = {}
    ready_now = []
    for name, ord0, rva, size in exports:
        seen = {}
        queue = deque()
        for t in callees(rva, profile):
            if is_domain(t, profile, kinds):
                queue.append((t, 1))
        while queue:
            addr, d = queue.popleft()
            if addr in seen and seen[addr] <= d:
                continue
            seen[addr] = d
            for t in callees(addr, profile):
                if is_domain(t, profile, kinds):
                    queue.append((t, d + 1))
        closure[(name, ord0)] = seen
        if not seen:
            ready_now.append((name, ord0, rva, size))
        for addr, d in seen.items():
            if addr not in depth or d < depth[addr]:
                depth[addr] = d

    needers = {}
    for (name, ord0), seen in closure.items():
        for addr in seen:
            needers.setdefault(addr, []).append(ord0)

    rows = []
    for addr in depth:
        size = (profile.get(addr) or {}).get("size")
        own = sum(1 for t in callees(addr, profile) if is_domain(t, profile, kinds))
        rows.append((len(needers[addr]), size or 0, depth[addr], own, addr))
    rows.sort(key=lambda r: (-r[0], r[1]))

    lines = []
    lines.append("# The dependency closure of the unimplemented exports")
    lines.append("")
    lines.append("Generated by re/g_closure.py. Every function below is real domain code that some unimplemented export")
    lines.append("needs, directly or through other such functions. Sort key: how many exports need it, then size.")
    lines.append("")
    lines.append("| rva | bytes | needed by | depth | own domain deps |")
    lines.append("|---|---:|---:|---:|---:|")
    for n, size, d, own, addr in rows:
        lines.append("| 0x%X | %d | %d | %d | %d |" % (addr, size, n, d, own))
    lines.append("")
    lines.append("## Exports that need no further reading")
    lines.append("")
    for name, ord0, rva, size in sorted(ready_now, key=lambda x: x[3]):
        lines.append("* 0x%X ordinal %d %s, %d bytes" % (rva, ord0, name, size))
    lines.append("")
    lines.append("## Exports with the smallest closures, which are the cheapest to finish")
    lines.append("")
    cheap = sorted(closure.items(), key=lambda kv: (len(kv[1]), kv[0][1]))[:40]
    lines.append("| ordinal | export | domain functions needed | total bytes |")
    lines.append("|---:|---|---:|---:|")
    by_ord = {(n, o): (r, s) for n, o, r, s in exports}
    for (name, ord0), seen in cheap:
        total = sum(((profile.get(a) or {}).get("size") or 0) for a in seen)
        lines.append("| %d | %s | %d | %d |" % (ord0, name, len(seen), total))
    io.open(os.path.join(L.ROOT, "re", "WORKLIST.md"), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")

    print("unimplemented exports: %d" % len(exports))
    print("domain functions in their closures: %d" % len(rows))
    print("exports needing no further reading: %d" % len(ready_now))
    total_bytes = sum(r[1] for r in rows)
    print("total domain bytes to read: %d" % total_bytes)
    print("")
    print("the twenty with the most leverage:")
    for n, size, d, own, addr in rows[:20]:
        print("    0x%-8X %5d B  needed by %3d  depth %d  own deps %d" % (addr, size, n, d, own))
    print("")
    print("wrote re/WORKLIST.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
