# -*- coding: utf-8 -*-
"""Round 367: a work queue for the remaining exports, derived from their structure rather than from convenience.

Each unimplemented export is classified by what its body actually contains: how many instructions, whether it calls
anything (and whether those callees are recovered), whether it branches or loops, and whether it only reads. That turns
the remaining 154 entries into an ordered queue with a reason per entry, so the coming rounds read the cheapest thing
first and know what a bigger function is blocked on before opening it.
"""
import io
import json
import os
import re
import sys

ROOT = r"D:\Nesting\nestfab"
sys.path.insert(0, os.path.join(ROOT, "re"))
from lib import disasm, load_prof  # noqa: E402

TABLE = os.path.join(ROOT, "re", "exports_table.json")
MAP = os.path.join(ROOT, "lcns", "include", "lcns", "detail", "exports_forwarding.inc")
OUT = os.path.join(ROOT, "re", "EXPORT_QUEUE.md")

already = set()
for line in io.open(MAP, encoding="utf-8"):
    m = re.match(r"\s*\{(\d+),", line)
    if m:
        already.add(int(m.group(1)))

# Which addresses have a recovered implementation? Those are the forwarding map's ordinals, mapped back to rva.
prof = load_prof()
by_ord = {}
for e in json.loads(io.open(TABLE, encoding="utf-8").read()):
    by_ord[(e.get("ords") or [0])[0]] = e
recovered_rvas = {by_ord[o]["rva"] for o in already if o in by_ord}

rows = []
for e in json.loads(io.open(TABLE, encoding="utf-8").read()):
    ord0 = (e.get("ords") or [0])[0]
    if ord0 in already:
        continue
    ins = [x for x in disasm(e["rva"]) if x.address < e["rva"] + e["size"]]
    calls = [x for x in ins if x.mnemonic == "call"]
    ext = []
    for x in calls:
        m = re.search(r"0x([0-9a-f]+)", x.op_str)
        if m:
            t = int(m.group(1), 16)
            if not (e["rva"] <= t < e["rva"] + e["size"]):
                ext.append(t)
    unresolved = sorted({t for t in ext if t not in recovered_rvas})
    branches = [x for x in ins if x.mnemonic.startswith("j") and x.mnemonic != "jmp"]
    backward = any(x.mnemonic.startswith("j") and re.search(r"0x([0-9a-f]+)", x.op_str) and
                   int(re.search(r"0x([0-9a-f]+)", x.op_str).group(1), 16) < x.address for x in ins)
    reads = sum(1 for x in ins if "[" in x.op_str and x.mnemonic.startswith("mov") and
                not x.op_str.split(",")[0].strip().endswith("]"))
    writes = sum(1 for x in ins if "ptr [" in x.op_str and x.op_str.split(",")[0].strip().endswith("]"))
    score = len(ins) + 8 * len(calls) + 4 * len(branches) + (40 if backward else 0)
    rows.append({
        "name": e.get("name") or ("sub_%05X" % e["rva"]),
        "ord": ord0, "rva": e["rva"], "size": e["size"], "nins": len(ins),
        "calls": len(calls), "unresolved": unresolved, "branches": len(branches),
        "backward": backward, "reads": reads, "writes": writes, "score": score,
    })

rows.sort(key=lambda r: (r["score"], r["size"]))

md = ["# Export work queue",
      "",
      "Generated by `re/g_export_queue.py` from each entry's own instructions. The score is",
      "`instructions + 8*calls + 4*branches + 40 (if it loops)`; a call into an address with no recovered implementation",
      "is named, because that is what a bigger entry is blocked on. Entries are listed cheapest-first, which is the order",
      "they will be read in.",
      "",
      "| # | entry (ordinals) | rva | size | insns | calls | loops | reads | writes | blocked on |",
      "|---:|---|---:|---:|---:|---:|:--:|---:|---:|---|"]
for i, r in enumerate(rows, 1):
    blocked = ", ".join("0x%X" % t for t in r["unresolved"][:4]) or ("-" if r["calls"] == 0 else "recovered")
    if len(r["unresolved"]) > 4:
        blocked += " (+%d)" % (len(r["unresolved"]) - 4)
    md.append("| %d | `%s` (%d) | `0x%X` | %d | %d | %d | %s | %d | %d | %s |"
              % (i, r["name"], r["ord"], r["rva"], r["size"], r["nins"], r["calls"],
                 "yes" if r["backward"] else "", r["reads"], r["writes"], blocked))

cheap = [r for r in rows if r["calls"] == 0 and not r["backward"]]
md += ["",
       "## Read this first: %d entries with no call and no loop" % len(cheap),
       "",
       "These are the ones that can be recovered without reading anything else, so they come before the rest:",
       ""]
for r in cheap[:40]:
    md.append("* `%s` (ord %d, rva `0x%X`, %d bytes, %d instructions) -- %s"
              % (r["name"], r["ord"], r["rva"], r["size"], r["nins"],
                 "reads %d / writes %d" % (r["reads"], r["writes"])))
md += ["",
       "## What the biggest blockers are",
       "",
       "The addresses below are called by several unimplemented entries, so recovering one of them unblocks more than one",
       "entry. Each will be read as a function in its own right, by the same rules: model it, test it, then point the",
       "callers at it.",
       ""]
counts = {}
for r in rows:
    for t in r["unresolved"]:
        counts[t] = counts.get(t, 0) + 1
for t, n in sorted(counts.items(), key=lambda kv: -kv[1])[:12]:
    size = (prof.get(t) or {}).get("size")
    md.append("* `0x%X` -- called by %d unimplemented entries%s" % (t, n, (", %s bytes" % size) if size else ""))

io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(md) + "\n")
print("queue written: %d unimplemented entries, %d with no call and no loop" % (len(rows), len(cheap)))
print("top blockers: " + ", ".join("0x%X(%d)" % (t, n) for t, n in sorted(counts.items(), key=lambda kv: -kv[1])[:6]))
