#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate lcns/include/lcns/option_keys.hpp from re/param_split.json.

The confirmed parameter names: identifier-like strings that precede a call to RE 0x82A3E0 AND whose lookup result is stored into a field.
The second condition is what separates a parameter from a datum -- the previous round's count included MIPLIB benchmark names because a
`lea` of a rip-relative string precedes the lookup either way.

Two independent sources agree on 54 of these: the findings archive's option-key table, built by reading a rodata range, contains 54 names
and every one of them is here. So each entry below is either confirmed twice or confirmed by the store test alone, and the header says
which.
"""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SPLIT = os.path.join(HERE, "param_split.json")
ARCHIVE = os.path.join(HERE, "findings_engine.md")
OUT = os.path.join(ROOT, "lcns", "include", "lcns", "option_keys.hpp")

import re  # noqa: E402

HEADER = '''// lcns/include/lcns/option_keys.hpp -- the nesting engine's option names, each confirmed by a store.
//
// GENERATED by re/g_gen_option_keys.py from re/param_split.json. Do not edit by hand.
//
// A name is here when an identifier-like string precedes a call to RE 0x82A3E0 AND the lookup's result is stored into a field of an
// object. The second condition is the one that matters: a `lea` of a rip-relative string precedes the lookup whether or not the string is
// a parameter, which is how an earlier count came to include MIPLIB benchmark names -- air03, bell3a, danoint, egout -- as if they were
// options.
//
// TWO SOURCES CONFIRM %(twice)d OF THEM. The findings archive's option-key table was built by reading a rodata range; this list is built
// by following call sites and checking the store. All %(twice)d of the archive's names are here, and the remaining %(once)d are confirmed
// by the store test alone, which is a weaker but still mechanical witness.
//
// %(total)d names in all. The archive's table is the smaller because a rodata range does not contain every option string.
#pragma once

#include <cstddef>

namespace lcns {

/** One option name with how often it is looked up and how often the result is stored.
 *
 *  `lookups` counts every site that loads the name; `stores` counts the sites whose result reaches a field. A name with lookups greater
 *  than stores is loaded at sites that do not store -- which happens when a parser reads an option to TEST it and writes elsewhere.
 */
struct OptionKey {
    const char* name;
    unsigned lookups;
    unsigned stores;
};

inline const OptionKey* optionKeys(std::size_t& count) {
    static const OptionKey table[] = {
%(rows)s    };
    count = sizeof(table) / sizeof(table[0]);
    return table;
}

/** The count of names confirmed by BOTH the archive and the store test. */
constexpr std::size_t kOptionKeysConfirmedTwice = %(twice)d;
/** And the total. */
constexpr std::size_t kOptionKeyCount = %(total)d;

}  // namespace lcns
'''


def main():
    split = json.loads(io.open(SPLIT, encoding="utf-8").read())
    parameters = split["parameters"]

    text = io.open(ARCHIVE, encoding="utf-8", errors="replace").read()
    marker = text.find("完整选项键表")
    end = text.find("\n## ", marker + 10) if marker >= 0 else -1
    chunk = text[marker:end if end > 0 else marker + 20000] if marker >= 0 else ""
    archive = {name for name in re.findall(r"`([a-z][a-z0-9_]{4,})`", chunk)}

    rows = []
    twice = 0
    for name in sorted(parameters):
        entry = parameters[name]
        if name in archive:
            twice += 1
        rows.append('        {"%s", %d, %d},\n' % (name, entry["seen"], entry["stored"]))

    if not rows:
        print("REFUSING: re/param_split.json has no parameters")
        return 2
    if twice == 0:
        print("REFUSING: none of the archive's names is in the split, so the two sources are not being compared")
        return 2

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(HEADER % {
        "rows": "".join(rows),
        "total": len(rows),
        "twice": twice,
        "once": len(rows) - twice,
    })
    print("wrote %s with %d option names, %d confirmed by both sources" % (OUT, len(rows), twice))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
