# -*- coding: utf-8 -*-
"""Generate lcns/include/lcns/class_constructors.hpp from re/all_class_fields.json.

Every class's constructor, found by the vtable slot-0 address it installs, with the number of DISTINCT field offsets it writes and how many
of the class's functions write any field at all. This is the population version of the two rounds before it, and it is generated so the
numbers cannot drift from the scan that produced them.
"""
import io
import json
import os

ROOT = r"D:\Nesting\nestfab"
SRC = os.path.join(ROOT, "re", "all_class_fields.json")
OUT = os.path.join(ROOT, "lcns", "include", "lcns", "class_constructors.hpp")

PROLOGUE = '''// lcns/include/lcns/class_constructors.hpp -- every class's constructor and the fields it writes.
//
// GENERATED by re/g_gen_class_ctors.py from re/all_class_fields.json, which re/g_all_class_fields.py produced by joining
// re/g_find_ctors.py (a constructor references its vtable's slot-0 ADDRESS, which is vtable_rva+0x10) to re/g_class_fields.py (a field's
// position is a store through a register the function has been shown to hold the object in, before that register is reassigned).
//
// %(classes)d classes have a constructor candidate; %(writing)d of them write at least one field. **A class with a constructor and no field
// writes is a real shape rather than a failure**: its constructor installs the vtable and nothing else, which is what a class with only
// virtual methods and no state looks like.
//
// THE FIELD COUNT IS A COUNT OF DISTINCT OFFSETS, so a class that writes 0x30 twice -- once zeroed and once from a double, as
// Multi::NestingNester does -- counts once. It is the number of POSITIONS the constructor names, not the number of stores.
#pragma once

#include <cstddef>
#include <cstdint>

namespace lcns {

struct ClassConstructor {
    const char* qualified;
    std::uintptr_t constructor;     // the candidate that writes the most fields
    std::uintptr_t vtable;
    unsigned fields;                // distinct offsets written
    unsigned candidates;            // functions referencing the slot-0 address
    unsigned functionsWriting;      // of those, how many write any field
};

inline const ClassConstructor* classConstructors(std::size_t& count) {
    static const ClassConstructor table[] = {
%(rows)s    };
    count = sizeof(table) / sizeof(table[0]);
    return table;
}

constexpr std::size_t kClassesWithConstructor = %(classes)d;
constexpr std::size_t kClassesWritingFields = %(writing)d;

}  // namespace lcns
'''


def main():
    data = json.loads(io.open(SRC, encoding="utf-8").read())
    rows = []
    for entry in data["classes"]:
        name = entry["class"].replace('"', "'")
        ctor = entry["constructor"]
        rows.append('        {"%s", %s, %s, %d, %d, %d},\n'
                    % (name, ctor if ctor else "0", entry["vtable"], entry["fields"], entry["candidates"],
                       entry["functions_writing"]))
    if len(rows) < 50:
        print("REFUSING: only %d classes" % len(rows))
        return 2
    writing = sum(1 for e in data["classes"] if e["fields"] > 0)
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(
        PROLOGUE % {"rows": "".join(rows), "classes": len(rows), "writing": writing})
    print("wrote %s with %d classes, %d of them writing fields" % (OUT, len(rows), writing))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
