#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate lcns/include/lcns/class_definitions.hpp: every class the RTTI names, DECLARED, in its own namespace.

WHAT IT REFUSES TO DO, which is the point: it does not invent data members, bases or method names. The vtable says how many virtuals a
class has and nothing about its data, so a generated class with made-up members would be the defect this project's ledger exists to
prevent. **A declaration here is the module's own claim that a class exists**, which is the claim the repository was making with a comment.

Two things learned from a first attempt: a namespace block must be emitted as `namespace Name {` on its own line with a matching close, and
TWO CLASSES MAY SHARE A SHORT NAME IN DIFFERENT NAMESPACES, so the declarations are grouped by full name and the table keys on it.
"""
import glob
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "lcns", "include", "lcns", "class_definitions.hpp")

sys.path.insert(0, HERE)
from lib import load_prof  # noqa: E402

FOREIGN = ("N8CryptoPP", "N5boost", "N6Json", "N9__gnu_cxx", "NSt7__cxx11", "N10__cxxabiv1", "N6Locale", "NSt6locale",
           "N5Clp", "N4Coin", "N8CoinUtils", "N3Osi", "N3Cbc", "N11CoinPresolve", "N6Ipopt", "N5Ipopt")
GENERATED = {"classes.hpp", "virtual_methods.hpp", "parameter_report.hpp", "option_keys.hpp", "miplib_names.hpp",
             "engine_defaults.hpp", "class_definitions.hpp"}

PROLOGUE = '''// lcns/include/lcns/class_definitions.hpp -- every class the module's RTTI names, DECLARED, in its own namespace.
//
// GENERATED by re/g_gen_class_definitions.py from re/vtables.json. Do not edit by hand.
//
// The repository used to name classes in prose and declare almost none -- re/g_defined_classes.py finds places where a header names one of
// the module's own classes more than once and declares it nowhere. This is the systematic answer: %(declared)d declarations, one per class.
//
// WHAT A DECLARATION HERE CLAIMS: that the class exists, that its vtable is at the named address, and that it has that many virtual slots
// of which slot 2 is the first declared. WHAT IT DOES NOT CLAIM: anything about the class's data. **No member is invented**, because the
// vtable does not say what a class holds.
//
// %(skipped)d classes already defined by hand are NOT repeated, because two declarations of one class is a compile error and one of them
// would have to be wrong. Their names are listed in the comment beside the table.
#pragma once

#include <cstddef>
#include <cstdint>

namespace lcns {

/** The facts the RTTI and the profile establish about one class. */
struct ClassFacts {
    const char* qualified;
    std::uintptr_t vtable;
    unsigned slots;
    std::uintptr_t firstVirtual;    // slot 2, past the destructor pair
    unsigned firstVirtualBytes;     // its size, or 0 when the profile does not know it
    bool definedByHand;             // a hand-written header declares it, so it is not repeated below
};

inline const ClassFacts* classFacts(std::size_t& count) {
    static const ClassFacts table[] = {
%(rows)s    };
    count = sizeof(table) / sizeof(table[0]);
    return table;
}

'''


def main():
    data = json.loads(io.open(os.path.join(HERE, "vtables.json"), encoding="utf-8").read())
    profile = load_prof()

    hand = set()
    for path in glob.glob(os.path.join(ROOT, "lcns", "include", "lcns", "**", "*.hpp"), recursive=True):
        if os.path.basename(path) in GENERATED:
            continue
        text = io.open(path, encoding="utf-8", errors="replace").read()
        for match in re.finditer(r"\b(?:class|struct)\s+(\w+)", text):
            hand.add(match.group(1))

    rows = []
    for mangled, entry in data.items():
        if any(mangled.startswith(prefix) for prefix in FOREIGN):
            continue
        qualified = (entry.get("demangled") or "").strip()
        slots = [int(a) for a in entry.get("slots") or []]
        if not qualified or "<" in qualified or "subst" in qualified or len(slots) < 3:
            continue
        short = qualified.split("::")[-1]
        if not short or not short[0].isalpha() or not re.match(r"^\w+$", short):
            continue
        first = slots[2]
        size = (profile.get(first) or {}).get("size") or 0
        namespace = qualified.rsplit("::", 1)[0] if "::" in qualified else ""
        rows.append((qualified, short, namespace, int(entry["vtable_rva"]), len(slots), first, size, short in hand))

    if len(rows) < 50:
        print("REFUSING: only %d usable classes" % len(rows))
        return 2

    # the table, keyed on the qualified name because two classes may share a short one
    table_rows = []
    for qualified, _short, _ns, vtable, slots, first, size, byhand in sorted(rows):
        table_rows.append('        {"%s", 0x%X, %d, 0x%X, %d, %s},\n'
                          % (qualified.replace('"', "'"), vtable, slots, first, size, "true" if byhand else "false"))

    # ONE NAMESPACE COLLIDES AND IS RENAMED. `Engine` in the RTTI is a namespace; this repository already has `lcns::Engine` as a
    # class, and a namespace and a class cannot share a name. The generated namespace is `EngineNS` and the table keeps the RTTI's own
    # qualified name, so nothing is lost -- only the emitted identifier differs, and it says why.
    RENAME = {"Engine": "EngineNS"}

    # the declarations, grouped by namespace, skipping anything a hand-written header already declares
    by_namespace = {}
    declared = 0
    skipped = 0
    for qualified, short, namespace, vtable, slots, first, size, byhand in rows:
        if byhand:
            skipped += 1
            continue
        by_namespace.setdefault(RENAME.get(namespace, namespace), []).append((short, qualified, vtable, slots, first, size))
        declared += 1

    blocks = ["// ------------------------------------------------------------------------------------------------",
              "// THE DECLARATIONS. Each carries the virtual count the RTTI gives it; the only method named is the destructor, because",
              "// the ABI gives that one and the module does not have to say it.",
              ""]
    for namespace in sorted(by_namespace):
        if namespace:
            blocks.append("namespace %s {" % namespace.replace("::", " { namespace "))
        for short, qualified, vtable, slots, first, size in sorted(by_namespace[namespace]):
            blocks.append("")
            blocks.append("/** %s -- vtable 0x%X, %d virtual slot(s). */" % (qualified, vtable, slots))
            blocks.append("class %s {" % short)
            blocks.append("public:")
            blocks.append("    virtual ~%s() = default;" % short)
            blocks.append("")
            blocks.append("    // Slot 2, the first DECLARED virtual, is 0x%X%s." %
                          (first, (" -- %d bytes, read" % size) if size else " -- no body in the profile"))
            blocks.append("};")
        if namespace:
            for _ in range(namespace.count("::") + 1):
                blocks.append("}  // namespace")
        blocks.append("")

    counts = []
    for namespace in sorted(by_namespace):
        identifier = re.sub(r"[^A-Za-z0-9]", "_", namespace) or "global"
        counts.append("constexpr std::size_t kDeclaredIn_%s = %d;" % (identifier, len(by_namespace[namespace])))

    text = (PROLOGUE % {"rows": "".join(table_rows), "declared": declared, "skipped": skipped}
            + "\n".join(counts) + "\n\n" + "\n".join(blocks) + "\n}  // namespace lcns\n")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s" % OUT)
    print("  classes in the table: %d" % len(rows))
    print("  declarations emitted: %d" % declared)
    print("  skipped, already defined by hand: %d" % skipped)
    print("")
    for namespace in sorted(by_namespace):
        print("   %-18s %d" % (namespace or "(global)", len(by_namespace[namespace])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
