#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate lcns/include/lcns/virtual_methods.hpp: every virtual slot of every own class, with its address.

re/vtables.json holds, for each class, the addresses in its vtable in slot order. Those are the class's VIRTUAL METHODS, and until now the
repository named three of them in prose (destructor, deleting destructor, Run) and had no table. This emits the table.

    Engine::InfiniteEngine, vtable 0xA3CFD0
        slot 0  0x759B20   the deleting destructor
        slot 1  0x759AD0   the destructor
        slot 2  0x759A80   Run -- the one this project implemented as lcns::InfiniteEngine

WHAT THE SLOT ORDER SAYS. The first two slots are the destructor pair for every polymorphic class in this module's ABI, so slot 2 is the
first DECLARED virtual and everything after it is declared after it. A slot count therefore says how many virtuals a class declares, and
the addresses say where each is -- which is the map a reconstruction needs and which a prose list of RVAs is not.

WHAT IT DOES NOT SAY: the NAME or the SIGNATURE of any slot except where a base class's own declaration gives it. Slot 2 of an Engine is
`Run`, because the base class's Run is what the call site at 0x2516E reaches and because the archive records it; slot 2 of a Nester is
NOT called `Run` merely because it is slot 2. So the table carries the ADDRESS and the SLOT INDEX and leaves the naming to whichever
reading establishes it, per class rather than per position.
"""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "lcns", "include", "lcns", "virtual_methods.hpp")

FOREIGN = ("N8CryptoPP", "N5boost", "N6Json", "N9__gnu_cxx", "NSt7__cxx11", "N10__cxxabiv1", "N6Locale", "NSt6locale",
           "N5Clp", "N4Coin", "N8CoinUtils", "N3Osi", "N3Cbc", "N11CoinPresolve", "N6Ipopt", "N5Ipopt")

HEADER = '''// lcns/include/lcns/virtual_methods.hpp -- every virtual slot of the module's own classes.
//
// GENERATED by re/g_gen_virtual_methods.py from re/vtables.json. Do not edit by hand.
//
// %(classes)d classes and %(slots)d virtual slots between them. The first two slots of every class are the destructor pair for this ABI, so
// slot 2 is the first declared virtual and a slot count says how many virtuals a class declares.
//
// **The addresses are evidence; the names are not.** Slot 2 of an Engine is `Run`, because the call site at 0x2516E reaches it and the
// archive records the signature. Slot 2 of a Nester is NOT called `Run` merely because it is in the same position -- so this file carries
// the SLOT INDEX and the ADDRESS, and the two names that ARE established are given constants of their own.
#pragma once

#include <cstddef>
#include <cstdint>

namespace lcns {

struct VirtualSlot {
    const char* owner;          // the demangled class
    unsigned index;             // the slot's position in the vtable
    std::uintptr_t address;     // the function the slot points at
};

inline const VirtualSlot* virtualSlots(std::size_t& count) {
    static const VirtualSlot table[] = {
%(rows)s    };
    count = sizeof(table) / sizeof(table[0]);
    return table;
}

/** RE 0x2516E: the slot the engine call site reaches, and RE 0x759A80: the function this project implemented. */
constexpr unsigned kEngineRunSlotIndex = 2;
constexpr std::uintptr_t kEngineRunSlotAddress = 0x759A80;

/** The two slots every class has first, by position rather than by name -- the names are the ABI's, not the module's. */
constexpr unsigned kDestructorSlot = 1;
constexpr unsigned kDeletingDestructorSlot = 0;

%(counts)s
}  // namespace lcns
'''


def main():
    data = json.loads(io.open(os.path.join(HERE, "vtables.json"), encoding="utf-8").read())
    rows = []
    classes = 0
    slots_total = 0
    per_class = {}
    for mangled, entry in data.items():
        if any(mangled.startswith(prefix) for prefix in FOREIGN):
            continue
        demangled = (entry.get("demangled") or "").strip()
        slots = entry.get("slots") or []
        if not demangled or not slots:
            continue
        classes += 1
        for index, address in enumerate(slots):
            rows.append((demangled, index, int(address)))
            slots_total += 1
        per_class[demangled] = len(slots)

    if classes < 50 or slots_total < 100:
        print("REFUSING: %d classes and %d slots is too few for this module's RTTI" % (classes, slots_total))
        return 2

    rows.sort(key=lambda r: (r[0], r[1]))
    table_rows = []
    for owner, index, address in rows:
        table_rows.append('        {"%s", %d, 0x%X},\n' % (owner.replace('"', "'"), index, address))

    counts = []
    for owner, number in sorted(per_class.items(), key=lambda kv: (-kv[1], kv[0]))[:24]:
        identifier = "kSlots_" + "".join(character if character.isalnum() else "_" for character in owner)
        counts.append("constexpr unsigned %s = %d;" % (identifier, number))

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(HEADER % {
        "rows": "".join(table_rows),
        "classes": classes,
        "slots": slots_total,
        "counts": "\n".join(counts),
    })
    print("wrote %s with %d classes and %d slots" % (OUT, classes, slots_total))
    print("")
    print("the classes with the most virtuals:")
    for owner, number in sorted(per_class.items(), key=lambda kv: -kv[1])[:10]:
        print("   %-34s %d" % (owner[:34], number))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
