#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate lcns/include/lcns/classes.hpp from re/vtables.json: the module's own classes, as C++ declarations.

The human asked why InfiniteEngine had only a comment, and the same was true of every class in the module. re/vtables.json holds 96 RTTI
entries for the module's own classes -- after the standard library, boost, CryptoPP, Json, Coin and Clp are set aside -- each with its
vtable address, its slot count and its demangled name. That is a class hierarchy with addresses, which is exactly what a C++ reconstruction
needs to state and what a reader cannot get from a comment listing slot RVAs.

WHAT THIS EMITS AND WHAT IT DOES NOT. It emits one declaration per class with the vtable's address and slot count as constants, and the
namespace as the module's RTTI gives it. It does NOT invent members, bases or method signatures: the vtable says how many virtual slots a
class has and where its vtable is, and says nothing about its data. A generated class with invented members would be the defect this
project's ledger exists to prevent, so members appear only where a base-offset is known and are marked as such.

Every entry carries its MANGLED name too, because that is the primary evidence: the demangled form is a decode, and a decode can be wrong
while the mangling cannot.
"""
import io
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "lcns", "include", "lcns", "classes.hpp")

# foreign libraries: named so the exclusion is a decision and not an oversight
FOREIGN = ("N8CryptoPP", "N5boost", "N6Json", "N9__gnu_cxx", "NSt7__cxx11", "N10__cxxabiv1", "N6Locale", "NSt6locale",
           "N5Clp", "N4Coin", "N8CoinUtils", "N3Osi", "N3Cbc", "N11CoinPresolve", "N6Ipopt", "N5Ipopt")

HEADER = '''// lcns/include/lcns/classes.hpp -- the module's own classes, generated from its RTTI.
//
// GENERATED by re/g_gen_classes.py from re/vtables.json. Do not edit by hand.
//
// The human asked why InfiniteEngine had only a comment. It did, and so did every other class: the repository listed slot RVAs in prose
// and defined none of them. This file states the hierarchy the module's OWN RTTI states -- %(count)d classes after the standard library,
// boost, CryptoPP, Json, Coin and Clp are set aside -- each with its vtable address, its slot count and its mangled name.
//
// WHAT A DECLARATION HERE MEANS: that this class exists, that its type_info is at the named vtable, and that it has that many virtual
// slots. WHAT IT DOES NOT MEAN: anything about its data. The vtable does not say what a class holds, so members are not invented -- and
// the mangled name is carried beside the demangled one because the demangling is a decode and the mangling is not.
#pragma once

#include <cstddef>
#include <cstdint>

namespace lcns {

/** The vtable and slot count of one class, as its RTTI states them. */
struct ClassInfo {
    const char* mangled;
    const char* qualified;      // the demangled name, which is a decode of the mangling
    std::uintptr_t vtable;
    unsigned slots;
};

inline const ClassInfo* moduleClasses(std::size_t& count) {
    static const ClassInfo table[] = {
%(rows)s    };
    count = sizeof(table) / sizeof(table[0]);
    return table;
}

%(counts)s
}  // namespace lcns
'''


def main():
    data = json.loads(io.open(os.path.join(HERE, "vtables.json"), encoding="utf-8").read())
    rows = []
    for mangled, entry in data.items():
        if any(mangled.startswith(prefix) for prefix in FOREIGN):
            continue
        vtable = entry.get("vtable_rva")
        slots = entry.get("slots") or []
        demangled = (entry.get("demangled") or "").strip()
        if not vtable or not demangled:
            continue
        rows.append((demangled, mangled, int(vtable), len(slots)))
    rows.sort()

    if len(rows) < 50:
        print("REFUSING: only %d own classes found, which is too few for this module's RTTI" % len(rows))
        return 2

    # namespace counts, so the shape of the module is visible in the generated file
    namespaces = {}
    for qualified, _mangled, _vtable, _slots in rows:
        namespace = qualified.split("::")[0] if "::" in qualified else "(global)"
        namespaces[namespace] = namespaces.get(namespace, 0) + 1

    table_rows = []
    for qualified, mangled, vtable, slots in rows:
        table_rows.append('        {"%s", "%s", 0x%X, %d},\n' % (mangled, qualified.replace('"', "'"), vtable, slots))

    counts = []
    for namespace, number in sorted(namespaces.items(), key=lambda kv: -kv[1]):
        identifier = re.sub(r"[^A-Za-z0-9]", "_", namespace)
        if identifier and identifier[0].isdigit():
            identifier = "n" + identifier
        counts.append("constexpr std::size_t kClassesIn_%s = %d;" % (identifier, number))

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(HEADER % {
        "rows": "".join(table_rows),
        "count": len(rows),
        "counts": "\n".join(counts),
    })
    print("wrote %s with %d classes" % (OUT, len(rows)))
    print("")
    print("by namespace: %s" % ", ".join("%s %d" % kv for kv in sorted(namespaces.items(), key=lambda kv: -kv[1])[:10]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
