# -*- coding: utf-8 -*-
"""Recover the string literals each function hands to the logger, which is where the names are.

Usage: python g_labels.py            -> the table for every unimplemented export, written to re/LABELS.md
       python g_labels.py 0x2AB0     -> the labels of one function or export rva

Every function in this module announces itself: a rip-relative lea loads a label and a call into the 0x64xxxx logger family
takes it. The displacement is relative to the next instruction, which is the same correction the angle constants needed, and
the string sits at that address. Decoding them turns an address into a name, and a name into a hint about what the function
does, which is the cheapest evidence available and does not require reading the body at all.

Both the label and, when the call passes a length in rdx or r8, that length are reported, because the sequences I have read
elsewhere pass the exact length rather than relying on a terminator.
"""
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import g_leverage as L          # noqa: E402
from lib import disasm, load_prof, rva2off  # noqa: E402

DATA = L.__dict__.get("lib")           # not needed; kept explicit below
import lib as LIB                      # noqa: E402

IMAGE = LIB.data if isinstance(LIB.data, (bytes, bytearray)) else LIB.data()


def printable(data):
    out = []
    for b in data:
        if b == 0:
            break
        if 32 <= b < 127:
            out.append(chr(b))
        else:
            return "".join(out)
    return "".join(out)


def string_at(rva, limit=96):
    try:
        off = rva2off(rva)
    except Exception:
        return None
    if off is None or off < 0 or off >= len(IMAGE):
        return None
    text = printable(IMAGE[off:off + limit])
    return text if len(text) >= 2 else None


def function_labels(rva, size):
    """Every rip-relative literal the function loads, with the register and the instruction address."""
    found = []
    body = [i for i in disasm(rva) if not size or i.address < rva + size]
    for index, ins in enumerate(body):
        m = re.search(r"\[rip \+ 0x([0-9a-f]+)\]", ins.op_str)
        if not m:
            continue
        disp = int(m.group(1), 16)
        nxt = body[index + 1].address if index + 1 < len(body) else ins.address + 8
        target = nxt + disp
        text = string_at(target)
        if text:
            found.append((ins.address, ins.mnemonic, ins.op_str.split(",")[0], target, text))
    return found


def main(argv):
    profile = load_prof()
    table = json.loads(io.open(os.path.join(L.ROOT, "re", "exports_table.json"), encoding="utf-8").read())
    done = L.forwarded_ordinals()

    if argv and argv[0].startswith("0x"):
        rva = int(argv[0], 16)
        size = (profile.get(rva) or {}).get("size")
        for a, mnemonic, reg, target, text in function_labels(rva, size):
            print("   0x%-8X %-8s %-10s -> 0x%-8X %r" % (a, mnemonic, reg, target, text))
        return 0

    lines = ["# The log labels of the unimplemented exports", "",
             "Generated by re/g_labels.py. A rip-relative displacement is measured from the next instruction, so the string",
             "sits at that plus the displacement; the label and the length the call passes are both the module's own words.",
             ""]
    total = 0
    for e in sorted(table, key=lambda x: (x.get("ords") or [0])[0]):
        ord0 = (e.get("ords") or [0])[0]
        if ord0 in done:
            continue
        name = e.get("name") or ("sub_%05X" % e["rva"])
        labels = function_labels(e["rva"], e["size"])
        total += len(labels)
        lines.append("## ordinal %d, 0x%X, %d bytes, %s" % (ord0, e["rva"], e["size"], name))
        lines.append("")
        if labels:
            for a, _mnemonic, _reg, target, text in labels[:8]:
                lines.append("* 0x%X -> `%s` (string at 0x%X)" % (a, text.replace("`", "'"), target))
        else:
            labels2 = []
            size = (profile.get(e["rva"]) or {}).get("size")
            for i in disasm(e["rva"]):
                if size and i.address >= e["rva"] + size:
                    break
                if i.mnemonic == "call" or i.mnemonic == "jmp":
                    m = re.search(r"0x([0-9a-f]+)", i.op_str)
                    if m:
                        t = int(m.group(1), 16)
                        ts = (profile.get(t) or {}).get("size")
                        labels2 += function_labels(t, ts)
            if labels2:
                lines.append("* (through a callee)")
                for a, _mnemonic, _reg, target, text in labels2[:6]:
                    lines.append("* 0x%X -> `%s`" % (a, text.replace("`", "'")))
            else:
                lines.append("* no literal found in the entry or its direct callees")
        lines.append("")
    out = os.path.join(L.ROOT, "re", "LABELS.md")
    io.open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print("wrote re/LABELS.md with labels for every unimplemented export")
    print("literals found: %d" % total)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
