# -*- coding: utf-8 -*-
"""What the naming channels bought, kept strictly in two parts.

Usage: python g_names_report.py

re/name_registry.json holds, per function, the names read out of its own call sites and, separately, the names guessed
from the functions it calls. The first is evidence; the second is a hypothesis. This writes re/NAME_COVERAGE.md with the
two never added together, and it reports each channel's yield against the set that matters -- the reachable functions this
project has not cited, implemented, verified or classified as library.
"""
import glob
import io
import json
import os
import re
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import g_leverage as L          # noqa: E402
import g_toolchain as T         # noqa: E402
from lib import load_prof  # noqa: E402

ROOT = L.ROOT
SKIP = {"NAMES.md", "NAME_COVERAGE.md", "name_registry.json", "ASSERTIONS.md"}


def main():
    profile = load_prof()
    reg = json.load(io.open(os.path.join(ROOT, "re", "name_registry.json"), encoding="utf-8"))

    direct, guessed = {}, {}
    for key, value in reg.items():
        addr = int(key, 16)
        own = [v for v in value["via"] if not v.startswith("via ")]
        if value["methods"] and own:
            direct[addr] = (sorted(value["methods"]), own, value["loglines"])
        elif value["guessed_from_callees"]:
            guessed[addr] = (sorted(value["guessed_from_callees"]), value["via"])

    cited = set()
    files = glob.glob(os.path.join(ROOT, "re", "*.md")) + glob.glob(os.path.join(ROOT, "re", "*.py"))
    for root, _d, fs in os.walk(os.path.join(ROOT, "lcns")):
        if os.sep + "build" in root:
            continue
        for f in fs:
            if f.endswith((".cpp", ".hpp", ".md")):
                files.append(os.path.join(root, f))
    for fp in files:
        if os.path.basename(fp) in SKIP:
            continue
        try:
            text = io.open(fp, encoding="utf-8", errors="ignore").read()
        except Exception:
            continue
        for m in re.finditer(r"0x([0-9A-Fa-f]{3,8})", text):
            cited.add(int(m.group(1), 16))

    accounted = set(getattr(T, "IMPLEMENTED", ())) | set(T.BOILERPLATE) | set(L.VERIFIED)
    # Names that belong to the standard library or to a third party are not this module's functions, however clean the
    # call site looks: 'stdin', 'column' and 'plain' come out of libstdc++'s and CoinUtils's own assertions, and
    # 'Modulus', 'ClpLinearObjective' and the CryptoPP mangled names out of those libraries' property pages.
    FOREIGN = re.compile(
        r"^(std|__gnu_cxx|Clp|Clp\w+|Coin\w*|Osi\w*|CryptoPP\w*|N[0-9]|_M_|operator|basic_\w+|vector|string|map|set|"
        r"list|deque|stdin|stdout|stderr|column|row|plain|get|put|value|size|begin|end|nullptr|true|false|"
        r"[0-9A-Fa-f]{32,})$")
    newly = sorted(a for a in direct
                   if a not in cited and a not in accounted and not FOREIGN.match(direct[a][0][0]))
    print("names read from a function's own call site: %d" % len(direct))
    print("names guessed from a callee (kept apart, never added in): %d" % len(guessed))
    print("of the direct ones, not cited and not accounted for before: %d" % len(newly))
    print("")
    per_channel = Counter()
    for _methods, own, _logs in direct.values():
        for channel in own:
            per_channel[channel] += 1
    for channel, count in per_channel.most_common():
        print("    channel %-10s %d functions" % (channel, count))
    print("")

    lines = ["# What the naming channels name",
             "",
             "Generated by `re/g_names_report.py` from `re/name_registry.json`.",
             "",
             "A name read from a function's own call site is evidence. A name guessed from the functions it calls is a",
             "hypothesis. **The two are never added together in this file.**",
             "",
             "| | |",
             "|---|---:|",
             "| names read from the function's own call site | %d |" % len(direct),
             "| names guessed from a callee | %d |" % len(guessed),
             "| direct names for functions that were not cited or accounted for before | %d |" % len(newly),
             ""]
    for channel, count in per_channel.most_common():
        lines.append("* channel `%s`: %d functions" % (channel, count))
    lines.append("")
    lines.append("## Functions that had no name and now have one, read from their own call site")
    lines.append("")
    lines.append("| function | size | name | channel | log line |")
    lines.append("|---|---:|---|---|---|")
    for a in newly:
        methods, own, logs = direct[a]
        lines.append("| `0x%X` | %s | `%s` | %s | %s |"
                     % (a, (profile.get(a) or {}).get("size"), methods[0], ", ".join(own),
                        ("`%s`" % logs[0].replace("|", "\\|")[:70]) if logs else ""))
    lines.append("")
    lines.append("## Functions with no name of their own, described by what they call (hypotheses)")
    lines.append("")
    lines.append("| function | size | guessed name | from |")
    lines.append("|---|---:|---|---|")
    for a in sorted(guessed)[:400]:
        methods, via = guessed[a]
        lines.append("| `0x%X` | %s | `%s` | %s |"
                     % (a, (profile.get(a) or {}).get("size"), methods[0],
                        ", ".join(v for v in via if v.startswith("via "))[:60]))
    lines.append("")
    io.open(os.path.join(ROOT, "re", "NAME_COVERAGE.md"), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print("wrote re/NAME_COVERAGE.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
