# -*- coding: utf-8 -*-
"""The module's own class list, with correctly decoded names.

Usage: python g_own_class_list.py [--top 100] [--out re/CLASSES.md]

re/g_own_classes.py decoded the mangled names with a pattern that requires a letter after the length, so `NSt7__cxx11...`
came out as `NSt7__`. This fixes the decoder -- the length prefix can be followed by an underscore -- and filters the
standard library, third party and compiler-runtime symbols by their MANGLED form instead of the decoded one, which is the
reliable test.

The output is this module's class table: vtable address, class name, slot count, and the member region its methods reveal.
That table is what turns a vtable pointer stored in an object into a type, and it is the piece of the architecture this
project had never read.
"""
import io
import json
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import g_names as N             # noqa: E402
import lib as LIB               # noqa: E402
from lib import disasm, load_prof, rva2off  # noqa: E402

IMAGE = LIB.data if isinstance(LIB.data, (bytes, bytearray)) else LIB.data()
ACCESS = re.compile(r"\[([a-z0-9]+)(?: \+ (0x[0-9a-f]+))?\]")
MOVE = re.compile(r"^([a-z0-9]+), ([a-z0-9]+)$")
TOKEN = re.compile(r"(\d+)([A-Za-z0-9_]+)")
WIDTHS = (("xmmword", 16), ("oword", 16), ("qword", 8), ("dword", 4), ("word", 2), ("byte", 1))
ALIAS = {}
for _full, _names in {"rax": ("eax", "ax", "al"), "rbx": ("ebx", "bx", "bl"), "rcx": ("ecx", "cx", "cl"),
                      "rdx": ("edx", "dx", "dl"), "rsi": ("esi", "si", "sil"), "rdi": ("edi", "di", "dil")}.items():
    ALIAS[_full] = _full
    for _n in _names:
        ALIAS[_n] = _full
for _r in range(8, 16):
    for _s in ("", "d", "w", "b"):
        ALIAS["r%d%s" % (_r, _s)] = "r%d" % _r

# Filtered on the MANGLED form, which is what is actually in the file.
FOREIGN_MANGLED = ("8CryptoPP", "4Coin", "3Clp", "3Osi", "5boost", "6Json", "NSt", "St", "__cxxabiv1", "__gnu_cxx",
                   "6locale", "9__gnu_cxx", "N5boost", "4Json", "11JsonCpp")


def canonical(reg):
    return ALIAS.get(reg, reg)


def width_of(text):
    for name, width in WIDTHS:
        if name in text:
            return width
    return 0


def decode(mangled):
    text = mangled
    if text.startswith("_Z"):
        text = text[2:]
    nested = text.startswith("N")
    if nested:
        text = text[1:]
    if text.endswith("E"):
        text = text[:-1]
    parts = []
    for match in TOKEN.finditer(text):
        length = int(match.group(1))
        word = match.group(2)[:length]
        parts.append(word)
    clean = []
    for word in parts:
        if word.startswith("__cxx11") or word.startswith("__cxx"):
            continue
        if word == "St":
            word = "std"
        clean.append(word)
    if not clean:
        return mangled
    return "::".join(clean)


def is_own(mangled):
    if any(marker in mangled for marker in FOREIGN_MANGLED):
        return False
    return True


def class_fields(slots, profile):
    seen = {}
    widths = {}
    for slot in slots:
        size = (profile.get(slot) or {}).get("size") or 0
        if size <= 0:
            continue
        body = [i for i in disasm(slot) if i.address < slot + size]
        carries = {"rcx"}
        for _round in range(3):
            for ins in body:
                m = MOVE.match(ins.op_str)
                if ins.mnemonic == "mov" and m and canonical(m.group(2)) in carries:
                    carries.add(canonical(m.group(1)))
        for ins in body:
            for m in ACCESS.finditer(ins.op_str):
                if canonical(m.group(1)) in carries and m.group(2):
                    offset = int(m.group(2), 16)
                    seen.setdefault(offset, slot)
                    widths[offset] = max(widths.get(offset, 0), width_of(ins.op_str))
    return seen, widths


def main(argv):
    top = int(argv[argv.index("--top") + 1]) if "--top" in argv else 200
    out = argv[argv.index("--out") + 1] if "--out" in argv else None
    profile = load_prof()
    data = json.load(io.open(os.path.join(HERE, "vtables.json"), encoding="utf-8"))

    rows = []
    for mangled, info in data.items():
        if not is_own(mangled):
            continue
        slots = [s for s in (info.get("slots") or []) if s in profile]
        if not slots:
            continue
        seen, widths = class_fields(slots, profile)
        named = [(i, s, N.direct(s)) for i, s in enumerate(slots) if N.direct(s)]
        rows.append((info.get("vtable_rva") or 0, decode(mangled), mangled, slots, seen, named))
    rows.sort()

    lines = ["# This module's classes, from the compiler's own RTTI", "",
             "Generated by `re/g_own_class_list.py` from `re/vtables.json`. A vtable slot is a virtual method and its RVA is a",
             "plain RVA, so each class arrives with its method bodies and no body has to be read. The member region is the union",
             "of the offsets each method touches through its FIRST argument -- the object.",
             "",
             "| vtable | class | slots | named methods | member offsets |",
             "|---|---|---:|---|---|"]
    for vtable, name, mangled, slots, seen, named in rows[:top]:
        offsets = sorted(seen)
        region = " ".join("+0x%X" % o for o in offsets[:14])
        if len(offsets) > 14:
            region += " (+%d more)" % (len(offsets) - 14)
        names = ", ".join("%s@%d" % (label, index) for index, _s, label in named[:4])
        lines.append("| `0x%X` | `%s` | %d | %s | %s |" % (vtable, name, len(slots), names or "", region or "-"))
    lines.append("")
    lines.append("**%d classes in this module.**" % len(rows))
    lines.append("")
    text = "\n".join(lines) + "\n"
    if out:
        io.open(os.path.join(os.path.dirname(HERE), out.replace("/", os.sep)), "w",
                encoding="utf-8", newline="\n").write(text)
        print("wrote %s (%d classes)" % (out, len(rows)))
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
