# -*- coding: utf-8 -*-
"""The eleven strategy classes: their vtable, their Run, and their member region.

Usage: python g_strategy_fields.py [--out re/STRATEGIES.md]

re/g_strategy_vtables.py joined the recovered strategy list to the RTTI, so each strategy now has a vtable address. This
takes the next step: the member region of each strategy class, which is the union of the offsets its own methods touch
through their first argument, with the width of each field and the method that shows it.

That is the declaration the twelve `Run` bodies have been missing. `RowNester` is the interesting one: its Run is 12380 bytes
and the order's destructor walks arrays of 0x50 byte records, so its member list is where those records are introduced.
"""
import io
import json
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import g_names as N             # noqa: E402
from lib import disasm, load_prof  # noqa: E402

ROOT = os.path.dirname(HERE)
ACCESS = re.compile(r"\[([a-z0-9]+)(?: \+ (0x[0-9a-f]+))?\]")
MOVE = re.compile(r"^([a-z0-9]+), ([a-z0-9]+)$")
WIDTHS = (("xmmword", 16), ("oword", 16), ("qword", 8), ("dword", 4), ("word", 2), ("byte", 1))
ALIAS = {}
for _full, _names in {"rax": ("eax", "ax", "al"), "rbx": ("ebx", "bx", "bl"), "rcx": ("ecx", "cx", "cl"),
                      "rdx": ("edx", "dx", "dl"), "rsi": ("esi", "si", "sil"), "rdi": ("edi", "di", "dil")}.items():
    ALIAS[_full] = _full
    for _n in _names:
        ALIAS[_n] = _full
for _r in range(8, 16):
    for _s in ("", "d", "w", "b"):
        ALIAS["r%d%s" % (_r, _s)] = "r%d" % _r

# class name -> (vtable rva, Run rva, Run size), from re/g_strategy_vtables.py and re/STRATEGY_METHODS.md.
STRATEGIES = [
    ("Multi::NestingNester", 0xA3B690, 0x378E0, 14374),
    ("Multi::TilingNester", 0xA3B5A0, 0x46940, 16258),
    ("Multi::LimitedNester", 0xA3B650, 0x4AB40, 1650),
    ("Multi::FlipNester", 0xA3B490, 0x4B870, 3496),
    ("Multi::DatabaseNester", 0xA3B740, 0x5B250, 4495),
    ("Multi::RectangleNester", 0xA3B800, 0x75FB0, 5261),
    ("Multi::MultiTorchNester", 0xA3B8A0, 0x7BCC0, 12232),
    ("Multi::NoFillNester", 0xA3B530, 0x7F240, 8440),
    ("Multi::RowNester", 0xA3BB30, 0x913E0, 12380),
    ("Multi::CompactNester", 0xA3B610, 0xB13D0, 9393),
    ("Multi::FilterNester", 0xA3B4F0, 0xB3AE0, 2254),
]


def canonical(reg):
    return ALIAS.get(reg, reg)


def width_of(text):
    for name, width in WIDTHS:
        if name in text:
            return width
    return 0


def fields_of(slots, profile):
    seen = {}
    widths = {}
    for slot in slots:
        size = (profile.get(slot) or {}).get("size") or 0
        if size <= 0:
            continue
        body = [i for i in disasm(slot) if i.address < slot + size]
        carries = {"rcx"}
        for _round in range(3):
            for ins in body:
                m = MOVE.match(ins.op_str)
                if ins.mnemonic == "mov" and m and canonical(m.group(2)) in carries:
                    carries.add(canonical(m.group(1)))
        for ins in body:
            for m in ACCESS.finditer(ins.op_str):
                if canonical(m.group(1)) in carries and m.group(2):
                    offset = int(m.group(2), 16)
                    seen.setdefault(offset, slot)
                    widths[offset] = max(widths.get(offset, 0), width_of(ins.op_str))
    return seen, widths


def main(argv):
    out = argv[argv.index("--out") + 1] if "--out" in argv else None
    profile = load_prof()
    data = json.load(io.open(os.path.join(HERE, "vtables.json"), encoding="utf-8"))
    vtables = {}
    for mangled, info in data.items():
        vtables[info.get("vtable_rva") or 0] = [s for s in (info.get("slots") or []) if s in profile]

    lines = ["# The eleven strategy classes, their vtables and their member regions", "",
             "Generated by `re/g_strategy_fields.py`. The class names and the `Run` bodies come from",
             "`re/STRATEGY_METHODS.md`; the vtable addresses were joined to them by slot 5 (`re/g_strategy_vtables.py`), and",
             "the member region is the union of the offsets each method touches through its FIRST argument.",
             "",
             "| class | vtable | Run (slot 5) | Run bytes | slots | member offsets |",
             "|---|---|---:|---:|---:|---|"]
    for name, vtable, run, run_size in STRATEGIES:
        slots = vtables.get(vtable, [])
        seen, widths = fields_of(slots, profile)
        offsets = sorted(seen)
        region = " ".join("+0x%X" % o for o in offsets[:18])
        if len(offsets) > 18:
            region += " (+%d more)" % (len(offsets) - 18)
        lines.append("| `%s` | `0x%X` | `0x%X` | %d | %d | %s |"
                     % (name, vtable, run, run_size, len(slots), region or "-"))
        print("%-26s vtable 0x%-8X slots %d  offsets %d" % (name, vtable, len(slots), len(offsets)))
    lines.append("")
    lines.append("## One class's member list, per class")
    lines.append("")
    for name, vtable, run, run_size in STRATEGIES:
        slots = vtables.get(vtable, [])
        seen, widths = fields_of(slots, profile)
        lines.append("### %s" % name)
        lines.append("")
        lines.append("Run 0x%X, %d bytes, slot 5 of vtable 0x%X." % (run, run_size, vtable))
        lines.append("")
        lines.append("| offset | width | shown by |")
        lines.append("|---|---|---|")
        for offset in sorted(seen):
            width = widths.get(offset) or 0
            lines.append("| `+0x%X` | %s | `0x%X` |" % (offset, width or "?", seen[offset]))
        lines.append("")
    text = "\n".join(lines) + "\n"
    if out:
        io.open(os.path.join(ROOT, out.replace("/", os.sep)), "w", encoding="utf-8", newline="\n").write(text)
        print("")
        print("wrote %s" % out)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
