# -*- coding: utf-8 -*-
"""Every readable string in the module, with the function that loads it -- the broadest name channel there is.

Usage: python g_strings_all.py [--min 4] [--function 0x14620] [--grep shear] [--out re/STRINGS.md]

The three channels this project has used read a FUNCTION name out of the module's own words in three shapes: the
`__PRETTY_FUNCTION__`-style string an assertion's second argument holds, the log format string a call site loads, and the member
expression an assertion's condition spells out. Each was found by looking for one shape. This tool stops looking for shapes and
prints the whole vocabulary instead: every printable run of characters in the image, with the address and, where it can be
attributed, the function that references it.

That breadth is the point, because it is the answer to "where else could a name be". A field name could be in a JSON key, an
error message, a format string, a symbol table entry, a deferred-report label, or a string that is only built at run time from
pieces -- and this prints all of them, so the next question is "which of these is a field name" rather than "where would I look".

Attribution is by a `lea reg, [rip+disp]` whose target lands on the string, which is how this compiler materialises an address.
A string with no attributed function is still printed, because a table of strings is data and the code that uses it may compute
the address rather than load it.
"""
import argparse
import io
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import lib as LIB  # noqa: E402
from lib import disasm, load_prof, rva2off  # noqa: E402

PRINTABLE = re.compile(rb"[\x20-\x7e]{4,}")
LEA = re.compile(r"^([a-z0-9]+), \[rip \+ 0x([0-9a-f]+)\]$")
FORBIDDEN = ("__cxx", "std::", "operator", "basic_string", "allocator", "_M_", "GCC:", "GNU C++")


def image():
    return LIB.data() if callable(getattr(LIB, "data", None)) else LIB.data


def harvest(blob, minimum):
    """file offset -> text."""
    out = {}
    for match in PRINTABLE.finditer(blob):
        text = match.group(0).decode("ascii", "replace")
        if len(text) >= minimum and text not in out.values():
            out[match.start()] = text
    return out


def main(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument("--min", type=int, default=4)
    parser.add_argument("--function", type=lambda v: int(v, 0), default=None)
    parser.add_argument("--grep", default=None)
    parser.add_argument("--out", default=None)
    parser.add_argument("--library", action="store_true", help="keep the standard library strings too")
    parser.add_argument("--limit", type=int, default=4000)
    args = parser.parse_args(argv)

    blob = image()
    offset_to_text = harvest(blob, args.min)
    print("printable strings of %d or more characters: %d" % (args.min, len(offset_to_text)))

    # attribute each string to the function whose `lea reg, [rip+disp]` lands on it
    profile = load_prof()
    owners = defaultdict(set)
    if args.function is not None:
        addresses = [args.function]
    else:
        addresses = list(profile)
    for address in addresses:
        info = profile.get(address) or {}
        size = info.get("size") or 0
        if size <= 0:
            continue
        for ins in disasm(address):
            if ins.address >= address + size:
                break
            m = LEA.match(ins.op_str)
            if ins.mnemonic != "lea" or not m:
                continue
            target = ins.address + ins.size + int(m.group(2), 16)
            try:
                file_offset = rva2off(target)
            except Exception:
                continue
            if file_offset in offset_to_text:
                owners[file_offset].add(address)

    rows = sorted(offset_to_text.items())
    if not args.library:
        rows = [(o, t) for o, t in rows if not any(marker in t for marker in FORBIDDEN)]
    if args.grep:
        needle = args.grep.lower()
        rows = [(o, t) for o, t in rows if needle in t.lower()]
    print("after filtering: %d" % len(rows))

    attributed = sum(1 for o, _t in rows if o in owners)
    print("attributed to a loading function: %d" % attributed)
    print("")
    for offset, text in rows[:args.limit]:
        who = ", ".join("0x%X" % a for a in sorted(owners.get(offset, []))[:3])
        print("%-14s %s" % (who or "-", text[:120]))

    if args.out:
        lines = ["# Every readable string in the module",
                 "",
                 "Generated by `re/g_strings_all.py`. The three name channels this project already used each looked for ONE",
                 "shape; this is the whole vocabulary, with the function that loads each string where one could be attributed.",
                 "",
                 "| string rva | loaded by | text |",
                 "|---|---|---|"]
        for offset, text in rows:
            who = ", ".join("`0x%X`" % a for a in sorted(owners.get(offset, []))[:3]) or ""
            lines.append("| `0x%X` | %s | `%s` |" % (offset, who, text.replace("|", "\\|")[:160]))
        io.open(os.path.join(os.path.dirname(HERE), args.out.replace("/", os.sep)), "w",
                encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
        print("")
        print("wrote %s" % args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
